require('dotenv').config();
const mongoose = require('mongoose');
const Spell = require('./models/Spell');

const SPELLS = [
  {
    name: 'Arcane Eye', level: 4, school: 'Divination',
    castingTime: '1 action', range: '30 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a bit of bat fur',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'You create an invisible, magical eye within range that hovers in the air for the duration. You mentally receive visual information from the eye, which has normal vision and darkvision out to 30 feet. The eye can look in every direction. As an action, you can move the eye up to 30 feet in any direction. There is no limit to how far away from you the eye can move, but it can\'t enter another plane of existence. A solid barrier blocks the eye\'s movement, but the eye can squeeze through an opening as small as 1 inch in diameter.',
    higherLevels: '',
    classes: ['Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Aura of Life', level: 4, school: 'Abjuration',
    castingTime: '1 action', range: 'Self (30-foot radius)',
    components: ['V'], materialComponent: '',
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: false,
    description: 'Life-preserving energy radiates from you in an aura with a 30-foot radius. Until the spell ends, the aura moves with you, centered on you. Each nonhostile creature in the aura (including you) has resistance to necrotic damage, and its hit point maximum can\'t be reduced. In addition, a nonhostile, living creature regains 1 hit point when it starts its turn in the aura with 0 hit points.',
    higherLevels: '',
    classes: ['Paladin'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Aura of Purity', level: 4, school: 'Abjuration',
    castingTime: '1 action', range: 'Self (30-foot radius)',
    components: ['V'], materialComponent: '',
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: false,
    description: 'Purifying energy radiates from you in an aura with a 30-foot radius. Until the spell ends, the aura moves with you, centered on you. Each nonhostile creature in the aura (including you) can\'t become diseased, has resistance to poison damage, and has advantage on saving throws against effects that cause any of the following conditions: blinded, charmed, deafened, frightened, paralyzed, poisoned, and stunned.',
    higherLevels: '',
    classes: ['Paladin'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Banishment', level: 4, school: 'Abjuration',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'S', 'M'], materialComponent: 'an item distasteful to the target',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You attempt to send one creature that you can see within range to another plane of existence. The target must succeed on a Charisma saving throw or be banished. If the target is native to the plane of existence you\'re on, you banish the target to a harmless demiplane. While there, the target is incapacitated. The target remains there until the spell ends, at which point the target reappears in the space it left or in the nearest unoccupied space if that space is occupied. If the target is native to a different plane of existence than the one you\'re on, the target is banished with a faint popping noise, returning to its home plane. If the spell lasts for its full duration, the target doesn\'t return. Otherwise, the target reappears in the space it left.',
    higherLevels: 'You can target one additional creature for each slot level above 4th.',
    classes: ['Cleric', 'Paladin', 'Sorcerer', 'Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'CHA', saveEffect: 'Negates',
  },
  {
    name: 'Blight', level: 4, school: 'Necromancy',
    castingTime: '1 action', range: '30 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'Necromantic energy washes over a creature of your choice that you can see within range, draining moisture and vitality from it. The target must make a Constitution saving throw. The target takes 8d8 necrotic damage on a failed save, or half as much damage on a successful one. This spell has no effect on undead or constructs. If you target a plant creature or a magical plant, it makes the saving throw with disadvantage, and the spell deals maximum damage to it. If you target a nonmagical plant that isn\'t a creature, such as a tree or shrub, it doesn\'t make a saving throw; it simply withers and dies.',
    higherLevels: 'The damage increases by 1d8 for each slot level above 4th.',
    classes: ['Druid', 'Sorcerer', 'Warlock', 'Wizard'],
    attackType: '', damage: '8d8', damageType: 'necrotic', scaling: '',
    savingThrow: 'CON', saveEffect: 'Half damage',
  },
  {
    name: 'Charm Monster', level: 4, school: 'Enchantment',
    castingTime: '1 action', range: '30 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: '1 hour', concentration: false, ritual: false,
    description: 'You attempt to charm a creature you can see within range. It must make a Wisdom saving throw, and it does so with advantage if you or your companions are fighting it. If it fails the saving throw, it is charmed by you until the spell ends or until you or your companions do anything harmful to it. The charmed creature is friendly to you. When the spell ends, the creature knows it was charmed by you.',
    higherLevels: 'You can target one additional creature for each slot level above 4th. The creatures must be within 30 feet of each other when you target them.',
    classes: ['Bard', 'Druid', 'Sorcerer', 'Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'WIS', saveEffect: 'Negates',
  },
  {
    name: 'Compulsion', level: 4, school: 'Enchantment',
    castingTime: '1 action', range: '30 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'Creatures of your choice that you can see within range and that can hear you must make a Wisdom saving throw. A target automatically succeeds on this saving throw if it can\'t be charmed. On a failed save, a target is affected by this spell. Until the spell ends, you can use a bonus action on each of your turns to designate a direction that is horizontal to you. Each affected target must use as much of its movement as possible to move in that direction on its next turn. It can take its action before it moves. After moving in this way, it can make another Wisdom saving throw to try to end the effect.',
    higherLevels: '',
    classes: ['Bard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'WIS', saveEffect: 'Negates',
  },
  {
    name: 'Confusion', level: 4, school: 'Enchantment',
    castingTime: '1 action', range: '90 feet',
    components: ['V', 'S', 'M'], materialComponent: 'three nut shells',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'This spell assaults and twists creatures\' minds, spawning delusions and provoking uncontrolled action. Each creature in a 10-foot-radius sphere centered on a point you choose within range must succeed on a Wisdom saving throw when you cast this spell or be affected by it. An affected target can\'t take reactions and must roll a d10 at the start of each of its turns to determine its behavior for that turn: 1 — moves in random direction; 2-6 — does nothing; 7-8 — makes melee attack against random creature in reach; 9-10 — acts normally. At the end of each of its turns, an affected target can make a Wisdom saving throw. If it succeeds, this effect ends for that target.',
    higherLevels: 'The radius of the sphere increases by 5 feet for each slot level above 4th.',
    classes: ['Bard', 'Druid', 'Sorcerer', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'WIS', saveEffect: 'Negates',
  },
  {
    name: 'Conjure Minor Elementals', level: 4, school: 'Conjuration',
    castingTime: '1 minute', range: '90 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'You summon elementals that appear in unoccupied spaces that you can see within range. You choose one of the following options for what appears:\n\nOne elemental of challenge rating 2 or lower\nTwo elementals of challenge rating 1 or lower\nFour elementals of challenge rating 1/2 or lower\nEight elementals of challenge rating 1/4 or lower\n\nAn elemental summoned by this spell disappears when it drops to 0 hit points or when the spell ends. The summoned creatures are friendly to you and your companions. Roll initiative for the summoned creatures as a group, which has its own turns. They obey any verbal commands that you issue to them (no action required by you). If you don\'t issue any commands to them, they defend themselves from hostile creatures, but otherwise take no actions.',
    higherLevels: 'You summon twice as many creatures at 6th level and three times as many at 8th level.',
    classes: ['Druid', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Conjure Woodland Beings', level: 4, school: 'Conjuration',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'S', 'M'], materialComponent: 'one holly berry per creature summoned',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'You summon fey creatures that appear in unoccupied spaces that you can see within range. Choose one of the following options for what appears:\n\nOne fey creature of challenge rating 2 or lower\nTwo fey creatures of challenge rating 1 or lower\nFour fey creatures of challenge rating 1/2 or lower\nEight fey creatures of challenge rating 1/4 or lower\n\nA summoned creature disappears when it drops to 0 hit points or when the spell ends. The summoned creatures are friendly to you and your companions. Roll initiative for the summoned creatures as a group. They obey any verbal commands that you issue to them (no action required by you). If you don\'t issue any commands to them, they defend themselves from hostile creatures, but otherwise take no actions.',
    higherLevels: 'You summon twice as many creatures at 6th level and three times as many at 8th level.',
    classes: ['Druid', 'Ranger'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Control Water', level: 4, school: 'Transmutation',
    castingTime: '1 action', range: '300 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a drop of water and a pinch of dust',
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: false,
    description: 'Until the spell ends, you control any freestanding water inside an area you choose that is a cube up to 100 feet on a side. You can choose from any of the following effects when you cast this spell. As an action on your turn, you can repeat the same effect or choose a different one.\n\nFlood. You cause the water level of all standing water in the area to rise by as much as 20 feet.\nPart Water. You cause water in the area to move apart and create a trench up to 100 feet long and 20 feet deep and wide.\nRedirect Flow. You cause flowing water in the area to move in a direction you choose.\nWhirlpool. You cause a whirlpool to form in the center of the area, dealing damage and restraining creatures that fail a Strength save.',
    higherLevels: '',
    classes: ['Cleric', 'Druid', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'STR', saveEffect: 'Negates whirlpool',
  },
  {
    name: 'Death Ward', level: 4, school: 'Abjuration',
    castingTime: '1 action', range: 'Touch',
    components: ['V', 'S'], materialComponent: '',
    duration: '8 hours', concentration: false, ritual: false,
    description: 'You touch a creature and grant it a measure of protection from death. The first time the target would drop to 0 hit points as a result of taking damage, the target instead drops to 1 hit point, and the spell ends. If the spell is still in effect when the target is subjected to an effect that would kill it instantaneously without dealing damage, that effect is negated against the target, and the spell ends.',
    higherLevels: '',
    classes: ['Cleric', 'Paladin'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Dimension Door', level: 4, school: 'Conjuration',
    castingTime: '1 action', range: '500 feet',
    components: ['V'], materialComponent: '',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You teleport yourself from your current location to any other spot within range. You arrive at exactly the spot desired. It can be a place you can see, one you can visualize, or one you can describe by stating distance and direction, such as "200 feet straight downward" or "upward to the northwest at a 45-degree angle, 300 feet." You can bring along objects as long as their weight doesn\'t exceed what you can carry. You can also bring one willing creature of your size or smaller who is carrying gear up to its carrying capacity. The creature must be within 5 feet of you when you cast this spell. If you would arrive in a place already occupied by an object or a creature, you and any creature traveling with you each take 4d6 force damage, and the spell fails to teleport you.',
    higherLevels: '',
    classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Divination', level: 4, school: 'Divination',
    castingTime: '1 action', range: 'Self',
    components: ['V', 'S', 'M'], materialComponent: 'incense and a sacrificial offering appropriate to your religion, together worth at least 25 gp, which the spell consumes',
    duration: 'Instantaneous', concentration: false, ritual: true,
    description: 'Your magic and an offering put you in contact with a god or a god\'s servants. You ask a single question concerning a specific goal, event, or activity to occur within 7 days. The DM offers a truthful reply. The reply might be a short phrase, a cryptic rhyme, or an omen. The spell doesn\'t take into account any possible circumstances that might change the outcome, such as the casting of additional spells or the loss or gain of a companion. If you cast the spell two or more times before finishing your next long rest, there is a cumulative 25 percent chance for each casting after the first that you get a random reading.',
    higherLevels: '',
    classes: ['Cleric'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Dominate Beast', level: 4, school: 'Enchantment',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You attempt to beguile a beast that you can see within range. It must succeed on a Wisdom saving throw or be charmed by you for the duration. If you or creatures that are friendly to you are fighting it, it has advantage on the saving throw. While the beast is charmed, you have a telepathic link with it as long as the two of you are on the same plane of existence. You can use this telepathic link to issue commands to the creature while you are conscious (no action required), which it does its best to obey. Each time the target takes damage, it makes a new Wisdom saving throw against the spell. If the saving throw succeeds, the spell ends.',
    higherLevels: 'Concentration up to 10 minutes at 5th level, up to 1 hour at 6th level, up to 8 hours at 7th level or higher.',
    classes: ['Druid', 'Sorcerer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'WIS', saveEffect: 'Negates',
  },
  {
    name: 'Elemental Bane', level: 4, school: 'Transmutation',
    castingTime: '1 action', range: '90 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'Choose one creature you can see within range, and choose one of the following damage types: acid, cold, fire, lightning, or thunder. The target must succeed on a Constitution saving throw or be affected by the spell for its duration. The first time each turn the affected target takes damage of the chosen type, the target takes an extra 2d6 damage of that type. Moreover, the target loses any resistance to that damage type until the spell ends.',
    higherLevels: 'You can target one additional creature for each slot level above 4th.',
    classes: ['Druid', 'Warlock', 'Wizard'],
    attackType: '', damage: '2d6', damageType: 'varies', scaling: '',
    savingThrow: 'CON', saveEffect: 'Negates',
  },
  {
    name: 'Evard\'s Black Tentacles', level: 4, school: 'Conjuration',
    castingTime: '1 action', range: '90 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a piece of tentacle from a giant octopus or a giant squid',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'Squirming, ebony tentacles fill a 20-foot square on ground that you can see within range. For the duration, these tentacles turn the ground in the area into difficult terrain. When a creature enters the affected area for the first time on a turn or starts its turn there, the creature must succeed on a Dexterity saving throw or take 3d6 bludgeoning damage and be restrained by the tentacles until the spell ends. A creature that starts its turn in the area and is already restrained by the tentacles takes 3d6 bludgeoning damage. A creature restrained by the tentacles can use its action to make a Strength or Dexterity check (its choice) against your spell save DC. On a success, it frees itself.',
    higherLevels: '',
    classes: ['Wizard'],
    attackType: '', damage: '3d6', damageType: 'bludgeoning', scaling: '',
    savingThrow: 'DEX', saveEffect: 'Not restrained',
  },
  {
    name: 'Fabricate', level: 4, school: 'Transmutation',
    castingTime: '10 minutes', range: '120 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You convert raw materials into products of the same material. For example, you can fabricate a wooden bridge from a clump of trees, a rope from a patch of hemp, and clothes from flax or wool. Choose raw materials that you can see within range. You can fabricate a Large or smaller object (contained within a 10-foot cube, or eight connected 5-foot cubes), given a sufficient quantity of raw material. If you are working with metal, stone, or another mineral substance, however, the fabricated object can be no larger than Medium (contained within a single 5-foot cube). The quality of objects made by the spell is commensurate with the quality of the raw materials. Creatures or magic items can\'t be created or transmuted by this spell. You also can\'t use it to create items that ordinarily require a high degree of craftsmanship, such as jewelry, weapons, glass, or armor, unless you have proficiency with the type of artisan\'s tools used to craft such objects.',
    higherLevels: '',
    classes: ['Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Fire Shield', level: 4, school: 'Evocation',
    castingTime: '1 action', range: 'Self',
    components: ['V', 'S', 'M'], materialComponent: 'a bit of phosphorus or a firefly',
    duration: '10 minutes', concentration: false, ritual: false,
    description: 'Thin and wispy flames wreathe your body for the duration, shedding bright light in a 10-foot radius and dim light for an additional 10 feet. You can end the spell early by using an action to dismiss it. The flames provide you with a warm shield or a chill shield, as you choose. The warm shield grants you resistance to cold damage, and the chill shield grants you resistance to fire damage. In addition, whenever a creature within 5 feet of you hits you with a melee attack, the shield erupts with flame. The attacker takes 2d8 fire damage from a warm shield, or 2d8 cold damage from a cold shield.',
    higherLevels: '',
    classes: ['Wizard'],
    attackType: '', damage: '2d8', damageType: 'fire', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Freedom of Movement', level: 4, school: 'Abjuration',
    castingTime: '1 action', range: 'Touch',
    components: ['V', 'S', 'M'], materialComponent: 'a leather strap, bound around the arm or a similar appendage',
    duration: '1 hour', concentration: false, ritual: false,
    description: 'You touch a willing creature. For the duration, the target\'s movement is unaffected by difficult terrain, and spells and other magical effects can neither reduce the target\'s speed nor cause the target to be paralyzed or restrained. The target can also spend 5 feet of movement to automatically escape from nonmagical restraints, such as manacles or a creature that has it grappled. Finally, being underwater imposes no penalties on the target\'s movement or attacks.',
    higherLevels: '',
    classes: ['Bard', 'Cleric', 'Druid', 'Ranger', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Giant Insect', level: 4, school: 'Transmutation',
    castingTime: '1 action', range: '30 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: false,
    description: 'You transform up to ten centipedes, three spiders, five wasps, or one scorpion within range into giant versions of their natural forms for the duration. A centipede becomes a giant centipede, a spider becomes a giant spider, a wasp becomes a giant wasp, and a scorpion becomes a giant scorpion. Each creature obeys your verbal commands, and in combat, they act on your turn each round. The DM has the statistics for these creatures and resolves their actions and movement. A creature remains in its giant size for the duration, until it drops to 0 hit points, or until you use an action to dismiss the effect on it. The DM might allow you to choose different targets.',
    higherLevels: '',
    classes: ['Druid'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Grasping Vine', level: 4, school: 'Conjuration',
    castingTime: '1 bonus action', range: '30 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You conjure a vine that sprouts from the ground in an unoccupied space of your choice that you can see within range. When you cast this spell, you can direct the vine to lash out at a creature within 30 feet of it that you can see. That creature must succeed on a Dexterity saving throw or be pulled 20 feet directly toward the vine. Until the spell ends, you can direct the vine to lash out at the same creature or another one as a bonus action on each of your turns.',
    higherLevels: '',
    classes: ['Druid', 'Ranger'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'DEX', saveEffect: 'Not pulled',
  },
  {
    name: 'Greater Invisibility', level: 4, school: 'Illusion',
    castingTime: '1 action', range: 'Touch',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You or a creature you touch becomes invisible until the spell ends. Anything the target is wearing or carrying is invisible as long as it is on the target\'s person.',
    higherLevels: '',
    classes: ['Bard', 'Sorcerer', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Guardian of Faith', level: 4, school: 'Conjuration',
    castingTime: '1 action', range: '30 feet',
    components: ['V'], materialComponent: '',
    duration: '8 hours', concentration: false, ritual: false,
    description: 'A Large spectral guardian appears and hovers for the duration in an unoccupied space of your choice that you can see within range. The guardian occupies that space and is indistinct except for a gleaming sword and shield emblazoned with the symbol of your deity. Any creature hostile to you that moves to a space within 10 feet of the guardian for the first time on a turn must succeed on a Dexterity saving throw. The creature takes 20 radiant damage on a failed save, or half as much damage on a successful one. The guardian vanishes when it has dealt a total of 60 damage.',
    higherLevels: '',
    classes: ['Cleric'],
    attackType: '', damage: '', damageType: 'radiant', scaling: '',
    savingThrow: 'DEX', saveEffect: 'Half damage',
  },
  {
    name: 'Hallucinatory Terrain', level: 4, school: 'Illusion',
    castingTime: '10 minutes', range: '300 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a stone, a twig, and a bit of green plant',
    duration: '24 hours', concentration: false, ritual: false,
    description: 'You make natural terrain in a 150-foot cube in range look, sound, and smell like some other sort of natural terrain. Thus, open fields or a road can be made to resemble a swamp, hill, crevasse, or some other difficult or impassable terrain. A pond can be made to seem like a grassy meadow, a precipice like a gentle slope, or a rock-strewn gully like a wide and smooth road. Manufactured structures, equipment, and creatures within the area aren\'t changed in appearance. The tactile characteristics of the terrain are unchanged, so creatures entering the area are likely to see through the illusion. If the difference isn\'t obvious by touch, a creature carefully examining the illusion can attempt an Intelligence (Investigation) check against your spell save DC to disbelieve it. A creature who discerns the illusion for what it is, sees it as a vague image superimposed on the terrain.',
    higherLevels: '',
    classes: ['Bard', 'Druid', 'Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Ice Storm', level: 4, school: 'Evocation',
    castingTime: '1 action', range: '300 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a pinch of dust and a few drops of water',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'A hail of rock-hard ice pounds to the ground in a 20-foot-radius, 40-foot-high cylinder centered on a point within range. Each creature in the cylinder must make a Dexterity saving throw. A creature takes 2d8 bludgeoning damage and 4d6 cold damage on a failed save, or half as much damage on a successful one. Hailstones turn the storm\'s area of effect into difficult terrain until the end of your next turn.',
    higherLevels: 'The bludgeoning damage increases by 1d8 for each slot level above 4th.',
    classes: ['Druid', 'Sorcerer', 'Wizard'],
    attackType: '', damage: '4d6', damageType: 'cold', scaling: '',
    savingThrow: 'DEX', saveEffect: 'Half damage',
  },
  {
    name: 'Leomund\'s Secret Chest', level: 4, school: 'Conjuration',
    castingTime: '1 action', range: 'Touch',
    components: ['V', 'S', 'M'], materialComponent: 'an exquisite chest, 3 feet by 2 feet by 2 feet, constructed from rare materials worth at least 5,000 gp, and a Tiny replica made from the same materials worth at least 50 gp',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You hide a chest, and all its contents, on the Ethereal Plane. You must touch the chest and the miniature replica that serves as a material component for the spell. The chest can contain up to 12 cubic feet of nonliving material (3 feet by 2 feet by 2 feet). While the chest remains on the Ethereal Plane, you can use an action and touch the replica to recall the chest. It appears in an unoccupied space on the ground within 5 feet of you. You can send the chest back to the Ethereal Plane by using an action and touching both the chest and the replica. After 60 days, there is a cumulative 5 percent chance per day that the spell\'s effect ends. This effect ends if you cast this spell again, if the smaller replica chest is destroyed, or if you choose to end the spell as an action. If the spell ends and the larger chest is on the Ethereal Plane, it is irretrievably lost.',
    higherLevels: '',
    classes: ['Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Locate Creature', level: 4, school: 'Divination',
    castingTime: '1 action', range: 'Self',
    components: ['V', 'S', 'M'], materialComponent: 'a bit of fur from a bloodhound',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'Describe or name a creature that is familiar to you. You sense the direction to the creature\'s location, as long as that creature is within 1,000 feet of you. If the creature is moving, you know the direction of its movement. The spell can locate a specific creature known to you, or the nearest creature of a specific kind (such as a human or a unicorn), so long as you have seen such a creature up close — within 30 feet — at least once. If the creature you described or named is in a different form, such as being under the effects of a polymorph spell, this spell doesn\'t locate the creature. This spell can\'t locate a creature if running water at least 10 feet wide blocks a direct path between you and the creature.',
    higherLevels: '',
    classes: ['Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Mordenkainen\'s Faithful Hound', level: 4, school: 'Conjuration',
    castingTime: '1 action', range: '30 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a tiny silver whistle, a piece of bone, and a thread',
    duration: '8 hours', concentration: false, ritual: false,
    description: 'You conjure a phantom watchdog in an unoccupied space that you can see within range, where it remains for the duration, until you dismiss it as an action, or until you move more than 100 feet away from it. The hound is invisible to all creatures except you and can\'t be harmed. When a Small or larger creature comes within 30 feet of it without first speaking the password that you specify when you cast this spell, the hound starts barking loudly. The hound sees invisible creatures and can see into the Ethereal Plane. It ignores illusions. At the start of each of your turns, the hound attempts to bite one creature within 5 feet of it that is hostile to you. The hound\'s attack bonus is equal to your spellcasting ability modifier + your proficiency bonus. On a hit, it deals 4d8 piercing damage.',
    higherLevels: '',
    classes: ['Wizard'],
    attackType: 'melee', damage: '4d8', damageType: 'piercing', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Mordenkainen\'s Private Sanctum', level: 4, school: 'Abjuration',
    castingTime: '10 minutes', range: '120 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a thin sheet of lead, a piece of opaque glass, a wad of cotton or cloth, and powdered chrysolite',
    duration: '24 hours', concentration: false, ritual: false,
    description: 'You make an area within range magically secure. The area is a cube that can be as small as 5 feet to as large as 100 feet on each side. The spell lasts for the duration or until you use an action to dismiss it. When you cast the spell, you decide what sort of security the spell provides, choosing any or all of the following properties: sound can\'t pass through the barrier, the barrier is opaque from the outside, divination spells can\'t target anything within the barrier, and teleportation into and out of the barrier is blocked. Casting this spell on the same spot every day for a year makes this effect permanent.',
    higherLevels: 'The area of the cube increases by 100 feet for each slot level above 4th.',
    classes: ['Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Otiluke\'s Resilient Sphere', level: 4, school: 'Evocation',
    castingTime: '1 action', range: '30 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a hemispherical piece of clear crystal and a matching hemispherical piece of gum arabic',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'A sphere of shimmering force encloses a creature or object of Large size or smaller within range. An unwilling creature must make a Dexterity saving throw. On a failed save, the creature is enclosed for the duration. Nothing — not physical objects, energy, or other spell effects — can pass through the barrier, in or out, though a creature in the sphere can breathe there. The sphere is immune to all damage, and a creature or object inside can\'t be damaged by attacks or effects originating from outside, nor can a creature inside the sphere damage anything outside it. The sphere is weightless and just large enough to contain the creature or object inside. An enclosed creature can use its action to push against the sphere\'s walls and thus roll the sphere at up to half the creature\'s speed. Similarly, the globe can be picked up and moved by other creatures. A disintegrate spell targeting the globe destroys it without harming anything inside it.',
    higherLevels: '',
    classes: ['Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'DEX', saveEffect: 'Negates',
  },
  {
    name: 'Phantasmal Killer', level: 4, school: 'Illusion',
    castingTime: '1 action', range: '120 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You tap into the nightmares of a creature you can see within range and create an illusory manifestation of its deepest fears, visible only to that creature. The target must make a Wisdom saving throw. On a failed save, the target becomes frightened for the duration. At the end of each of the target\'s turns before the spell ends, the target must succeed on a Wisdom saving throw or take 4d10 psychic damage. On a successful save, the spell ends.',
    higherLevels: 'The damage increases by 1d10 for each slot level above 4th.',
    classes: ['Wizard'],
    attackType: '', damage: '4d10', damageType: 'psychic', scaling: '',
    savingThrow: 'WIS', saveEffect: 'Negates',
  },
  {
    name: 'Polymorph', level: 4, school: 'Transmutation',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a caterpillar cocoon',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'This spell transforms a creature that you can see within range into a new form. An unwilling creature must make a Wisdom saving throw to avoid the effect. The spell has no effect on a shapechanger or a creature with 0 hit points. The transformation lasts for the duration, or until the target drops to 0 hit points or dies. The new form can be any beast whose challenge rating is equal to or less than the target\'s (or the target\'s level). The target\'s game statistics, including mental ability scores, are replaced by the statistics of the chosen beast. It retains its alignment and personality. The target assumes the hit points of its new form. When it reverts to its normal form, the creature returns to the number of hit points it had before it transformed. If it reverts as a result of dropping to 0 hit points, any excess damage carries over to its normal form.',
    higherLevels: '',
    classes: ['Bard', 'Druid', 'Sorcerer', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'WIS', saveEffect: 'Negates',
  },
  {
    name: 'Shadow of Moil', level: 4, school: 'Necromancy',
    castingTime: '1 action', range: 'Self',
    components: ['V', 'S', 'M'], materialComponent: 'an undead eyeball encased in a gem worth at least 150 gp',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'Flame-like shadows wreathe your body until the spell ends, causing you to become heavily obscured to others. The shadows turn dim light within 10 feet of you into darkness, and bright light in the same area to dim light. Until the spell ends, you have resistance to radiant damage. In addition, whenever a creature within 10 feet of you hits you with an attack, the shadows lash out at that creature, dealing it 2d8 necrotic damage.',
    higherLevels: '',
    classes: ['Warlock'],
    attackType: '', damage: '2d8', damageType: 'necrotic', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Sickening Radiance', level: 4, school: 'Evocation',
    castingTime: '1 action', range: '120 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: false,
    description: 'Dim, greenish light spreads within a 30-foot-radius sphere centered on a point you choose within range. The light spreads around corners, and it lasts until the spell ends. When a creature moves into the spell\'s area for the first time on a turn or starts its turn there, that creature must succeed on a Constitution saving throw or take 4d10 radiant damage, and it suffers one level of exhaustion and emits a dim, greenish light in a 5-foot radius. This light makes it impossible for the creature to benefit from being invisible. The light and any levels of exhaustion caused by this spell go away when the spell ends.',
    higherLevels: '',
    classes: ['Sorcerer', 'Warlock', 'Wizard'],
    attackType: '', damage: '4d10', damageType: 'radiant', scaling: '',
    savingThrow: 'CON', saveEffect: 'Negates',
  },
  {
    name: 'Staggering Smite', level: 4, school: 'Evocation',
    castingTime: '1 bonus action', range: 'Self',
    components: ['V'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'The next time you hit a creature with a melee weapon attack during this spell\'s duration, your weapon pierces both body and mind, and the attack deals an extra 4d6 psychic damage to the target. The target must make a Wisdom saving throw. On a failed save, it has disadvantage on attack rolls and ability checks, and can\'t take reactions, until the end of its next turn.',
    higherLevels: '',
    classes: ['Paladin'],
    attackType: '', damage: '4d6', damageType: 'psychic', scaling: '',
    savingThrow: 'WIS', saveEffect: 'No debuff',
  },
  {
    name: 'Stone Shape', level: 4, school: 'Transmutation',
    castingTime: '1 action', range: 'Touch',
    components: ['V', 'S', 'M'], materialComponent: 'soft clay, which must be worked into roughly the desired shape of the stone object',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You touch a stone object of Medium size or smaller or a section of stone no more than 5 feet in any dimension and form it into any shape that suits your purpose. So, for example, you could shape a large rock into a weapon, idol, or coffer, or make a small passage through a wall, as long as the wall is less than 5 feet thick. You could also shape a stone door or its frame to seal the door shut. The object you create can have up to two hinges and a latch, but finer mechanical detail isn\'t possible.',
    higherLevels: '',
    classes: ['Cleric', 'Druid', 'Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Stoneskin', level: 4, school: 'Abjuration',
    castingTime: '1 action', range: 'Touch',
    components: ['V', 'S', 'M'], materialComponent: 'diamond dust worth 100 gp, which the spell consumes',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'This spell turns the flesh of a willing creature you touch as hard as stone. Until the spell ends, the target has resistance to nonmagical bludgeoning, piercing, and slashing damage.',
    higherLevels: '',
    classes: ['Druid', 'Ranger', 'Sorcerer', 'Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Storm Sphere', level: 4, school: 'Evocation',
    castingTime: '1 action', range: '150 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'A 20-foot-radius sphere of whirling air springs into existence, centered on a point you choose within range. The sphere remains for the spell\'s duration. Each creature in the sphere when it appears or that ends its turn there must succeed on a Strength saving throw or take 2d6 bludgeoning damage. The sphere\'s space is difficult terrain. Until the spell ends, you can use a bonus action on each of your turns to cause a bolt of lightning to leap from the center of the sphere toward one creature you choose within 60 feet of the center. Make a ranged spell attack. On a hit, the target takes 4d6 lightning damage.',
    higherLevels: 'The damage for both effects increases by 1d6 for each slot level above 4th.',
    classes: ['Sorcerer', 'Wizard'],
    attackType: 'ranged', damage: '4d6', damageType: 'lightning', scaling: '',
    savingThrow: 'STR', saveEffect: 'No bludgeoning',
  },
  {
    name: 'Summon Greater Demon', level: 4, school: 'Conjuration',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a vial of blood from a humanoid killed within the past 24 hours',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'You utter foul words, summoning one demon from the chaos of the Abyss. You choose the demon\'s type, which must be one of challenge rating 5 or lower. The demon appears in an unoccupied space you can see within range, and the demon disappears when it drops to 0 hit points or when the spell ends. Roll initiative for the demon, which has its own turns. At the start of the demon\'s turn, if you don\'t maintain control by using a bonus action, the DM determines the demon\'s actions. The demon is hostile to all non-demons. If you draw a circle on the ground with the blood used as a material component, the demon can\'t cross that circle.',
    higherLevels: 'The challenge rating increases by 1 for each slot level above 4th.',
    classes: ['Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Wall of Fire', level: 4, school: 'Evocation',
    castingTime: '1 action', range: '120 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a small piece of phosphorus',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You create a wall of fire on a solid surface within range. You can make the wall up to 60 feet long, 20 feet high, and 1 foot thick, or a ringed wall up to 20 feet in diameter, 20 feet high, and 1 foot thick. The wall is opaque and lasts for the duration. When the wall appears, each creature within its area must make a Dexterity saving throw. On a failed save, a creature takes 5d8 fire damage, or half as much damage on a successful save. One side of the wall, selected by you when you cast this spell, deals 5d8 fire damage to each creature that ends its turn within 10 feet of that side or inside the wall. A creature takes the same damage when it enters the wall for the first time on a turn or ends its turn there. The other side of the wall deals no damage.',
    higherLevels: 'The damage increases by 1d8 for each slot level above 4th.',
    classes: ['Druid', 'Sorcerer', 'Wizard'],
    attackType: '', damage: '5d8', damageType: 'fire', scaling: '',
    savingThrow: 'DEX', saveEffect: 'Half damage',
  },
  {
    name: 'Watery Sphere', level: 4, school: 'Conjuration',
    castingTime: '1 action', range: '90 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a droplet of water',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You conjure up a sphere of water with a 5-foot radius at a point you can see within range. The sphere can hover but no more than 10 feet off the ground. The sphere remains for the spell\'s duration. Any creature in the sphere\'s space must make a Strength saving throw. On a successful save, a creature is ejected from that space to the nearest unoccupied space of the creature\'s choice outside the sphere. On a failed save, a creature is restrained by the sphere and is engulfed by the water. At the end of each of its turns, a restrained target can repeat the saving throw, ending the effect on itself on a success. As an action, you can move the sphere up to 30 feet in a straight line. If it moves over a pit, cliff, or other drop-off, it safely descends until it is hovering 10 feet above the ground. Any creature restrained by the sphere moves with it. The sphere can restrain a maximum of four Medium or smaller creatures or one Large creature.',
    higherLevels: '',
    classes: ['Druid', 'Sorcerer', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'STR', saveEffect: 'Ejected',
  },
];

async function seed() {
  await mongoose.connect(process.env.MONGODB_URI);
  console.log('Connected to MongoDB');

  const del = await Spell.deleteMany({ level: 4 });
  console.log(`Removed ${del.deletedCount} existing level 4 spells`);

  await Spell.insertMany(SPELLS);
  console.log(`Seeded ${SPELLS.length} level 4 spells`);

  console.log('Done');
  process.exit(0);
}

seed().catch(err => { console.error(err); process.exit(1); });
