require('dotenv').config();
const mongoose = require('mongoose');
const Spell = require('./models/Spell');

const SPELLS = [
  {
    name: 'Aid', level: 2, school: 'Abjuration',
    castingTime: '1 action', range: '30 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a tiny strip of white cloth',
    duration: '8 hours', concentration: false, ritual: false,
    description: 'Your spell bolsters your allies with toughness and resolve. Choose up to three creatures within range. Each target\'s hit point maximum and current hit points increase by 5 for the duration.',
    higherLevels: 'For each slot level above 2nd, a target\'s hit points increase by an additional 5.',
    classes: ['Cleric', 'Paladin', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Alter Self', level: 2, school: 'Transmutation',
    castingTime: '1 action', range: 'Self',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'You assume a different form. When you cast the spell, choose one of the following options, the effects of which last for the duration of the spell. While the spell lasts, you can end one option as an action to gain the benefits of a different one.\n\nAquatic Adaptation. You adapt your body to an aquatic environment, sprouting gills and growing webbing between your fingers. You can breathe underwater and gain a swimming speed equal to your walking speed.\n\nChange Appearance. You transform your appearance. You decide what you look like, including your height, weight, facial features, sound of your voice, hair length, coloration, and distinguishing characteristics, if any.\n\nNatural Weapons. You grow claws, fangs, spines, horns, or a different natural weapon of your choice. Your unarmed strikes deal 1d6 bludgeoning, piercing, or slashing damage, as appropriate to the natural weapon you chose, and you are proficient with your unarmed strikes. Finally, the natural weapon is magic and you have a +1 bonus to the attack and damage rolls you make using it.',
    higherLevels: '',
    classes: ['Sorcerer', 'Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Animal Messenger', level: 2, school: 'Enchantment',
    castingTime: '1 action', range: '30 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a morsel of food',
    duration: '24 hours', concentration: false, ritual: true,
    description: 'By means of this spell, you use an animal to deliver a message. Choose a Tiny beast you can see within range, such as a squirrel, a blue jay, or a bat. You specify a location, which you must have visited, and a recipient who matches a general description, such as "a man or woman dressed in the uniform of the town guard" or "a red-haired dwarf wearing a pointed hat." You also speak a message of up to twenty-five words. The target beast travels for the duration of the spell toward the specified location, covering about 50 miles per 24 hours for a flying messenger, or 25 miles for other animals. When the messenger arrives, it delivers your message to the creature that you described, replicating the sound of your voice.',
    higherLevels: 'The duration of the spell increases by 48 hours for each slot level above 2nd.',
    classes: ['Bard', 'Druid', 'Ranger'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Arcane Lock', level: 2, school: 'Abjuration',
    castingTime: '1 action', range: 'Touch',
    components: ['V', 'S', 'M'], materialComponent: 'gold dust worth at least 25 gp, which the spell consumes',
    duration: 'Until dispelled', concentration: false, ritual: false,
    description: 'You touch a closed door, window, gate, chest, or other entryway, and it becomes locked for the duration. You and the creatures you designate when you cast this spell can open the object normally. You can also set a password that, when spoken within 5 feet of the object, suppresses this spell for 1 minute. Otherwise, it is impassable until it is broken or the spell is dispelled or suppressed. Casting knock on the object suppresses arcane lock for 10 minutes. While affected by this spell, the object is more difficult to break or force open; the DC to break it or pick any locks on it increases by 10.',
    higherLevels: '',
    classes: ['Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Augury', level: 2, school: 'Divination',
    castingTime: '1 minute', range: 'Self',
    components: ['V', 'S', 'M'], materialComponent: 'specially marked sticks, bones, or similar tokens worth at least 25 gp',
    duration: 'Instantaneous', concentration: false, ritual: true,
    description: 'By casting gem-inlaid sticks, rolling dragon bones, laying out ornate cards, or employing some other divining tool, you receive an omen from an otherworldly entity about the results of a specific course of action that you plan to take within the next 30 minutes. The DM chooses from the following possible omens:\n\nWeal, for good results\nWoe, for bad results\nWeal and woe, for both good and bad results\nNothing, for results that aren\'t especially good or bad\n\nThe spell doesn\'t take into account any possible circumstances that might change the outcome, such as the casting of additional spells or the loss or gain of a companion. If you cast the spell two or more times before completing your next long rest, there is a cumulative 25 percent chance for each casting after the first that you get a random reading.',
    higherLevels: '',
    classes: ['Cleric'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Barkskin', level: 2, school: 'Transmutation',
    castingTime: '1 action', range: 'Touch',
    components: ['V', 'S', 'M'], materialComponent: 'a handful of oak bark',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'You touch a willing creature. Until the spell ends, the target\'s skin has a rough, bark-like appearance, and the target\'s AC can\'t be less than 16, regardless of what kind of armor it is wearing.',
    higherLevels: '',
    classes: ['Druid', 'Ranger'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Beast Sense', level: 2, school: 'Divination',
    castingTime: '1 action', range: 'Touch',
    components: ['S'], materialComponent: '',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: true,
    description: 'You touch a willing beast. For the duration of the spell, you can use your action to see through the beast\'s eyes and hear what it hears, and continue to do so until you use your action to return to your normal senses. While perceiving through the beast\'s senses, you gain the benefits of any special senses possessed by that creature, though you are blinded and deafened to your own surroundings.',
    higherLevels: '',
    classes: ['Druid', 'Ranger'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Blindness/Deafness', level: 2, school: 'Necromancy',
    castingTime: '1 action', range: '30 feet',
    components: ['V'], materialComponent: '',
    duration: '1 minute', concentration: false, ritual: false,
    description: 'You can blind or deafen a foe. Choose one creature that you can see within range to make a Constitution saving throw. If it fails, the target is either blinded or deafened (your choice) for the duration. At the end of each of its turns, the target can make a Constitution saving throw. On a success, the spell ends.',
    higherLevels: 'You can target one additional creature for each slot level above 2nd.',
    classes: ['Bard', 'Cleric', 'Sorcerer', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'CON', saveEffect: 'Negates',
  },
  {
    name: 'Blur', level: 2, school: 'Illusion',
    castingTime: '1 action', range: 'Self',
    components: ['V'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'Your body becomes blurred, shifting and wavering to all who can see you. For the duration, any creature has disadvantage on attack rolls against you. An attacker is immune to this effect if it doesn\'t rely on sight, as with blindsight, or can see through illusions, as with truesight.',
    higherLevels: '',
    classes: ['Sorcerer', 'Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Branding Smite', level: 2, school: 'Evocation',
    castingTime: '1 bonus action', range: 'Self',
    components: ['V'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'The next time you hit a creature with a weapon attack before this spell ends, the weapon gleams with astral radiance as you strike. The attack deals an extra 2d6 radiant damage to the target, which becomes visible if it\'s invisible, and the target sheds dim light in a 5-foot radius and can\'t become invisible until the spell ends.',
    higherLevels: 'The extra damage increases by 1d6 for each slot level above 2nd.',
    classes: ['Paladin'],
    attackType: '', damage: '2d6', damageType: 'radiant', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Calm Emotions', level: 2, school: 'Enchantment',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You attempt to suppress strong emotions in a group of people. Each humanoid in a 20-foot-radius sphere centered on a point you choose within range must make a Charisma saving throw; a creature can choose to fail this saving throw if it wishes. If a creature fails its saving throw, choose one of the following two effects.\n\nYou can suppress any effect causing a target to be charmed or frightened. When this spell ends, any suppressed effect resumes, provided that its duration has not expired in the meantime.\n\nAlternatively, you can make a target indifferent about creatures of your choice that it is hostile toward. This indifference ends if the target is attacked or harmed by a spell or if it witnesses any of its friends being harmed.',
    higherLevels: '',
    classes: ['Bard', 'Cleric'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'CHA', saveEffect: 'Negates',
  },
  {
    name: 'Cloud of Daggers', level: 2, school: 'Conjuration',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a sliver of glass',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You fill the air with spinning daggers in a cube 5 feet on each side, centered on a point you choose within range. A creature takes 4d4 slashing damage when it enters the spell\'s area for the first time on a turn or starts its turn there.',
    higherLevels: 'The damage increases by 2d4 for each slot level above 2nd.',
    classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    attackType: '', damage: '4d4', damageType: 'slashing', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Continual Flame', level: 2, school: 'Evocation',
    castingTime: '1 action', range: 'Touch',
    components: ['V', 'S', 'M'], materialComponent: 'ruby dust worth 50 gp, which the spell consumes',
    duration: 'Until dispelled', concentration: false, ritual: false,
    description: 'A flame, equivalent in brightness to a torch, springs forth from an object that you touch. The effect looks like a regular flame, but it creates no heat and doesn\'t use oxygen. A continual flame can be covered or hidden but not smothered or quenched.',
    higherLevels: '',
    classes: ['Cleric', 'Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Cordon of Arrows', level: 2, school: 'Transmutation',
    castingTime: '1 action', range: '5 feet',
    components: ['V', 'S', 'M'], materialComponent: 'four or more arrows or bolts',
    duration: '8 hours', concentration: false, ritual: false,
    description: 'You plant four pieces of nonmagical ammunition — arrows or crossbow bolts — in the ground within range and lay magic upon them to protect an area. Until the spell ends, whenever a creature other than you comes within 30 feet of the ammunition for the first time on a turn or ends its turn there, one piece of ammunition flies up to strike it. The creature must succeed on a Dexterity saving throw or take 1d6 piercing damage. The piece of ammunition is then destroyed. The spell ends when no ammunition remains.',
    higherLevels: 'The amount of ammunition that can be affected increases by two for each slot level above 2nd.',
    classes: ['Ranger'],
    attackType: '', damage: '1d6', damageType: 'piercing', scaling: '',
    savingThrow: 'DEX', saveEffect: 'Negates',
  },
  {
    name: 'Crown of Madness', level: 2, school: 'Enchantment',
    castingTime: '1 action', range: '120 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'One humanoid of your choice that you can see within range must succeed on a Wisdom saving throw or become charmed by you for the duration. While the target is charmed in this way, a twisted crown of jagged iron appears on its head, and a madness glows in its eyes. The charmed target must use its action before moving on each of its turns to make a melee attack against a creature other than itself that you mentally choose. The target can act normally on its turn if you choose no creature or if none are within its reach. On your subsequent turns, you must use your action to maintain control over the target, or the spell ends. Also, the target can make a Wisdom saving throw at the end of each of its turns. On a success, the spell ends.',
    higherLevels: '',
    classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'WIS', saveEffect: 'Negates',
  },
  {
    name: 'Darkness', level: 2, school: 'Evocation',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'M'], materialComponent: 'bat fur and a drop of pitch or piece of coal',
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: false,
    description: 'Magical darkness spreads from a point you choose within range to fill a 15-foot-radius sphere for the duration. The darkness spreads around corners. A creature with darkvision can\'t see through this darkness, and nonmagical light can\'t illuminate it. If the point you choose is on an object you are holding or one that isn\'t being worn or carried, the darkness emanates from the object and moves with it. Completely covering the source of the darkness with an opaque object, such as a bowl or a helm, blocks the darkness. If any of this spell\'s area overlaps with an area of light created by a spell of 2nd level or lower, the spell that created the light is dispelled.',
    higherLevels: '',
    classes: ['Sorcerer', 'Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Darkvision', level: 2, school: 'Transmutation',
    castingTime: '1 action', range: 'Touch',
    components: ['V', 'S', 'M'], materialComponent: 'either a pinch of dried carrot or an agate',
    duration: '8 hours', concentration: false, ritual: false,
    description: 'You touch a willing creature to grant it the ability to see in the dark. For the duration, that creature has darkvision out to a range of 60 feet.',
    higherLevels: '',
    classes: ['Druid', 'Ranger', 'Sorcerer', 'Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Detect Thoughts', level: 2, school: 'Divination',
    castingTime: '1 action', range: 'Self',
    components: ['V', 'S', 'M'], materialComponent: 'a copper piece',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'For the duration, you can read the thoughts of certain creatures. When you cast the spell and as your action on each turn until the spell ends, you can focus your mind on any one creature that you can see within 30 feet of you. If the creature you choose has an Intelligence of 3 or lower or doesn\'t speak any language, the creature is unaffected. You initially learn the surface thoughts of the creature — what is most on its mind in that moment. As an action, you can either shift your attention to another creature\'s thoughts or attempt to probe deeper into the same creature\'s mind. If you probe deeper, the target must make a Wisdom saving throw. If it fails, you gain insight into its reasoning (if any), its emotional state, and something that looms large in its mind. If it succeeds, the spell ends.',
    higherLevels: '',
    classes: ['Bard', 'Sorcerer', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'WIS', saveEffect: 'Spell ends',
  },
  {
    name: 'Dragon\'s Breath', level: 2, school: 'Transmutation',
    castingTime: '1 bonus action', range: 'Touch',
    components: ['V', 'S', 'M'], materialComponent: 'a hot pepper',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You touch one willing creature and imbue it with the power to spew magical energy from its mouth, provided it has one. Choose acid, cold, fire, lightning, or poison. Until the spell ends, the creature can use an action to exhale energy of the chosen type in a 15-foot cone. Each creature in that area must make a Dexterity saving throw, taking 3d6 damage of the chosen type on a failed save, or half as much damage on a successful one.',
    higherLevels: 'The damage increases by 1d6 for each slot level above 2nd.',
    classes: ['Sorcerer', 'Wizard'],
    attackType: '', damage: '3d6', damageType: 'varies', scaling: '',
    savingThrow: 'DEX', saveEffect: 'Half damage',
  },
  {
    name: 'Dust Devil', level: 2, school: 'Conjuration',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a pinch of dust',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'Choose an unoccupied 5-foot cube of air that you can see within range. An elemental force that resembles a dust devil appears in the cube and lasts for the spell\'s duration. Any creature that ends its turn within 5 feet of the dust devil must make a Strength saving throw. On a failed save, the creature takes 1d8 bludgeoning damage and is pushed 10 feet away. On a successful save, the creature takes half as much damage and isn\'t pushed. As a bonus action, you can move the dust devil up to 30 feet in any direction. If the dust devil moves over sand, dust, loose dirt, or small gravel, it sucks up the material and forms a 10-foot-radius cloud of debris around itself that lasts until the start of your next turn. The cloud heavily obscures its area.',
    higherLevels: 'The damage increases by 1d8 for each slot level above 2nd.',
    classes: ['Druid', 'Sorcerer', 'Wizard'],
    attackType: '', damage: '1d8', damageType: 'bludgeoning', scaling: '',
    savingThrow: 'STR', saveEffect: 'Half damage',
  },
  {
    name: 'Earthbind', level: 2, school: 'Transmutation',
    castingTime: '1 action', range: '300 feet',
    components: ['V'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'Choose one creature you can see within range. Yellow strips of magical energy loop around the creature. The target must succeed on a Strength saving throw, or its flying speed (if any) is reduced to 0 feet for the spell\'s duration. An airborne creature affected by this spell safely descends at 60 feet per round until it reaches the ground or the spell ends.',
    higherLevels: '',
    classes: ['Druid', 'Sorcerer', 'Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'STR', saveEffect: 'Negates',
  },
  {
    name: 'Enhance Ability', level: 2, school: 'Transmutation',
    castingTime: '1 action', range: 'Touch',
    components: ['V', 'S', 'M'], materialComponent: 'fur or a feather from a beast',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'You touch a creature and bestow upon it a magical enhancement. Choose one of the following effects; the target gains that effect until the spell ends.\n\nBear\'s Endurance. The target has advantage on Constitution checks. It also gains 2d6 temporary hit points, which are lost when the spell ends.\nBull\'s Strength. The target has advantage on Strength checks, and his or her carrying capacity doubles.\nCat\'s Grace. The target has advantage on Dexterity checks. It also doesn\'t take damage from falling 20 feet or less if it isn\'t incapacitated.\nEagle\'s Splendor. The target has advantage on Charisma checks.\nFox\'s Cunning. The target has advantage on Intelligence checks.\nOwl\'s Wisdom. The target has advantage on Wisdom checks.',
    higherLevels: 'You can target one additional creature for each slot level above 2nd.',
    classes: ['Bard', 'Cleric', 'Druid', 'Sorcerer', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Enlarge/Reduce', level: 2, school: 'Transmutation',
    castingTime: '1 action', range: '30 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a pinch of powdered iron',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You cause a creature or an object you can see within range to grow larger or smaller for the duration. Choose either a creature or an object that is neither worn nor carried. If the target is unwilling, it can make a Constitution saving throw. On a success, the spell has no effect.\n\nEnlarge. The target\'s size doubles in all dimensions, and its weight is multiplied by eight. This growth increases its size by one category. If there isn\'t enough room for the target to double its size, the creature or object attains the maximum possible size in the space available. Until the spell ends, the target also has advantage on Strength checks and Strength saving throws. The target\'s weapons also grow to match its new size. While these weapons are enlarged, the target\'s attacks with them deal 1d4 extra damage.\n\nReduce. The target\'s size is halved in all dimensions, and its weight is reduced to one-eighth of normal. This reduction decreases its size by one category. Until the spell ends, the target also has disadvantage on Strength checks and Strength saving throws. The target\'s weapons also shrink to match its new size. While these weapons are reduced, the target\'s attacks with them deal 1d4 less damage (this can\'t reduce the damage below 1).',
    higherLevels: '',
    classes: ['Sorcerer', 'Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'CON', saveEffect: 'Negates',
  },
  {
    name: 'Enthrall', level: 2, school: 'Enchantment',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: '1 minute', concentration: false, ritual: false,
    description: 'You weave a distracting string of words, causing creatures of your choice that you can see within range and that can hear you to make a Wisdom saving throw. Any creature that can\'t be charmed succeeds on this saving throw automatically, and if you or your companions are fighting a creature, it has advantage on the save. On a failed save, the target has disadvantage on Wisdom (Perception) checks made to perceive any creature other than you until the spell ends or until the target can no longer hear you. The spell ends if you are incapacitated or can no longer speak.',
    higherLevels: '',
    classes: ['Bard', 'Warlock'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'WIS', saveEffect: 'Negates',
  },
  {
    name: 'Find Steed', level: 2, school: 'Conjuration',
    castingTime: '10 minutes', range: '30 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You summon a spirit that assumes the form of an unusually intelligent, strong, and loyal steed, creating a long-lasting bond with it. Appearing in an unoccupied space within range, the steed takes on a form that you choose: a warhorse, a pony, a camel, an elk, or a mastiff. The steed has the statistics of the chosen form, though it is a celestial, fey, or fiend (your choice) instead of its normal type. Additionally, if your steed has an Intelligence of 5 or less, its Intelligence becomes 6, and it gains the ability to understand one language of your choice that you speak. Your steed serves you as a mount, both in combat and out, and you have an instinctive bond with it that allows you to fight as a seamless unit. While mounted on your steed, you can make any spell you cast that targets only you also target your steed.',
    higherLevels: '',
    classes: ['Paladin'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Find Traps', level: 2, school: 'Divination',
    castingTime: '1 action', range: '120 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You sense the presence of any trap within range that is within line of sight. A trap, for the purpose of this spell, includes anything that would inflict a sudden or unexpected effect you consider harmful or undesirable, which was specifically intended as such by its creator. Thus, the spell would sense an area affected by the alarm spell, a glyph of warding, or a mechanical pit trap, but it would not reveal a natural weakness in the floor, an unstable ceiling, or a hidden sinkhole. This spell merely reveals that a trap is present. You don\'t learn the location of each trap, but you do learn the general nature of the danger posed by a trap you sense.',
    higherLevels: '',
    classes: ['Cleric', 'Druid', 'Ranger'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Flame Blade', level: 2, school: 'Evocation',
    castingTime: '1 bonus action', range: 'Self',
    components: ['V', 'S', 'M'], materialComponent: 'leaf of sumac',
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: false,
    description: 'You evoke a fiery blade in your free hand. The blade is similar in size and shape to a scimitar, and it lasts for the duration. If you let go of the blade, it disappears, but you can evoke the blade again as a bonus action. You can use your action to make a melee spell attack with the fiery blade. On a hit, the target takes 3d6 fire damage. The flaming blade sheds bright light in a 10-foot radius and dim light for an additional 10 feet.',
    higherLevels: 'The damage increases by 1d6 for every two slot levels above 2nd.',
    classes: ['Druid'],
    attackType: 'melee', damage: '3d6', damageType: 'fire', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Flaming Sphere', level: 2, school: 'Conjuration',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a bit of tallow, a pinch of brimstone, and a dusting of powdered iron',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'A 5-foot-diameter sphere of fire appears in an unoccupied space of your choice within range and lasts for the duration. Any creature that ends its turn within 5 feet of the sphere must make a Dexterity saving throw. The creature takes 2d6 fire damage on a failed save, or half as much damage on a successful one. As a bonus action, you can move the sphere up to 30 feet. If you ram the sphere into a creature, that creature must make the saving throw against the sphere\'s damage, and the sphere stops moving this turn. When you move the sphere, you can direct it over barriers up to 5 feet tall and jump it across pits up to 10 feet wide. The sphere ignites flammable objects not being worn or carried, and it sheds bright light in a 20-foot radius and dim light for an additional 20 feet.',
    higherLevels: 'The damage increases by 1d6 for each slot level above 2nd.',
    classes: ['Druid', 'Wizard'],
    attackType: '', damage: '2d6', damageType: 'fire', scaling: '',
    savingThrow: 'DEX', saveEffect: 'Half damage',
  },
  {
    name: 'Gentle Repose', level: 2, school: 'Necromancy',
    castingTime: '1 action', range: 'Touch',
    components: ['V', 'S', 'M'], materialComponent: 'a pinch of salt and one copper piece placed on each of the corpse\'s eyes, which must remain there for the duration',
    duration: '10 days', concentration: false, ritual: true,
    description: 'You touch a corpse or other remains. For the duration, the target is protected from decay and can\'t become undead. The spell also effectively extends the time limit on raising the target from the dead, since days spent under the influence of this spell don\'t count against the time limit of spells such as raise dead.',
    higherLevels: '',
    classes: ['Cleric', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Gust of Wind', level: 2, school: 'Evocation',
    castingTime: '1 action', range: 'Self (60-foot line)',
    components: ['V', 'S', 'M'], materialComponent: 'a legume seed',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'A line of strong wind 60 feet long and 10 feet wide blasts from you in a direction you choose for the spell\'s duration. Each creature that starts its turn in the line must succeed on a Strength saving throw or be pushed 15 feet away from you in a direction following the line. Any creature in the line must spend 2 feet of movement for every 1 foot it moves when moving closer to you. The gust disperses gas or vapor, and it extinguishes candles, torches, and similar unprotected flames in the area. It causes protected flames, such as those of lanterns, to dance wildly and has a 50 percent chance to extinguish them.',
    higherLevels: '',
    classes: ['Druid', 'Sorcerer', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'STR', saveEffect: 'Negates push',
  },
  {
    name: 'Heat Metal', level: 2, school: 'Transmutation',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a piece of iron and a flame',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'Choose a manufactured metal object, such as a metal weapon or a suit of heavy or medium metal armor, that you can see within range. You cause the object to glow red-hot. Any creature in physical contact with the object takes 2d8 fire damage when you cast the spell. Until the spell ends, you can use a bonus action on each of your subsequent turns to cause this damage again. If a creature is holding or wearing the object and takes the damage from it, the creature must succeed on a Constitution saving throw or drop the object if it can. If it doesn\'t drop the object, it has disadvantage on attack rolls and ability checks until the start of your next turn.',
    higherLevels: 'The damage increases by 1d8 for each slot level above 2nd.',
    classes: ['Bard', 'Druid', 'Artificer'],
    attackType: '', damage: '2d8', damageType: 'fire', scaling: '',
    savingThrow: 'CON', saveEffect: 'Doesn\'t drop object',
  },
  {
    name: 'Hold Person', level: 2, school: 'Enchantment',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a small, straight piece of iron',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'Choose a humanoid that you can see within range. The target must succeed on a Wisdom saving throw or be paralyzed for the duration. At the end of each of its turns, the target can make another Wisdom saving throw. On a success, the spell ends on the target.',
    higherLevels: 'You can target one additional humanoid for each slot level above 2nd. The humanoids must be within 30 feet of each other when you target them.',
    classes: ['Bard', 'Cleric', 'Druid', 'Sorcerer', 'Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'WIS', saveEffect: 'Negates',
  },
  {
    name: 'Invisibility', level: 2, school: 'Illusion',
    castingTime: '1 action', range: 'Touch',
    components: ['V', 'S', 'M'], materialComponent: 'an eyelash encased in gum arabic',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'A creature you touch becomes invisible until the spell ends. Anything the target is wearing or carrying is invisible as long as it is on the target\'s person. The spell ends for a target that attacks or casts a spell.',
    higherLevels: 'You can target one additional creature for each slot level above 2nd.',
    classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Knock', level: 2, school: 'Transmutation',
    castingTime: '1 action', range: '60 feet',
    components: ['V'], materialComponent: '',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'Choose an object that you can see within range. The object can be a door, a box, a chest, a set of manacles, a padlock, or another object that contains a mundane or magical means that prevents access. A target that is held shut by a mundane lock or that is stuck or barred becomes unlocked, unstuck, or unbarred. If the object has multiple locks, only one of them is unlocked. If you choose a target that is held shut with arcane lock, that spell is suppressed for 10 minutes, during which time the target can be opened and shut normally. When you cast the spell, a loud knock, audible from as far away as 300 feet, emanates from the target object.',
    higherLevels: '',
    classes: ['Bard', 'Sorcerer', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Lesser Restoration', level: 2, school: 'Abjuration',
    castingTime: '1 action', range: 'Touch',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You touch a creature and can end either one disease or one condition afflicting it. The condition can be blinded, deafened, paralyzed, or poisoned.',
    higherLevels: '',
    classes: ['Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Levitate', level: 2, school: 'Transmutation',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'S', 'M'], materialComponent: 'either a small leather loop or a piece of golden wire bent into a cup shape with a long shank on one end',
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: false,
    description: 'One creature or loose object of your choice that you can see within range rises vertically, up to 20 feet, and remains suspended there for the duration. The spell can levitate a target that weighs up to 500 pounds. An unwilling creature that succeeds on a Constitution saving throw is unaffected. The target can move only by pushing or pulling against a fixed object or surface within reach (such as a wall or a ceiling), which allows it to move as if it were climbing. You can change the target\'s altitude by up to 20 feet in either direction on your turn. If you are the target, you can move up or down as part of your move. Otherwise, you can use your action to move the target, which must remain within the spell\'s range. When the spell ends, the target floats gently to the ground if it is still aloft.',
    higherLevels: '',
    classes: ['Sorcerer', 'Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'CON', saveEffect: 'Negates',
  },
  {
    name: 'Locate Animals or Plants', level: 2, school: 'Divination',
    castingTime: '1 action', range: 'Self',
    components: ['V', 'S', 'M'], materialComponent: 'a bit of fur from a bloodhound',
    duration: 'Instantaneous', concentration: false, ritual: true,
    description: 'Describe or name a specific kind of beast or plant. Concentrating on the voice of nature in your surroundings, you learn the direction and distance to the closest creature or plant of that kind within 5 miles, if any are present.',
    higherLevels: '',
    classes: ['Bard', 'Druid', 'Ranger'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Locate Object', level: 2, school: 'Divination',
    castingTime: '1 action', range: 'Self',
    components: ['V', 'S', 'M'], materialComponent: 'a forked twig',
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: false,
    description: 'Describe or name an object that is familiar to you. You sense the direction to the object\'s location, as long as that object is within 1,000 feet of you. If the object is in motion, you know the direction of its movement. The spell can locate a specific object known to you, as long as you have seen it up close — within 30 feet — at least once. Alternatively, the spell can locate the nearest object of a particular kind, such as a certain kind of apparel, jewelry, furniture, tool, or weapon. This spell can\'t locate an object if any thickness of lead, even a thin sheet, blocks a direct path between you and the object.',
    higherLevels: '',
    classes: ['Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Magic Mouth', level: 2, school: 'Illusion',
    castingTime: '1 minute', range: '30 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a small bit of honeycomb and jade dust worth at least 10 gp, which the spell consumes',
    duration: 'Until dispelled', concentration: false, ritual: true,
    description: 'You implant a message within an object in range, a message that is uttered when a trigger condition is met. Choose an object that you can see and that isn\'t being worn or carried by another creature. Then speak the message, which must be 25 words or less, though it can be delivered over as long as 10 minutes. Finally, determine the circumstance that will trigger the spell to deliver your message. When that circumstance occurs, a magical mouth appears on the object and recites the message in your voice and at the same volume you spoke. If the object you chose has a mouth or something that looks like a mouth (for example, the mouth of a statue), the magical mouth appears there so that the words appear to come from the object\'s mouth.',
    higherLevels: '',
    classes: ['Bard', 'Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Magic Weapon', level: 2, school: 'Transmutation',
    castingTime: '1 bonus action', range: 'Touch',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'You touch a nonmagical weapon. Until the spell ends, that weapon becomes a magic weapon with a +1 bonus to attack rolls and damage rolls.',
    higherLevels: 'The bonus increases to +2 when you cast this spell using a 4th-level slot, or +3 when you use a 6th-level or higher spell slot.',
    classes: ['Paladin', 'Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Melf\'s Acid Arrow', level: 2, school: 'Evocation',
    castingTime: '1 action', range: '90 feet',
    components: ['V', 'S', 'M'], materialComponent: 'powdered rhubarb leaf and an adder\'s stomach',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'A shimmering green arrow streaks toward a target within range and bursts in a spray of acid. Make a ranged spell attack against the target. On a hit, the target takes 4d4 acid damage immediately and 2d4 acid damage at the end of its next turn. On a miss, the arrow splashes the target with acid for half as much of the initial damage and no damage at the end of its next turn.',
    higherLevels: 'Both the initial damage and the later damage increase by 1d4 for each slot level above 2nd.',
    classes: ['Wizard'],
    attackType: 'ranged', damage: '4d4', damageType: 'acid', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Mind Spike', level: 2, school: 'Divination',
    castingTime: '1 action', range: '60 feet',
    components: ['S'], materialComponent: '',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'You reach into the mind of one creature you can see within range. The target must make a Wisdom saving throw, taking 3d8 psychic damage on a failed save, or half as much damage on a successful one. On a failed save, you also always know the target\'s location until the spell ends, but only while the two of you are on the same plane of existence. While you have this knowledge, the target can\'t become hidden from you, and if it\'s invisible, it gains no benefit from that condition against you.',
    higherLevels: 'The damage increases by 1d8 for each slot level above 2nd.',
    classes: ['Sorcerer', 'Warlock', 'Wizard'],
    attackType: '', damage: '3d8', damageType: 'psychic', scaling: '',
    savingThrow: 'WIS', saveEffect: 'Half damage',
  },
  {
    name: 'Mirror Image', level: 2, school: 'Illusion',
    castingTime: '1 action', range: 'Self',
    components: ['V', 'S'], materialComponent: '',
    duration: '1 minute', concentration: false, ritual: false,
    description: 'Three illusory duplicates of yourself appear in your space. Until the spell ends, the duplicates move with you and mimic your actions, shifting position so it\'s impossible to track which image is real. You can use your action to dismiss the illusory duplicates. Each time a creature targets you with an attack during the spell\'s duration, roll a d20 to determine whether the attack instead targets one of your duplicates. If you have three duplicates, you must roll a 6 or higher to change the attack\'s target to a duplicate. With two duplicates, you must roll an 8 or higher. With one duplicate, you must roll an 11 or higher. A duplicate\'s AC equals 10 + your Dexterity modifier. If an attack hits a duplicate, the duplicate is destroyed. A duplicate can be destroyed only by an attack that hits it. It ignores all other damage and effects.',
    higherLevels: '',
    classes: ['Sorcerer', 'Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Misty Step', level: 2, school: 'Conjuration',
    castingTime: '1 bonus action', range: 'Self',
    components: ['V'], materialComponent: '',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space that you can see.',
    higherLevels: '',
    classes: ['Sorcerer', 'Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Moonbeam', level: 2, school: 'Evocation',
    castingTime: '1 action', range: '120 feet',
    components: ['V', 'S', 'M'], materialComponent: 'several seeds of any moonseed plant and a piece of opalescent feldspar',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'A silvery beam of pale light shines down in a 5-foot-radius, 40-foot-high cylinder centered on a point within range. Until the spell ends, dim light fills the cylinder. When a creature enters the spell\'s area for the first time on a turn or starts its turn there, it is engulfed in ghostly flames that cause searing pain, and it must make a Constitution saving throw. It takes 2d10 radiant damage on a failed save, or half as much damage on a successful one. A shapechanger makes its saving throw with disadvantage. If it fails, it also instantly reverts to its original form and can\'t assume a different form until it leaves the spell\'s light. On each of your turns after you cast this spell, you can use an action to move the beam up to 60 feet in any direction.',
    higherLevels: 'The damage increases by 1d10 for each slot level above 2nd.',
    classes: ['Druid'],
    attackType: '', damage: '2d10', damageType: 'radiant', scaling: '',
    savingThrow: 'CON', saveEffect: 'Half damage',
  },
  {
    name: 'Nystul\'s Magic Aura', level: 2, school: 'Illusion',
    castingTime: '1 action', range: 'Touch',
    components: ['V', 'S', 'M'], materialComponent: 'a small square of silk',
    duration: '24 hours', concentration: false, ritual: false,
    description: 'You place an illusion on a creature or an object you touch so that divination spells reveal false information about it. The target can be a willing creature or an object that isn\'t being carried or worn by another creature. When you cast the spell, choose one or both of the following effects. The effect lasts for the duration. If you cast this spell on the same creature or object every day for 30 days, placing the same effect on it each time, the illusion lasts until it is dispelled.\n\nFalse Aura. You change the way the target appears to spells and magical effects, such as detect magic, that detect magical auras.\n\nMask. You change the way the target appears to spells and magical effects that detect creature types, such as a paladin\'s Divine Sense or the trigger of a symbol spell.',
    higherLevels: '',
    classes: ['Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Pass without Trace', level: 2, school: 'Abjuration',
    castingTime: '1 action', range: 'Self',
    components: ['V', 'S', 'M'], materialComponent: 'ashes from a burned leaf of mistletoe and a sprig of spruce',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'A veil of shadows and silence radiates from you, masking you and your companions from detection. For the duration, each creature you choose within 30 feet of you (including you) has a +10 bonus to Dexterity (Stealth) checks and can\'t be tracked except by magical means. A creature that receives this bonus leaves behind no tracks or other traces of its passage.',
    higherLevels: '',
    classes: ['Druid', 'Ranger'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Phantasmal Force', level: 2, school: 'Illusion',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a bit of fleece',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You craft an illusion that takes root in the mind of a creature that you can see within range. The target must make an Intelligence saving throw. On a failed save, you create a phantasmal object, creature, or other visible phenomenon of your choice that is no larger than a 10-foot cube and that is perceivable only to the target for the duration. The phantasm includes sound, temperature, and other stimuli, also evident only to the target. The target can use its action to examine the phantasm with an Intelligence (Investigation) check against your spell save DC. If the check succeeds, the target realizes that the phantasm is an illusion, and the spell ends. While a target is affected by the spell, the target treats the phantasm as if it were real. The target rationalizes any illogical outcomes from interacting with the phantasm. An affected target is so convinced of the phantasm\'s reality that it can even take damage from the illusion. Each round on your turn, the phantasm can deal 1d6 psychic damage to the target if it is in the phantasm\'s area or within 5 feet of the phantasm.',
    higherLevels: '',
    classes: ['Bard', 'Sorcerer', 'Wizard'],
    attackType: '', damage: '1d6', damageType: 'psychic', scaling: '',
    savingThrow: 'INT', saveEffect: 'Negates',
  },
  {
    name: 'Prayer of Healing', level: 2, school: 'Evocation',
    castingTime: '10 minutes', range: '30 feet',
    components: ['V'], materialComponent: '',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'Up to six creatures of your choice that you can see within range each regain hit points equal to 2d8 + your spellcasting ability modifier. This spell has no effect on undead or constructs.',
    higherLevels: 'The healing increases by 1d8 for each slot level above 2nd.',
    classes: ['Cleric'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Protection from Poison', level: 2, school: 'Abjuration',
    castingTime: '1 action', range: 'Touch',
    components: ['V', 'S'], materialComponent: '',
    duration: '1 hour', concentration: false, ritual: false,
    description: 'You touch a creature. If it is poisoned, you neutralize the poison. If more than one poison afflicts the target, you neutralize one poison that you know is present, or you neutralize one at random. For the duration, the target has advantage on saving throws against being poisoned, and it has resistance to poison damage.',
    higherLevels: '',
    classes: ['Cleric', 'Druid', 'Paladin', 'Ranger', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Pyrotechnics', level: 2, school: 'Transmutation',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'Choose an area of nonmagical flame that you can see and that fits within a 5-foot cube within range. You can extinguish the fire in that area, and you create either fireworks or smoke.\n\nFireworks. The target explodes with a dazzling display of colors. Each creature within 10 feet of the target must succeed on a Constitution saving throw or become blinded until the end of your next turn.\n\nSmoke. Thick black smoke spreads out from the target in a 20-foot radius, moving around corners. The area of the smoke is heavily obscured. The smoke persists for 1 minute or until a strong wind disperses it.',
    higherLevels: '',
    classes: ['Bard', 'Sorcerer', 'Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'CON', saveEffect: 'Not blinded',
  },
  {
    name: 'Ray of Enfeeblement', level: 2, school: 'Necromancy',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'A black beam of enervating energy springs from your finger toward a creature within range. Make a ranged spell attack against the target. On a hit, the target deals only half damage with weapon attacks that use Strength until the spell ends. At the end of each of the target\'s turns, it can make a Constitution saving throw against the spell. On a success, the spell ends.',
    higherLevels: '',
    classes: ['Warlock', 'Wizard'],
    attackType: 'ranged', damage: '', damageType: 'necrotic', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Rope Trick', level: 2, school: 'Transmutation',
    castingTime: '1 action', range: 'Touch',
    components: ['V', 'S', 'M'], materialComponent: 'powdered corn extract and a twisted loop of parchment',
    duration: '1 hour', concentration: false, ritual: false,
    description: 'You touch a length of rope that is up to 60 feet long. One end of the rope then rises into the air until the whole rope hangs perpendicular to the ground. At the upper end of the rope, an invisible entrance opens to an extradimensional space that lasts until the spell ends. The extradimensional space can be reached by climbing to the top of the rope. The space can hold as many as eight Medium or smaller creatures. The rope can be pulled into the space, making the rope disappear from view outside the space. Attacks and spells can\'t cross through the entrance into or out of the extradimensional space, but those inside can see out of it as if through a 3-foot-by-5-foot window centered on the rope. Anything inside the extradimensional space drops out when the spell ends.',
    higherLevels: '',
    classes: ['Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Scorching Ray', level: 2, school: 'Evocation',
    castingTime: '1 action', range: '120 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You create three rays of fire and hurl them at targets within range. You can hurl them at one target or several. Make a ranged spell attack for each ray. On a hit, the target takes 2d6 fire damage.',
    higherLevels: 'You create one additional ray for each slot level above 2nd.',
    classes: ['Sorcerer', 'Wizard'],
    attackType: 'ranged', damage: '2d6', damageType: 'fire', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'See Invisibility', level: 2, school: 'Divination',
    castingTime: '1 action', range: 'Self',
    components: ['V', 'S', 'M'], materialComponent: 'a pinch of talc and a small sprinkling of powdered silver',
    duration: '1 hour', concentration: false, ritual: false,
    description: 'For the duration, you see invisible creatures and objects as if they were visible, and you can see into the Ethereal Plane. Ethereal creatures and objects appear ghostly and translucent.',
    higherLevels: '',
    classes: ['Bard', 'Sorcerer', 'Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Shadow Blade', level: 2, school: 'Illusion',
    castingTime: '1 bonus action', range: 'Self',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You weave together threads of shadow to create a sword of solidified gloom in your hand. This magic sword lasts until the spell ends. It counts as a simple melee weapon with which you are proficient. It deals 2d8 psychic damage on a hit and has the finesse, light, and thrown properties (range 20/60). In addition, when you use the sword to attack a target that is in dim light or darkness, you make the attack roll with advantage. If you drop the weapon or throw it, it dissipates at the end of the turn. Thereafter, while the spell persists, you can use a bonus action to cause the sword to reappear in your hand.',
    higherLevels: 'The damage increases by 1d8 for every two slot levels above 2nd (3d8 at 3rd-4th, 4d8 at 5th-6th, 5d8 at 7th+).',
    classes: ['Sorcerer', 'Warlock', 'Wizard'],
    attackType: 'melee', damage: '2d8', damageType: 'psychic', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Shatter', level: 2, school: 'Evocation',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a chip of mica',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'A sudden loud ringing noise, painfully intense, erupts from a point of your choice within range. Each creature in a 10-foot-radius sphere centered on that point must make a Constitution saving throw. A creature takes 3d8 thunder damage on a failed save, or half as much damage on a successful one. A creature made of inorganic material such as stone, crystal, or metal has disadvantage on this saving throw. A nonmagical object that isn\'t being worn or carried also takes the damage if it\'s in the spell\'s area.',
    higherLevels: 'The damage increases by 1d8 for each slot level above 2nd.',
    classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    attackType: '', damage: '3d8', damageType: 'thunder', scaling: '',
    savingThrow: 'CON', saveEffect: 'Half damage',
  },
  {
    name: 'Silence', level: 2, school: 'Illusion',
    castingTime: '1 action', range: '120 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: true,
    description: 'For the duration, no sound can be created within or pass through a 20-foot-radius sphere centered on a point you choose within range. Any creature or object entirely inside the sphere is immune to thunder damage, and creatures are deafened while entirely inside it. Casting a spell that includes a verbal component is impossible there.',
    higherLevels: '',
    classes: ['Bard', 'Cleric', 'Ranger'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Skywrite', level: 2, school: 'Transmutation',
    castingTime: '1 action', range: 'Sight',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: true,
    description: 'You cause up to ten words to form in a part of the sky you can see. The words appear to be made of cloud and remain in place for the spell\'s duration. The words dissipate when the spell ends. A strong wind can disperse the clouds and end the spell early.',
    higherLevels: '',
    classes: ['Bard', 'Druid', 'Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Snilloc\'s Snowball Swarm', level: 2, school: 'Evocation',
    castingTime: '1 action', range: '90 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a piece of ice or a small white rock chip',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'A flurry of magic snowballs erupts from a point you choose within range. Each creature in a 5-foot-radius sphere centered on that point must make a Dexterity saving throw. A creature takes 3d6 cold damage on a failed save, or half as much damage on a successful one.',
    higherLevels: 'The damage increases by 1d6 for each slot level above 2nd.',
    classes: ['Sorcerer', 'Wizard'],
    attackType: '', damage: '3d6', damageType: 'cold', scaling: '',
    savingThrow: 'DEX', saveEffect: 'Half damage',
  },
  {
    name: 'Spider Climb', level: 2, school: 'Transmutation',
    castingTime: '1 action', range: 'Touch',
    components: ['V', 'S', 'M'], materialComponent: 'a drop of bitumen and a spider',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'Until the spell ends, one willing creature you touch gains the ability to move up, down, and across vertical surfaces and upside down along ceilings, while leaving its hands free. The target also gains a climbing speed equal to its walking speed.',
    higherLevels: '',
    classes: ['Sorcerer', 'Warlock', 'Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Spike Growth', level: 2, school: 'Transmutation',
    castingTime: '1 action', range: '150 feet',
    components: ['V', 'S', 'M'], materialComponent: 'seven sharp thorns or seven small twigs, each sharpened to a point',
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: false,
    description: 'The ground in a 20-foot radius centered on a point within range twists and sprouts hard spikes and thorns. The area becomes difficult terrain for the duration. When a creature moves into or within the area, it takes 2d4 piercing damage for every 5 feet it travels. The transformation of the ground is camouflaged to look natural. Any creature that can\'t see the area at the time the spell is cast must make a Wisdom (Perception) check against your spell save DC to recognize the terrain as hazardous before entering it.',
    higherLevels: '',
    classes: ['Druid', 'Ranger'],
    attackType: '', damage: '2d4', damageType: 'piercing', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Spiritual Weapon', level: 2, school: 'Evocation',
    castingTime: '1 bonus action', range: '60 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: '1 minute', concentration: false, ritual: false,
    description: 'You create a floating, spectral weapon within range that lasts for the duration or until you cast this spell again. When you cast the spell, you can make a melee spell attack against a creature within 5 feet of the weapon. On a hit, the target takes force damage equal to 1d8 + your spellcasting ability modifier. As a bonus action on your turn, you can move the weapon up to 20 feet and repeat the attack against a creature within 5 feet of it. The weapon can take whatever form you choose. Clerics of deities who are associated with a particular weapon (as St. Cuthbert is known for his mace and Thor for his hammer) make this spell\'s effect resemble that weapon.',
    higherLevels: 'The damage increases by 1d8 for every two slot levels above 2nd.',
    classes: ['Cleric'],
    attackType: 'melee', damage: '1d8', damageType: 'force', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Suggestion', level: 2, school: 'Enchantment',
    castingTime: '1 action', range: '30 feet',
    components: ['V', 'M'], materialComponent: 'a snake\'s tongue and either a bit of honeycomb or a drop of sweet oil',
    duration: 'Concentration, up to 8 hours', concentration: true, ritual: false,
    description: 'You suggest a course of activity (limited to a sentence or two) and magically influence a creature you can see within range that can hear and understand you. Creatures that can\'t be charmed are immune to this effect. The suggestion must be worded in such a manner as to make the course of action sound reasonable. Asking the creature to stab itself, throw itself onto a spear, immolate itself, or do some other obviously harmful act ends the spell. The target must make a Wisdom saving throw. On a failed save, it pursues the course of action you described to the best of its ability. The suggested course of action can continue for the entire duration. If the suggested activity can be completed in a shorter time, the spell ends when the subject finishes what it was asked to do.',
    higherLevels: '',
    classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'WIS', saveEffect: 'Negates',
  },
  {
    name: 'Warding Bond', level: 2, school: 'Abjuration',
    castingTime: '1 action', range: 'Touch',
    components: ['V', 'S', 'M'], materialComponent: 'a pair of platinum rings worth at least 50 gp each, which you and the target must wear for the duration',
    duration: '1 hour', concentration: false, ritual: false,
    description: 'This spell wards a willing creature you touch and creates a mystic connection between you and the target until the spell ends. While the target is within 60 feet of you, it gains a +1 bonus to AC and saving throws, and it has resistance to all damage. Also, each time it takes damage, you take the same amount of damage. The spell ends if you drop to 0 hit points or if you and the target become separated by more than 60 feet. It also ends if the spell is cast again on either of the connected creatures. You can also dismiss the spell as an action.',
    higherLevels: '',
    classes: ['Cleric'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Warding Wind', level: 2, school: 'Evocation',
    castingTime: '1 action', range: 'Self',
    components: ['V'], materialComponent: '',
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: false,
    description: 'A strong wind (20 miles per hour) blows around you in a 10-foot radius and moves with you, remaining centered on you. The wind lasts for the spell\'s duration. The wind has the following effects: it deafens you and other creatures in its area, it extinguishes unprotected flames in its area that are torch-sized or smaller, it hedges out vapor, gas, and fog that can be dispersed by strong wind, the area is difficult terrain for creatures other than you, and the attack rolls of ranged weapon attacks have disadvantage if the attacks pass in or out of the wind.',
    higherLevels: '',
    classes: ['Bard', 'Druid', 'Sorcerer', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Web', level: 2, school: 'Conjuration',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a bit of spiderweb',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'You conjure a mass of thick, sticky webbing at a point of your choice within range. The webs fill a 20-foot cube from that point for the duration. The webs are difficult terrain and lightly obscure their area. If the webs aren\'t anchored between two solid masses (such as walls or trees) or layered across a floor, wall, or ceiling, the conjured web collapses on itself, and the spell ends at the start of your next turn. Webs layered over a flat surface have a depth of 5 feet. Each creature that starts its turn in the webs or that enters them during its turn must make a Dexterity saving throw. On a failed save, the creature is restrained as long as it remains in the webs or until it breaks free. A creature restrained by the webs can use its action to make a Strength check against your spell save DC. If it succeeds, it is no longer restrained. The webs are flammable. Any 5-foot cube of webs exposed to fire burns away in 1 round, dealing 2d4 fire damage to any creature that starts its turn in the fire.',
    higherLevels: '',
    classes: ['Sorcerer', 'Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'DEX', saveEffect: 'Not restrained',
  },
  {
    name: 'Zone of Truth', level: 2, school: 'Enchantment',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: '10 minutes', concentration: false, ritual: false,
    description: 'You create a magical zone that guards against deception in a 15-foot-radius sphere centered on a point of your choice within range. Until the spell ends, a creature that enters the spell\'s area for the first time on a turn or starts its turn there must make a Charisma saving throw. On a failed save, a creature can\'t speak a deliberate lie while in the radius. You know whether each creature succeeds or fails on its saving throw. An affected creature is aware of the spell and can thus avoid answering questions to which it would normally respond with a lie. Such a creature can be evasive in its answers as long as it remains within the boundaries of the truth.',
    higherLevels: '',
    classes: ['Bard', 'Cleric', 'Paladin'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'CHA', saveEffect: 'Can still lie',
  },
];

async function seed() {
  await mongoose.connect(process.env.MONGODB_URI);
  console.log('Connected to MongoDB');

  // Remove existing level 2 spells
  const del = await Spell.deleteMany({ level: 2 });
  console.log(`Removed ${del.deletedCount} existing level 2 spells`);

  await Spell.insertMany(SPELLS);
  console.log(`Seeded ${SPELLS.length} level 2 spells`);

  console.log('Done');
  process.exit(0);
}

seed().catch(err => { console.error(err); process.exit(1); });
