require('dotenv').config();
const mongoose = require('mongoose');
const Spell = require('./models/Spell');

const SPELLS = [
  // LEVEL 1
  {
    name: 'Beast Bond', level: 1, school: 'Divination',
    castingTime: '1 action', range: 'Touch',
    components: ['V', 'S', 'M'], materialComponent: 'a bit of fur wrapped in a cloth',
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: false,
    description: 'You establish a telepathic link with one beast you touch that is friendly to you or charmed by you. The spell fails if the beast\'s Intelligence is 4 or higher. Until the spell ends, the link is active while you and the beast are within line of sight of each other. Through the link, the beast can understand your telepathic messages to it, and it can telepathically communicate simple emotions and concepts back to you. While the link is active, the beast gains advantage on attack rolls against any creature within 5 feet of you that you can see.',
    higherLevels: '',
    classes: ['Druid', 'Ranger'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },

  // LEVEL 2
  {
    name: "Aganazzar's Scorcher", level: 2, school: 'Evocation',
    castingTime: '1 action', range: '30 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a red dragon\'s scale',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'A line of roaring flame 30 feet long and 5 feet wide emanates from you in a direction you choose. Each creature in the line must make a Dexterity saving throw. A creature takes 3d8 fire damage on a failed save, or half as much damage on a successful one.',
    higherLevels: 'The damage increases by 1d8 for each slot level above 2nd.',
    classes: ['Sorcerer', 'Wizard'],
    attackType: '', damage: '3d8', damageType: 'fire', scaling: '',
    savingThrow: 'DEX', saveEffect: 'half damage',
  },
  {
    name: 'Gift of Gab', level: 2, school: 'Enchantment',
    castingTime: '1 reaction, which you take when you speak to another creature', range: 'Self',
    components: ['V', 'S', 'M'], materialComponent: '2 gp, which is consumed',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'When you cast this spell, you skillfully reshape the memories of listeners in your immediate area, so that each creature of your choice within 5 feet of you forgets everything you said within the last 6 seconds. Those creatures then remember that you actually said the words you speak as the verbal component of the spell.',
    higherLevels: '',
    classes: ['Bard', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Healing Spirit', level: 2, school: 'Conjuration',
    castingTime: '1 bonus action', range: '60 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You call forth a nature spirit to soothe the wounded. The intangible spirit appears in a space that is a 5-foot cube you can see within range. The spirit looks like a transparent beast or fey (your choice). Until the spell ends, whenever you or a creature you can see moves into the spirit\'s space for the first time on a turn or starts its turn there, you can cause the spirit to restore 1d6 hit points to that creature (no action required). The spirit can\'t heal constructs or undead. The spirit can heal a number of times equal to 1 + your spellcasting ability modifier (minimum twice). After healing that number of times, the spirit disappears. As a bonus action on your turn, you can move the spirit up to 30 feet to a space you can see.',
    higherLevels: 'The healing increases by 1d6 for each slot level above 2nd.',
    classes: ['Druid', 'Ranger'],
    attackType: '', damage: '1d6', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: "Maximilian's Earthen Grasp", level: 2, school: 'Transmutation',
    castingTime: '1 action', range: '30 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a miniature hand sculpted from clay',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You choose a 5-foot-square unoccupied space on the ground that you can see within range. A Medium hand made from compacted soil rises there and reaches for one creature you can see within 5 feet of it. The target must make a Strength saving throw. On a failed save, the target takes 2d6 bludgeoning damage and is restrained for the spell\'s duration. As an action, you can cause the hand to crush the restrained target, dealing 2d6 bludgeoning damage. To break out, the restrained target can use its action to make a Strength check against your spell save DC. On a success, the target escapes and is no longer restrained. As an action, you can cause the hand to reach for a different creature or to move to a different unoccupied space within range. The hand releases a restrained target if you do either.',
    higherLevels: '',
    classes: ['Sorcerer', 'Wizard'],
    attackType: '', damage: '2d6', damageType: 'bludgeoning', scaling: '',
    savingThrow: 'STR', saveEffect: 'negates',
  },
  {
    name: "Nathair's Mischief", level: 2, school: 'Illusion',
    castingTime: '1 action', range: '60 feet',
    components: ['S', 'M'], materialComponent: 'a piece of crust from an apple pie',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You fill a 20-foot cube you can see within range with fey and draconic magic. Roll a d4 to determine the effect on creatures in the cube when you cast the spell. At the start of each of your turns, you can move the cube up to 10 feet and roll again.\n\n1 — Charmed. Each creature in the cube must succeed on a Wisdom saving throw or become charmed until the start of your next turn.\n2 — Blinding. Each creature in the cube that fails a Constitution saving throw is blinded until the start of your next turn.\n3 — Laughter. Each creature in the cube must succeed on a Wisdom saving throw or fall prone, becoming incapacitated until the start of your next turn from laughing.\n4 — Confusion. Each creature in the cube that fails a Wisdom saving throw can\'t speak and any movement it makes is in a random direction until the start of your next turn.',
    higherLevels: '',
    classes: ['Bard', 'Sorcerer', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'WIS', saveEffect: 'negates',
  },
  {
    name: "Tasha's Mind Whip", level: 2, school: 'Enchantment',
    castingTime: '1 action', range: '90 feet',
    components: ['V'], materialComponent: '',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You psychically lash out at one creature you can see within range. The target must make an Intelligence saving throw. On a failed save, the target takes 3d6 psychic damage, and it can\'t take a reaction until the end of its next turn. Moreover, on its next turn, it must choose whether it gets a move, an action, or a bonus action; it gets only one of the three. On a successful save, the target takes half as much damage and suffers no other effects.',
    higherLevels: 'You can target one additional creature for each slot level above 2nd. The creatures must be within 30 feet of each other when you target them.',
    classes: ['Sorcerer', 'Wizard'],
    attackType: '', damage: '3d6', damageType: 'psychic', scaling: '',
    savingThrow: 'INT', saveEffect: 'half damage',
  },
  {
    name: 'Wither and Bloom', level: 2, school: 'Necromancy',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a withered vine twisted into a loop',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You invoke both decay and life in a 10-foot-radius sphere centered on a point within range. Each creature of your choice in that area must make a Constitution saving throw, taking 2d6 necrotic damage on a failed save, or half as much damage on a successful one. Nonmagical vegetation in that area withers. In addition, one creature of your choice in that area can spend and roll one of its unspent Hit Dice and regain a number of hit points equal to the roll plus your spellcasting ability modifier.',
    higherLevels: 'The damage increases by 1d6 and the number of Hit Dice that can be spent increases by one for each slot level above 2nd.',
    classes: ['Druid', 'Sorcerer', 'Wizard'],
    attackType: '', damage: '2d6', damageType: 'necrotic', scaling: '',
    savingThrow: 'CON', saveEffect: 'half damage',
  },

  // LEVEL 3
  {
    name: 'Conjure Lesser Demons', level: 3, school: 'Conjuration',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a vial of blood from a humanoid killed within the past 24 hours',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'You summon fiends that appear in unoccupied spaces you can see within range. Choose one of the following: You summon 8 demons of CR 1/4 or lower, you summon 4 demons of CR 1/2 or lower, or you summon 2 demons of CR 1 or lower. The DM chooses the demons. The summoned demons disappear when they drop to 0 hit points or when the spell ends. The demons are hostile to all creatures, including you. Roll initiative for the summoned demons as a group. If no creatures are within range for them to perceive, they attack you. A demon can make a Charisma saving throw at the end of each of its turns in an area of magic circle. On a success, the spell ends for that demon.',
    higherLevels: 'You summon twice as many demons with a 6th-level slot and three times as many with an 8th-level slot.',
    classes: ['Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Incite Greed', level: 3, school: 'Enchantment',
    castingTime: '1 action', range: 'Self (30-foot radius)',
    components: ['V', 'S', 'M'], materialComponent: 'a gem worth at least 50 gp',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'When you cast this spell, you present the gem used as the material component and choose any number of creatures within range that can see you. Each target must succeed on a Wisdom saving throw or be charmed by you until the spell ends, or until you or your companions do anything harmful to it. While charmed in this way, a creature can do nothing but use its movement to approach you in a safe manner. While an affected creature is within 5 feet of you, it cannot move but simply stares greedily at the gem you present.',
    higherLevels: '',
    classes: ['Cleric', 'Sorcerer', 'Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'WIS', saveEffect: 'negates',
  },
  {
    name: 'Intellect Fortress', level: 3, school: 'Abjuration',
    castingTime: '1 action', range: '30 feet',
    components: ['V'], materialComponent: '',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'For the duration, you or one willing creature you can see within range has resistance to psychic damage, as well as advantage on Intelligence, Wisdom, and Charisma saving throws.',
    higherLevels: 'You can target one additional creature for each slot level above 3rd.',
    classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Lightning Arrow', level: 3, school: 'Transmutation',
    castingTime: '1 bonus action', range: 'Self',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'The next time you make a ranged weapon attack during the spell\'s duration, the weapon\'s ammunition, or the weapon itself if it\'s a thrown weapon, transforms into a bolt of lightning. Make the attack roll as normal. The target takes 4d8 lightning damage on a hit, or half as much damage on a miss, instead of the weapon\'s normal damage. Whether you hit or miss, each creature within 10 feet of the target must make a Dexterity saving throw. Each of these creatures takes 2d8 lightning damage on a failed save, or half as much damage on a successful one. The piece of ammunition or weapon then returns to its normal form.',
    higherLevels: 'The damage for both effects increases by 1d8 for each slot level above 3rd.',
    classes: ['Ranger'],
    attackType: 'ranged', damage: '4d8', damageType: 'lightning', scaling: '',
    savingThrow: 'DEX', saveEffect: 'half damage (splash)',
  },
  {
    name: 'Pulse Wave', level: 3, school: 'Evocation',
    castingTime: '1 action', range: 'Self (30-foot cone)',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You create intense pressure, unleash it in a 30-foot cone, and decide whether the pressure pushes or pulls creatures and objects in the area. Each creature in the cone must make a Constitution saving throw. A creature takes 6d6 force damage on a failed save, or half as much damage on a successful one. In addition, every creature that fails the save is either pushed 15 feet away from you or pulled 15 feet toward you, depending on the choice you made for the spell.',
    higherLevels: 'The damage increases by 1d6 and the distance pushed or pulled increases by 5 feet for each slot level above 3rd.',
    classes: ['Wizard'],
    attackType: '', damage: '6d6', damageType: 'force', scaling: '',
    savingThrow: 'CON', saveEffect: 'half damage, not moved',
  },
  {
    name: 'Spirit Shroud', level: 3, school: 'Necromancy',
    castingTime: '1 bonus action', range: 'Self',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You call forth spirits of the dead, which flit around you for the spell\'s duration. The spirits are intangible and invulnerable. Until the spell ends, any attack you make deals 1d8 extra damage when you hit a creature within 10 feet of you. This damage is radiant, necrotic, or cold (your choice when you cast the spell). Any creature that takes this damage can\'t regain hit points until the start of your next turn. In addition, any creature of your choice that you can see that starts its turn within 10 feet of you has its speed reduced by 10 feet until the start of your next turn.',
    higherLevels: 'The extra damage increases by 1d8 for every two slot levels above 3rd.',
    classes: ['Cleric', 'Paladin', 'Warlock', 'Wizard'],
    attackType: '', damage: '1d8', damageType: 'radiant', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Summon Fey', level: 3, school: 'Conjuration',
    castingTime: '1 action', range: '90 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a gilded flower worth at least 300 gp',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'You call forth a fey spirit. It manifests in an unoccupied space that you can see within range. This corporeal form uses the Fey Spirit stat block. When you cast the spell, choose a mood: Fuming, Mirthful, or Tricksy. The creature resembles a fey creature of your choice marked by the chosen mood, which determines one of the traits in its stat block. The creature disappears when it drops to 0 hit points or when the spell ends. The creature is an ally to you and your companions. In combat, the creature shares your initiative count, but it takes its turn immediately after yours. It obeys your verbal commands. If you don\'t issue any, it takes the Dodge action and uses its move to avoid danger.',
    higherLevels: 'The creature assumes the higher level for its stat block.',
    classes: ['Druid', 'Ranger', 'Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Summon Shadowspawn', level: 3, school: 'Conjuration',
    castingTime: '1 action', range: '90 feet',
    components: ['V', 'S', 'M'], materialComponent: 'tears inside a gem worth at least 300 gp',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'You call forth a shadowy spirit. It manifests in an unoccupied space that you can see within range. This corporeal form uses the Shadow Spirit stat block. When you cast the spell, choose an emotion: Fury, Despair, or Fear. The creature resembles a misshapen biped marked by the chosen emotion, which determines certain traits in its stat block. The creature disappears when it drops to 0 hit points or when the spell ends. The creature is an ally to you and your companions. In combat, the creature shares your initiative count, but it takes its turn immediately after yours. It obeys your verbal commands. If you don\'t issue any, it takes the Dodge action and uses its move to avoid danger.',
    higherLevels: 'The creature assumes the higher level for its stat block.',
    classes: ['Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Summon Undead', level: 3, school: 'Necromancy',
    castingTime: '1 action', range: '90 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a gilded skull worth at least 300 gp',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'You call forth an undead spirit. It manifests in an unoccupied space that you can see within range. This corporeal form uses the Undead Spirit stat block. When you cast the spell, choose the creature\'s form: Ghostly, Putrid, or Skeletal. The spirit resembles an undead creature with the chosen form, which determines certain traits in its stat block. The creature disappears when it drops to 0 hit points or when the spell ends. The creature is an ally to you and your companions. In combat, the creature shares your initiative count, but it takes its turn immediately after yours. It obeys your verbal commands. If you don\'t issue any, it takes the Dodge action and uses its move to avoid danger.',
    higherLevels: 'The creature assumes the higher level for its stat block.',
    classes: ['Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Tiny Servant', level: 3, school: 'Transmutation',
    castingTime: '1 minute', range: 'Touch',
    components: ['V', 'S'], materialComponent: '',
    duration: '8 hours', concentration: false, ritual: false,
    description: 'You touch one Tiny, nonmagical object that isn\'t attached to another object or a surface and isn\'t being carried by another creature. The target animates and sprouts little arms and legs, becoming a creature under your control until the spell ends or the creature drops to 0 hit points. See the Tiny Servant stat block for its statistics. As a bonus action, you can mentally command the creature if it is within 120 feet of you. You decide what action the creature will take and where it will move during its next turn, or you can issue a simple, general command. If you issue no commands, the servant does nothing other than defend itself.',
    higherLevels: 'You animate two additional objects for each slot level above 3rd.',
    classes: ['Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Wall of Sand', level: 3, school: 'Evocation',
    castingTime: '1 action', range: '90 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a handful of sand',
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: false,
    description: 'You create a wall of swirling sand on the ground at a point you can see within range. You can make the wall up to 30 feet long, 10 feet high, and 10 feet thick. It vanishes when the spell ends. It blocks line of sight but not movement. A creature is blinded while in the wall\'s space and must spend 3 feet of movement for every 1 foot it moves there.',
    higherLevels: '',
    classes: ['Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },

  // LEVEL 4
  {
    name: 'Guardian of Nature', level: 4, school: 'Transmutation',
    castingTime: '1 bonus action', range: 'Self',
    components: ['V'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'A nature spirit answers your call and transforms you into a powerful guardian. The transformation lasts until the spell ends. You choose one of the following forms to assume: Primal Beast or Great Tree.\n\nPrimal Beast. Bestial fur covers your body, your facial features become feral, and you gain the following benefits: Your walking speed increases by 10 feet, you gain darkvision with a range of 120 feet, you make Strength-based attack rolls with advantage, and your melee weapon attacks deal an extra 1d6 force damage on a hit.\n\nGreat Tree. Your skin appears barky, leaves sprout from your hair, and you gain the following benefits: You gain 10 temporary hit points, you make Constitution saving throws with advantage, you make Dexterity- and Wisdom-based attack rolls with advantage, and while you are on the ground, the ground within 15 feet of you is difficult terrain for your enemies.',
    higherLevels: '',
    classes: ['Druid', 'Ranger'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Summon Aberration', level: 4, school: 'Conjuration',
    castingTime: '1 action', range: '90 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a pickled tentacle and an eyeball in a platinum-inlaid vial worth at least 400 gp',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'You call forth an aberrant spirit. It manifests in an unoccupied space that you can see within range. This corporeal form uses the Aberrant Spirit stat block. When you cast the spell, choose Beholderkin, Slaad, or Star Spawn. The creature resembles an aberration of that kind, which determines certain traits in its stat block. The creature disappears when it drops to 0 hit points or when the spell ends. The creature is an ally to you and your companions. In combat, the creature shares your initiative count, but it takes its turn immediately after yours. It obeys your verbal commands. If you don\'t issue any, it takes the Dodge action and uses its move to avoid danger.',
    higherLevels: 'The creature assumes the higher level for its stat block.',
    classes: ['Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Summon Construct', level: 4, school: 'Conjuration',
    castingTime: '1 action', range: '90 feet',
    components: ['V', 'S', 'M'], materialComponent: 'an ornate stone and metal lockbox worth at least 400 gp',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'You call forth the spirit of a construct. It manifests in an unoccupied space that you can see within range. This corporeal form uses the Construct Spirit stat block. When you cast the spell, choose a material: Clay, Metal, or Stone. The creature resembles a golem or automaton made of the chosen material, which determines certain traits in its stat block. The creature disappears when it drops to 0 hit points or when the spell ends. The creature is an ally to you and your companions. In combat, the creature shares your initiative count, but it takes its turn immediately after yours. It obeys your verbal commands. If you don\'t issue any, it takes the Dodge action and uses its move to avoid danger.',
    higherLevels: 'The creature assumes the higher level for its stat block.',
    classes: ['Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Summon Elemental', level: 4, school: 'Conjuration',
    castingTime: '1 action', range: '90 feet',
    components: ['V', 'S', 'M'], materialComponent: 'air, a pebble, ash, and water inside a gold-inlaid vial worth at least 400 gp',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'You call forth an elemental spirit. It manifests in an unoccupied space that you can see within range. This corporeal form uses the Elemental Spirit stat block. When you cast the spell, choose an element: Air, Earth, Fire, or Water. The creature resembles a bipedal form wreathed in the chosen element, which determines certain traits in its stat block. The creature disappears when it drops to 0 hit points or when the spell ends. The creature is an ally to you and your companions. In combat, the creature shares your initiative count, but it takes its turn immediately after yours. It obeys your verbal commands. If you don\'t issue any, it takes the Dodge action and uses its move to avoid danger.',
    higherLevels: 'The creature assumes the higher level for its stat block.',
    classes: ['Druid', 'Ranger', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Vitriolic Sphere', level: 4, school: 'Evocation',
    castingTime: '1 action', range: '150 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a drop of giant slug bile',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You point at a location within range, and a glowing 1-foot-diameter ball of emerald acid streaks there and explodes in a 20-foot-radius sphere. Each creature in that area must make a Dexterity saving throw. On a failed save, a creature takes 10d4 acid damage and 5d4 acid damage at the end of its next turn. On a successful save, a creature takes half the initial damage and no damage at the end of its next turn.',
    higherLevels: 'The initial damage increases by 2d4 for each slot level above 4th.',
    classes: ['Sorcerer', 'Wizard'],
    attackType: '', damage: '10d4', damageType: 'acid', scaling: '',
    savingThrow: 'DEX', saveEffect: 'half initial, no ongoing',
  },
];

(async () => {
  await mongoose.connect(process.env.MONGODB_URI);
  for (const sp of SPELLS) await Spell.findOneAndUpdate({ name: sp.name, level: sp.level }, sp, { upsert: true });
  console.log(`Seeded ${SPELLS.length} missing spells`);
  process.exit(0);
})();
