require('dotenv').config();
const mongoose = require('mongoose');
const Spell = require('./models/Spell');

const SPELLS = [
  {
    name: 'Absorb Elements', level: 1, school: 'Abjuration',
    castingTime: '1 reaction', range: 'Self',
    components: ['S'], materialComponent: '',
    duration: '1 round', concentration: false, ritual: false,
    description: 'The spell captures some of the incoming energy, lessening its effect on you and storing it for your next melee attack. You have resistance to the triggering damage type until the start of your next turn. Also, the first time you hit with a melee attack on your next turn, the target takes an extra 1d6 damage of the triggering type, and the spell ends.',
    higherLevels: 'The extra damage increases by 1d6 for each slot level above 1st.',
    classes: ['Druid', 'Ranger', 'Sorcerer', 'Wizard', 'Artificer'],
    attackType: '', damage: '1d6', damageType: 'varies', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Alarm', level: 1, school: 'Abjuration',
    castingTime: '1 minute', range: '30 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a tiny bell and a piece of fine silver wire',
    duration: '8 hours', concentration: false, ritual: true,
    description: 'You set an alarm against unwanted intrusion. Choose a door, a window, or an area within range that is no larger than a 20-foot cube. Until the spell ends, an alarm alerts you whenever a Tiny or larger creature touches or enters the warded area. When you cast the spell, you can designate creatures that won\'t set off the alarm. You also choose whether the alarm is mental or audible. A mental alarm alerts you with a ping in your mind if you are within 1 mile of the warded area. This ping awakens you if you are sleeping. An audible alarm produces the sound of a hand bell for 10 seconds within 60 feet.',
    higherLevels: '',
    classes: ['Ranger', 'Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Animal Friendship', level: 1, school: 'Enchantment',
    castingTime: '1 action', range: '30 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a morsel of food',
    duration: '24 hours', concentration: false, ritual: false,
    description: 'This spell lets you convince a beast that you mean it no harm. Choose a beast that you can see within range. It must see and hear you. If the beast\'s Intelligence is 4 or higher, the spell fails. Otherwise, the beast must succeed on a Wisdom saving throw or be charmed by you for the spell\'s duration. If you or one of your companions harms the target, the spell ends.',
    higherLevels: 'You can target one additional beast for each slot level above 1st.',
    classes: ['Bard', 'Druid', 'Ranger'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'WIS', saveEffect: 'Not charmed on success',
  },
  {
    name: 'Armor of Agathys', level: 1, school: 'Abjuration',
    castingTime: '1 action', range: 'Self',
    components: ['V', 'S', 'M'], materialComponent: 'a cup of water',
    duration: '1 hour', concentration: false, ritual: false,
    description: 'A protective magical force surrounds you, manifesting as a spectral frost that covers you and your gear. You gain 5 temporary hit points for the duration. If a creature hits you with a melee attack while you have these hit points, the creature takes 5 cold damage.',
    higherLevels: 'Both the temporary hit points and the cold damage increase by 5 for each slot level above 1st.',
    classes: ['Warlock'],
    attackType: '', damage: '', damageType: 'cold', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Arms of Hadar', level: 1, school: 'Conjuration',
    castingTime: '1 action', range: 'Self (10-foot radius)',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You invoke the power of Hadar, the Dark Hunger. Tendrils of dark energy erupt from you and batter all creatures within 10 feet of you. Each creature in that area must make a Strength saving throw. On a failed save, a target takes 2d6 necrotic damage and can\'t take reactions until its next turn. On a successful save, the creature takes half damage, and suffers no other effect.',
    higherLevels: 'The damage increases by 1d6 for each slot level above 1st.',
    classes: ['Warlock'],
    attackType: '', damage: '2d6', damageType: 'necrotic', scaling: '',
    savingThrow: 'STR', saveEffect: 'Half damage on success',
  },
  {
    name: 'Bane', level: 1, school: 'Enchantment',
    castingTime: '1 action', range: '30 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a drop of blood',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'Up to three creatures of your choice that you can see within range must make Charisma saving throws. Whenever a target that fails this saving throw makes an attack roll or a saving throw before the spell ends, the target must roll a d4 and subtract the number rolled from the attack roll or saving throw.',
    higherLevels: 'You can target one additional creature for each slot level above 1st.',
    classes: ['Bard', 'Cleric'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'CHA', saveEffect: 'No effect on success',
  },
  {
    name: 'Bless', level: 1, school: 'Enchantment',
    castingTime: '1 action', range: '30 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a sprinkling of holy water',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You bless up to three creatures of your choice within range. Whenever a target makes an attack roll or a saving throw before the spell ends, the target can roll a d4 and add the number rolled to the attack roll or saving throw.',
    higherLevels: 'You can target one additional creature for each slot level above 1st.',
    classes: ['Cleric', 'Paladin'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Burning Hands', level: 1, school: 'Evocation',
    castingTime: '1 action', range: 'Self (15-foot cone)',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'As you hold your hands with thumbs touching and fingers spread, a thin sheet of flames shoots forth from your outstretched fingertips. Each creature in a 15-foot cone must make a Dexterity saving throw. A creature takes 3d6 fire damage on a failed save, or half as much damage on a successful one. The fire ignites any flammable objects in the area that aren\'t being worn or carried.',
    higherLevels: 'The damage increases by 1d6 for each slot level above 1st.',
    classes: ['Sorcerer', 'Wizard'],
    attackType: '', damage: '3d6', damageType: 'fire', scaling: '',
    savingThrow: 'DEX', saveEffect: 'Half damage on success',
  },
  {
    name: 'Catapult', level: 1, school: 'Transmutation',
    castingTime: '1 action', range: '60 feet',
    components: ['S'], materialComponent: '',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'Choose one object weighing 1 to 5 pounds within range that isn\'t being worn or carried. The object flies in a straight line up to 90 feet in a direction you choose before falling to the ground, stopping early if it impacts against a solid surface. If the object would strike a creature, that creature must make a Dexterity saving throw. On a failed save, the object strikes the target and stops moving. When the object strikes something, the object and what it strikes each take 3d8 bludgeoning damage.',
    higherLevels: 'The maximum weight of objects increases by 5 pounds, and the damage increases by 1d8, for each slot level above 1st.',
    classes: ['Sorcerer', 'Wizard', 'Artificer'],
    attackType: '', damage: '3d8', damageType: 'bludgeoning', scaling: '',
    savingThrow: 'DEX', saveEffect: 'Object misses on success',
  },
  {
    name: 'Cause Fear', level: 1, school: 'Necromancy',
    castingTime: '1 action', range: '60 feet',
    components: ['V'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You awaken the sense of mortality in one creature you can see within range. A construct or an undead is immune to this effect. The target must succeed on a Wisdom saving throw or become frightened of you until the spell ends. The frightened target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.',
    higherLevels: 'You can target one additional creature for each slot level above 1st.',
    classes: ['Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'WIS', saveEffect: 'Not frightened on success',
  },
  {
    name: 'Charm Person', level: 1, school: 'Enchantment',
    castingTime: '1 action', range: '30 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: '1 hour', concentration: false, ritual: false,
    description: 'You attempt to charm a humanoid you can see within range. It must make a Wisdom saving throw, and does so with advantage if you or your companions are fighting it. If it fails the saving throw, it is charmed by you until the spell ends or until you or your companions do anything harmful to it. The charmed creature regards you as a friendly acquaintance. When the spell ends, the creature knows it was charmed by you.',
    higherLevels: 'You can target one additional creature for each slot level above 1st.',
    classes: ['Bard', 'Druid', 'Sorcerer', 'Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'WIS', saveEffect: 'Not charmed on success',
  },
  {
    name: 'Chromatic Orb', level: 1, school: 'Evocation',
    castingTime: '1 action', range: '90 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a diamond worth at least 50 gp',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You hurl a 4-inch-diameter sphere of energy at a creature that you can see within range. You choose acid, cold, fire, lightning, poison, or thunder for the type of orb you create, and then make a ranged spell attack against the target. If the attack hits, the creature takes 3d8 damage of the type you chose.',
    higherLevels: 'The damage increases by 1d8 for each slot level above 1st.',
    classes: ['Sorcerer', 'Wizard'],
    attackType: 'ranged', damage: '3d8', damageType: 'varies', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Color Spray', level: 1, school: 'Illusion',
    castingTime: '1 action', range: 'Self (15-foot cone)',
    components: ['V', 'S', 'M'], materialComponent: 'a pinch of powder or sand colored red, yellow, and blue',
    duration: '1 round', concentration: false, ritual: false,
    description: 'A dazzling array of flashing, colored light springs from your hand. Roll 6d10; the total is how many hit points of creatures this spell can affect. Creatures in a 15-foot cone originating from you are affected in ascending order of their current hit points (ignoring unconscious creatures and creatures that can\'t see). Starting with the creature that has the lowest current hit points, each creature affected by this spell is blinded until the end of your next turn.',
    higherLevels: 'Roll an additional 2d10 for each slot level above 1st.',
    classes: ['Sorcerer', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Command', level: 1, school: 'Enchantment',
    castingTime: '1 action', range: '60 feet',
    components: ['V'], materialComponent: '',
    duration: '1 round', concentration: false, ritual: false,
    description: 'You speak a one-word command to a creature you can see within range. The target must succeed on a Wisdom saving throw or follow the command on its next turn. The spell has no effect if the target is undead, if it doesn\'t understand your language, or if your command is directly harmful to it. Some typical commands and their effects follow: Approach, Drop, Flee, Grovel, Halt.',
    higherLevels: 'You can affect one additional creature for each slot level above 1st.',
    classes: ['Cleric', 'Paladin'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'WIS', saveEffect: 'No effect on success',
  },
  {
    name: 'Compelled Duel', level: 1, school: 'Enchantment',
    castingTime: '1 bonus action', range: '30 feet',
    components: ['V'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You attempt to compel a creature into a duel. One creature that you can see within range must make a Wisdom saving throw. On a failed save, the creature is drawn to you, compelled by your divine demand. For the duration, it has disadvantage on attack rolls against creatures other than you, and must make a Wisdom saving throw each time it attempts to move to a space that is more than 30 feet away from you.',
    higherLevels: '',
    classes: ['Paladin'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'WIS', saveEffect: 'No effect on success',
  },
  {
    name: 'Comprehend Languages', level: 1, school: 'Divination',
    castingTime: '1 action', range: 'Self',
    components: ['V', 'S', 'M'], materialComponent: 'a pinch of soot and salt',
    duration: '1 hour', concentration: false, ritual: true,
    description: 'For the duration, you understand the literal meaning of any spoken language that you hear. You also understand any written language that you see, but you must be touching the surface on which the words are written. It takes about 1 minute to read one page of text. This spell doesn\'t decode secret messages in a text or a glyph, such as an arcane sigil, that isn\'t part of a written language.',
    higherLevels: '',
    classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Create or Destroy Water', level: 1, school: 'Transmutation',
    castingTime: '1 action', range: '30 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a drop of water if creating, or a few grains of sand if destroying',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You either create or destroy water. Create Water: You create up to 10 gallons of clean water within range in an open container. Alternatively, the water falls as rain in a 30-foot cube within range, extinguishing exposed flames in the area. Destroy Water: You destroy up to 10 gallons of water in an open container within range. Alternatively, you destroy fog in a 30-foot cube within range.',
    higherLevels: 'You create or destroy 10 additional gallons of water, or the size of the cube increases by 5 feet, for each slot level above 1st.',
    classes: ['Cleric', 'Druid'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Cure Wounds', level: 1, school: 'Evocation',
    castingTime: '1 action', range: 'Touch',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'A creature you touch regains a number of hit points equal to 1d8 + your spellcasting ability modifier. This spell has no effect on undead or constructs.',
    higherLevels: 'The healing increases by 1d8 for each slot level above 1st.',
    classes: ['Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Detect Evil and Good', level: 1, school: 'Divination',
    castingTime: '1 action', range: 'Self',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: false,
    description: 'For the duration, you know if there is an aberration, celestial, elemental, fey, fiend, or undead within 30 feet of you, as well as where the creature is located. Similarly, you know if there is a place or object within 30 feet of you that has been magically consecrated or desecrated. The spell can penetrate most barriers, but it is blocked by 1 foot of stone, 1 inch of common metal, a thin sheet of lead, or 3 feet of wood or dirt.',
    higherLevels: '',
    classes: ['Cleric', 'Paladin'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Detect Magic', level: 1, school: 'Divination',
    castingTime: '1 action', range: 'Self',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: true,
    description: 'For the duration, you sense the presence of magic within 30 feet of you. If you sense magic in this way, you can use your action to see a faint aura around any visible creature or object in the area that bears magic, and you learn its school of magic, if any. The spell can penetrate most barriers, but it is blocked by 1 foot of stone, 1 inch of common metal, a thin sheet of lead, or 3 feet of wood or dirt.',
    higherLevels: '',
    classes: ['Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger', 'Sorcerer', 'Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Detect Poison and Disease', level: 1, school: 'Divination',
    castingTime: '1 action', range: 'Self',
    components: ['V', 'S', 'M'], materialComponent: 'a yew leaf',
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: true,
    description: 'For the duration, you can sense the presence and location of poisons, poisonous creatures, and diseases within 30 feet of you. You also identify the kind of poison, poisonous creature, or disease in each case. The spell can penetrate most barriers, but it is blocked by 1 foot of stone, 1 inch of common metal, a thin sheet of lead, or 3 feet of wood or dirt.',
    higherLevels: '',
    classes: ['Cleric', 'Druid', 'Paladin', 'Ranger'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Disguise Self', level: 1, school: 'Illusion',
    castingTime: '1 action', range: 'Self',
    components: ['V', 'S'], materialComponent: '',
    duration: '1 hour', concentration: false, ritual: false,
    description: 'You make yourself — including your clothing, armor, weapons, and other belongings on your person — look different until the spell ends or until you use your action to dismiss it. You can seem 1 foot shorter or taller and can appear thin, fat, or in between. You can\'t change your body type, so you must adopt a form that has the same basic arrangement of limbs. Otherwise, the extent of the illusion is up to you. To discern that you are disguised, a creature can use its action to inspect your appearance and must succeed on an Intelligence (Investigation) check against your spell save DC.',
    higherLevels: '',
    classes: ['Bard', 'Sorcerer', 'Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Dissonant Whispers', level: 1, school: 'Enchantment',
    castingTime: '1 action', range: '60 feet',
    components: ['V'], materialComponent: '',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You whisper a discordant melody that only one creature of your choice within range can hear, wracking it with terrible pain. The target must make a Wisdom saving throw. On a failed save, it takes 3d6 psychic damage and must immediately use its reaction, if available, to move as far as its speed allows away from you. The creature doesn\'t move into obviously dangerous ground, such as a fire or a pit. On a successful save, the target takes half as much damage and doesn\'t have to move away.',
    higherLevels: 'The damage increases by 1d6 for each slot level above 1st.',
    classes: ['Bard'],
    attackType: '', damage: '3d6', damageType: 'psychic', scaling: '',
    savingThrow: 'WIS', saveEffect: 'Half damage on success',
  },
  {
    name: 'Divine Favor', level: 1, school: 'Evocation',
    castingTime: '1 bonus action', range: 'Self',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'Your prayer empowers you with divine radiance. Until the spell ends, your weapon attacks deal an extra 1d4 radiant damage on a hit.',
    higherLevels: '',
    classes: ['Paladin'],
    attackType: '', damage: '1d4', damageType: 'radiant', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Earth Tremor', level: 1, school: 'Evocation',
    castingTime: '1 action', range: 'Self (10-foot radius)',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You cause a tremor in the ground within 10 feet of you. Each creature other than you in that area must make a Dexterity saving throw. On a failed save, a creature takes 1d6 bludgeoning damage and is knocked prone. If the ground in that area is loose earth or stone, it becomes difficult terrain until cleared, with each 5-foot-square portion requiring at least 1 minute to clear by hand.',
    higherLevels: 'The damage increases by 1d6 for each slot level above 1st.',
    classes: ['Bard', 'Druid', 'Sorcerer', 'Wizard'],
    attackType: '', damage: '1d6', damageType: 'bludgeoning', scaling: '',
    savingThrow: 'DEX', saveEffect: 'No damage or prone on success',
  },
  {
    name: 'Ensnaring Strike', level: 1, school: 'Conjuration',
    castingTime: '1 bonus action', range: 'Self',
    components: ['V'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'The next time you hit a creature with a weapon attack before this spell ends, a writhing mass of thorny vines appears at the point of impact, and the target must succeed on a Strength saving throw or be restrained by the magical vines until the spell ends. A Large or larger creature has advantage on this saving throw. If the target succeeds on the save, the vines shrivel away. While restrained by this spell, the target takes 1d6 piercing damage at the start of each of its turns.',
    higherLevels: 'The damage increases by 1d6 for each slot level above 1st.',
    classes: ['Ranger'],
    attackType: '', damage: '1d6', damageType: 'piercing', scaling: '',
    savingThrow: 'STR', saveEffect: 'Not restrained on success',
  },
  {
    name: 'Entangle', level: 1, school: 'Conjuration',
    castingTime: '1 action', range: '90 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'Grasping weeds and vines sprout from the ground in a 20-foot square starting from a point within range. For the duration, these plants turn the ground in the area into difficult terrain. A creature in the area when you cast the spell must succeed on a Strength saving throw or be restrained by the entangling plants until the spell ends. A creature restrained by the plants can use its action to make a Strength check against your spell save DC. On a success, it frees itself.',
    higherLevels: '',
    classes: ['Druid'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'STR', saveEffect: 'Not restrained on success',
  },
  {
    name: 'Expeditious Retreat', level: 1, school: 'Transmutation',
    castingTime: '1 bonus action', range: 'Self',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: false,
    description: 'This spell allows you to move at an incredible pace. When you cast this spell, and then as a bonus action on each of your turns until the spell ends, you can take the Dash action.',
    higherLevels: '',
    classes: ['Sorcerer', 'Warlock', 'Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Faerie Fire', level: 1, school: 'Evocation',
    castingTime: '1 action', range: '60 feet',
    components: ['V'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'Each object in a 20-foot cube within range is outlined in blue, green, or violet light (your choice). Any creature in the area when the spell is cast is also outlined in light if it fails a Dexterity saving throw. For the duration, objects and affected creatures shed dim light in a 10-foot radius. Any attack roll against an affected creature or object has advantage if the attacker can see it, and the affected creature or object can\'t benefit from being invisible.',
    higherLevels: '',
    classes: ['Bard', 'Druid'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'DEX', saveEffect: 'Not outlined on success',
  },
  {
    name: 'False Life', level: 1, school: 'Necromancy',
    castingTime: '1 action', range: 'Self',
    components: ['V', 'S', 'M'], materialComponent: 'a small amount of alcohol or distilled spirits',
    duration: '1 hour', concentration: false, ritual: false,
    description: 'Bolstering yourself with a necromantic facsimile of life, you gain 1d4 + 4 temporary hit points for the duration.',
    higherLevels: 'You gain 5 additional temporary hit points for each slot level above 1st.',
    classes: ['Sorcerer', 'Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Feather Fall', level: 1, school: 'Transmutation',
    castingTime: '1 reaction', range: '60 feet',
    components: ['V', 'M'], materialComponent: 'a small feather or piece of down',
    duration: '1 minute', concentration: false, ritual: false,
    description: 'Choose up to five falling creatures within range. A falling creature\'s rate of descent slows to 60 feet per round until the spell ends. If the creature lands before the spell ends, it takes no falling damage and can land on its feet, and the spell ends for that creature.',
    higherLevels: '',
    classes: ['Bard', 'Sorcerer', 'Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Find Familiar', level: 1, school: 'Conjuration',
    castingTime: '1 hour', range: '10 feet',
    components: ['V', 'S', 'M'], materialComponent: '10 gp worth of charcoal, incense, and herbs consumed in a brass brazier',
    duration: 'Instantaneous', concentration: false, ritual: true,
    description: 'You gain the service of a familiar, a spirit that takes an animal form you choose: bat, cat, crab, frog (toad), hawk, lizard, octopus, owl, poisonous snake, fish (quipper), rat, raven, sea horse, spider, or weasel. Appearing in an unoccupied space within range, the familiar has the statistics of the chosen form, though it is a celestial, fey, or fiend (your choice) instead of a beast. Your familiar acts independently of you, but it always obeys your commands.',
    higherLevels: '',
    classes: ['Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Fog Cloud', level: 1, school: 'Conjuration',
    castingTime: '1 action', range: '120 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'You create a 20-foot-radius sphere of fog centered on a point within range. The sphere spreads around corners, and its area is heavily obscured. It lasts for the duration or until a wind of moderate or greater speed (at least 10 miles per hour) disperses it.',
    higherLevels: 'The radius of the fog increases by 20 feet for each slot level above 1st.',
    classes: ['Druid', 'Ranger', 'Sorcerer', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Goodberry', level: 1, school: 'Transmutation',
    castingTime: '1 action', range: 'Touch',
    components: ['V', 'S', 'M'], materialComponent: 'a sprig of mistletoe',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'Up to ten berries appear in your hand and are infused with magic for the duration. A creature can use its action to eat one berry. Eating a berry restores 1 hit point, and the berry provides enough nourishment to sustain a creature for one day. The berries lose their potency if they have not been consumed within 24 hours of the casting of this spell.',
    higherLevels: '',
    classes: ['Druid', 'Ranger'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Grease', level: 1, school: 'Conjuration',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a bit of pork rind or butter',
    duration: '1 minute', concentration: false, ritual: false,
    description: 'Slick grease covers the ground in a 10-foot square centered on a point within range and turns it into difficult terrain for the duration. When the grease appears, each creature standing in its area must succeed on a Dexterity saving throw or fall prone. A creature that enters the area or ends its turn there must also succeed on a Dexterity saving throw or fall prone.',
    higherLevels: '',
    classes: ['Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'DEX', saveEffect: 'Not prone on success',
  },
  {
    name: 'Guiding Bolt', level: 1, school: 'Evocation',
    castingTime: '1 action', range: '120 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: '1 round', concentration: false, ritual: false,
    description: 'A flash of light streaks toward a creature of your choice within range. Make a ranged spell attack against the target. On a hit, the target takes 4d6 radiant damage, and the next attack roll made against this target before the end of your next turn has advantage, thanks to the mystical dim light glittering on the target until then.',
    higherLevels: 'The damage increases by 1d6 for each slot level above 1st.',
    classes: ['Cleric'],
    attackType: 'ranged', damage: '4d6', damageType: 'radiant', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Hail of Thorns', level: 1, school: 'Conjuration',
    castingTime: '1 bonus action', range: 'Self',
    components: ['V'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'The next time you hit a creature with a ranged weapon attack before the spell ends, this spell creates a rain of thorns that sprouts from your ranged weapon or ammunition. In addition to the normal effect of the attack, the target of the attack and each creature within 5 feet of it must make a Dexterity saving throw. A creature takes 1d10 piercing damage on a failed save, or half as much damage on a successful one.',
    higherLevels: 'The damage increases by 1d10 for each slot level above 1st.',
    classes: ['Ranger'],
    attackType: '', damage: '1d10', damageType: 'piercing', scaling: '',
    savingThrow: 'DEX', saveEffect: 'Half damage on success',
  },
  {
    name: 'Healing Word', level: 1, school: 'Evocation',
    castingTime: '1 bonus action', range: '60 feet',
    components: ['V'], materialComponent: '',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'A creature of your choice that you can see within range regains hit points equal to 1d4 + your spellcasting ability modifier. This spell has no effect on undead or constructs.',
    higherLevels: 'The healing increases by 1d4 for each slot level above 1st.',
    classes: ['Bard', 'Cleric', 'Druid'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Hellish Rebuke', level: 1, school: 'Evocation',
    castingTime: '1 reaction', range: '60 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You point your finger, and the creature that damaged you is momentarily surrounded by hellish flames. The creature must make a Dexterity saving throw. It takes 2d10 fire damage on a failed save, or half as much damage on a successful one.',
    higherLevels: 'The damage increases by 1d10 for each slot level above 1st.',
    classes: ['Warlock'],
    attackType: '', damage: '2d10', damageType: 'fire', scaling: '',
    savingThrow: 'DEX', saveEffect: 'Half damage on success',
  },
  {
    name: 'Heroism', level: 1, school: 'Enchantment',
    castingTime: '1 action', range: 'Touch',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'A willing creature you touch is imbued with bravery. Until the spell ends, the creature is immune to being frightened and gains temporary hit points equal to your spellcasting ability modifier at the start of each of its turns. When the spell ends, the target loses any remaining temporary hit points from this spell.',
    higherLevels: 'You can target one additional creature for each slot level above 1st.',
    classes: ['Bard', 'Paladin'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Hex', level: 1, school: 'Enchantment',
    castingTime: '1 bonus action', range: '90 feet',
    components: ['V', 'S', 'M'], materialComponent: 'the petrified eye of a newt',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'You place a curse on a creature that you can see within range. Until the spell ends, you deal an extra 1d6 necrotic damage to the target whenever you hit it with an attack. Also, choose one ability when you cast the spell. The target has disadvantage on ability checks made with the chosen ability. If the target drops to 0 hit points before this spell ends, you can use a bonus action on a subsequent turn to curse a new creature.',
    higherLevels: 'At 3rd or 4th level slot, concentration lasts up to 8 hours. At 5th level slot or higher, concentration lasts up to 24 hours.',
    classes: ['Warlock'],
    attackType: '', damage: '1d6', damageType: 'necrotic', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Hunter\'s Mark', level: 1, school: 'Divination',
    castingTime: '1 bonus action', range: '90 feet',
    components: ['V'], materialComponent: '',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'You choose a creature you can see within range and mystically mark it as your quarry. Until the spell ends, you deal an extra 1d6 damage to the target whenever you hit it with a weapon attack, and you have advantage on any Wisdom (Perception) or Wisdom (Survival) check you make to find it. If the target drops to 0 hit points before this spell ends, you can use a bonus action on a subsequent turn of yours to mark a new creature.',
    higherLevels: 'At 3rd or 4th level slot, concentration lasts up to 8 hours. At 5th level slot or higher, concentration lasts up to 24 hours.',
    classes: ['Ranger'],
    attackType: '', damage: '1d6', damageType: 'varies', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Ice Knife', level: 1, school: 'Conjuration',
    castingTime: '1 action', range: '60 feet',
    components: ['S', 'M'], materialComponent: 'a drop of water or piece of ice',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You create a shard of ice and fling it at one creature within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 piercing damage. Hit or miss, the shard then explodes. The target and each creature within 5 feet of it must succeed on a Dexterity saving throw or take 2d6 cold damage.',
    higherLevels: 'The cold damage increases by 1d6 for each slot level above 1st.',
    classes: ['Druid', 'Sorcerer', 'Wizard'],
    attackType: 'ranged', damage: '1d10', damageType: 'piercing', scaling: '',
    savingThrow: 'DEX', saveEffect: 'No cold explosion damage on success',
  },
  {
    name: 'Identify', level: 1, school: 'Divination',
    castingTime: '1 minute', range: 'Touch',
    components: ['V', 'S', 'M'], materialComponent: 'a pearl worth at least 100 gp and an owl feather',
    duration: 'Instantaneous', concentration: false, ritual: true,
    description: 'You choose one object that you must touch throughout the casting of the spell. If it is a magic item or some other magic-imbued object, you learn its properties and how to use them, whether it requires attunement to use, and how many charges it has, if any. You learn whether any spells are affecting the item and what they are. If the item was created by a spell, you learn which spell created it.',
    higherLevels: '',
    classes: ['Bard', 'Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Illusory Script', level: 1, school: 'Illusion',
    castingTime: '1 minute', range: 'Touch',
    components: ['S', 'M'], materialComponent: 'a lead-based ink worth at least 10 gp, which the spell consumes',
    duration: '10 days', concentration: false, ritual: true,
    description: 'You write on parchment, paper, or some other suitable writing material and imbue it with a potent illusion that lasts for the duration. To you and any creatures you designate when you cast the spell, the writing appears normal, written in your hand, and conveys whatever meaning you intended when you wrote the text. To all others, the writing appears as if it were written in an unknown or magical script that is unintelligible. Alternatively, you can cause the writing to appear to be an entirely different message, written in a different hand and language, though the language must be one you know.',
    higherLevels: '',
    classes: ['Bard', 'Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Inflict Wounds', level: 1, school: 'Necromancy',
    castingTime: '1 action', range: 'Touch',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'Make a melee spell attack against a creature you can reach. On a hit, the target takes 3d10 necrotic damage.',
    higherLevels: 'The damage increases by 1d10 for each slot level above 1st.',
    classes: ['Cleric'],
    attackType: 'melee', damage: '3d10', damageType: 'necrotic', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Jump', level: 1, school: 'Transmutation',
    castingTime: '1 action', range: 'Touch',
    components: ['V', 'S', 'M'], materialComponent: 'a grasshopper\'s hind leg',
    duration: '1 minute', concentration: false, ritual: false,
    description: 'You touch a creature. The creature\'s jump distance is tripled until the spell ends.',
    higherLevels: '',
    classes: ['Druid', 'Ranger', 'Sorcerer', 'Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Longstrider', level: 1, school: 'Transmutation',
    castingTime: '1 action', range: 'Touch',
    components: ['V', 'S', 'M'], materialComponent: 'a pinch of dirt',
    duration: '1 hour', concentration: false, ritual: false,
    description: 'You touch a creature. The target\'s speed increases by 10 feet until the spell ends.',
    higherLevels: 'You can target one additional creature for each slot level above 1st.',
    classes: ['Bard', 'Druid', 'Ranger', 'Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Mage Armor', level: 1, school: 'Abjuration',
    castingTime: '1 action', range: 'Touch',
    components: ['V', 'S', 'M'], materialComponent: 'a piece of cured leather',
    duration: '8 hours', concentration: false, ritual: false,
    description: 'You touch a willing creature who isn\'t wearing armor, and a protective magical force surrounds it until the spell ends. The target\'s base AC becomes 13 + its Dexterity modifier. The spell ends if the target dons armor or if you dismiss the spell as an action.',
    higherLevels: '',
    classes: ['Sorcerer', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Magic Missile', level: 1, school: 'Evocation',
    castingTime: '1 action', range: '120 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You create three glowing darts of magical force. Each dart hits a creature of your choice that you can see within range. A dart deals 1d4 + 1 force damage to its target. The darts all strike simultaneously, and you can direct them to hit one creature or several.',
    higherLevels: 'The spell creates one more dart for each slot level above 1st.',
    classes: ['Sorcerer', 'Wizard'],
    attackType: '', damage: '3d4', damageType: 'force', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Protection from Evil and Good', level: 1, school: 'Abjuration',
    castingTime: '1 action', range: 'Touch',
    components: ['V', 'S', 'M'], materialComponent: 'holy water or powdered silver and iron, which the spell consumes',
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: false,
    description: 'Until the spell ends, one willing creature you touch is protected against certain types of creatures: aberrations, celestials, elementals, fey, fiends, and undead. The protection grants several benefits. Creatures of those types have disadvantage on attack rolls against the target. The target also can\'t be charmed, frightened, or possessed by them. If the target is already charmed, frightened, or possessed by such a creature, the target has advantage on any new saving throw against the relevant effect.',
    higherLevels: '',
    classes: ['Cleric', 'Paladin', 'Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Purify Food and Drink', level: 1, school: 'Transmutation',
    castingTime: '1 action', range: '10 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Instantaneous', concentration: false, ritual: true,
    description: 'All nonmagical food and drink within a 5-foot-radius sphere centered on a point of your choice within range is purified and rendered free of poison and disease.',
    higherLevels: '',
    classes: ['Cleric', 'Druid', 'Paladin', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Ray of Sickness', level: 1, school: 'Necromancy',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'A ray of sickening greenish energy lashes out toward a creature within range. Make a ranged spell attack against the target. On a hit, the target takes 2d8 poison damage and must make a Constitution saving throw. On a failed save, it is also poisoned until the end of your next turn.',
    higherLevels: 'The damage increases by 1d8 for each slot level above 1st.',
    classes: ['Sorcerer', 'Wizard'],
    attackType: 'ranged', damage: '2d8', damageType: 'poison', scaling: '',
    savingThrow: 'CON', saveEffect: 'Not poisoned on success',
  },
  {
    name: 'Sanctuary', level: 1, school: 'Abjuration',
    castingTime: '1 bonus action', range: '30 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a small silver mirror',
    duration: '1 minute', concentration: false, ritual: false,
    description: 'You ward a creature within range against attack. Until the spell ends, any creature who targets the warded creature with an attack or a harmful spell must first make a Wisdom saving throw. On a failed save, the creature must choose a new target or lose the attack or spell. This spell doesn\'t protect the warded creature from area effects, such as the explosion of a fireball. If the warded creature makes an attack, casts a spell that affects an enemy, or deals damage to another creature, this spell ends.',
    higherLevels: '',
    classes: ['Cleric', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'WIS', saveEffect: 'Can attack target normally',
  },
  {
    name: 'Searing Smite', level: 1, school: 'Evocation',
    castingTime: '1 bonus action', range: 'Self',
    components: ['V'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'The next time you hit a creature with a melee weapon attack during the spell\'s duration, your weapon flares with white-hot intensity, and the attack deals an extra 1d6 fire damage to the target and causes the target to ignite in flames. At the start of each of its turns until the spell ends, the target must make a Constitution saving throw. On a failed save, it takes 1d6 fire damage. On a successful save, the spell ends. If the target or a creature within 5 feet of it uses an action to put out the flames, or if some other effect douses the flames, the spell ends.',
    higherLevels: 'The initial extra damage dealt by the attack increases by 1d6 for each slot level above 1st.',
    classes: ['Paladin'],
    attackType: '', damage: '1d6', damageType: 'fire', scaling: '',
    savingThrow: 'CON', saveEffect: 'Fire ends on success',
  },
  {
    name: 'Shield', level: 1, school: 'Abjuration',
    castingTime: '1 reaction', range: 'Self',
    components: ['V', 'S'], materialComponent: '',
    duration: '1 round', concentration: false, ritual: false,
    description: 'An invisible barrier of magical force appears and protects you. Until the start of your next turn, you have a +5 bonus to AC, including against the triggering attack, and you take no damage from magic missile.',
    higherLevels: '',
    classes: ['Sorcerer', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Shield of Faith', level: 1, school: 'Abjuration',
    castingTime: '1 bonus action', range: '60 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a small parchment with a bit of holy text written on it',
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: false,
    description: 'A shimmering field appears and surrounds a creature of your choice within range, granting it a +2 bonus to AC for the duration.',
    higherLevels: '',
    classes: ['Cleric', 'Paladin'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Silent Image', level: 1, school: 'Illusion',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a bit of fleece',
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: false,
    description: 'You create the image of an object, a creature, or some other visible phenomenon that is no larger than a 15-foot cube. The image appears at a spot within range and lasts for the duration. The image is purely visual; it isn\'t accompanied by sound, smell, or other sensory effects. You can use your action to cause the image to move to any spot within range. As the image changes location, you can alter its appearance so that its movements appear natural for the image. Physical interaction with the image reveals it to be an illusion, because things can pass through it.',
    higherLevels: '',
    classes: ['Bard', 'Sorcerer', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Sleep', level: 1, school: 'Enchantment',
    castingTime: '1 action', range: '90 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a pinch of fine sand, rose petals, or a cricket',
    duration: '1 minute', concentration: false, ritual: false,
    description: 'This spell sends creatures into a magical slumber. Roll 5d8; the total is how many hit points of creatures this spell can affect. Creatures within 20 feet of a point you choose within range are affected in ascending order of their current hit points (ignoring unconscious creatures). Starting with the creature that has the lowest current hit points, each creature affected by this spell falls unconscious until the spell ends, the sleeper takes damage, or someone uses an action to shake or slap the sleeper awake. Undead and creatures immune to being charmed aren\'t affected by this spell.',
    higherLevels: 'Roll an additional 2d8 for each slot level above 1st.',
    classes: ['Bard', 'Sorcerer', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Snare', level: 1, school: 'Abjuration',
    castingTime: '1 minute', range: 'Touch',
    components: ['S', 'M'], materialComponent: '25 feet of rope, which the spell consumes',
    duration: '8 hours', concentration: false, ritual: false,
    description: 'As you cast this spell, you use the rope to create a circle with a 5-foot radius on the ground or the floor. When you finish casting, the rope disappears and the circle becomes a magic trap. The trap is nearly invisible and requires a successful Intelligence (Investigation) check against your spell save DC to be discerned. The trap triggers when a Small, Medium, or Large creature moves onto the ground or the floor in the spell\'s radius. That creature must succeed on a Dexterity saving throw or be magically hoisted into the air, leaving it hanging upside down 3 feet above the ground or the floor. The creature is restrained there until the spell ends.',
    higherLevels: '',
    classes: ['Druid', 'Ranger', 'Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'DEX', saveEffect: 'Not restrained on success',
  },
  {
    name: 'Speak with Animals', level: 1, school: 'Divination',
    castingTime: '1 action', range: 'Self',
    components: ['V', 'S'], materialComponent: '',
    duration: '10 minutes', concentration: false, ritual: true,
    description: 'You gain the ability to comprehend and verbally communicate with beasts for the duration. The knowledge and awareness of many beasts is limited by their intelligence, but at minimum, beasts can give you information about nearby locations and monsters, including whatever they can perceive or have perceived within the past day. You might be able to persuade a beast to perform a small favor for you, at the DM\'s discretion.',
    higherLevels: '',
    classes: ['Bard', 'Druid', 'Ranger'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Tasha\'s Caustic Brew', level: 1, school: 'Evocation',
    castingTime: '1 action', range: 'Self (30-foot line)',
    components: ['V', 'S', 'M'], materialComponent: 'a bit of rotten food',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'A stream of acid emanates from you in a line 30 feet long and 5 feet wide in a direction you choose. Each creature in the line must succeed on a Dexterity saving throw or be covered in acid for the spell\'s duration or until a creature uses its action to scrape or wash the acid off itself or another creature. A creature covered in the acid takes 2d4 acid damage at start of each of its turns.',
    higherLevels: 'The damage increases by 2d4 for each slot level above 1st.',
    classes: ['Sorcerer', 'Wizard', 'Artificer'],
    attackType: '', damage: '2d4', damageType: 'acid', scaling: '',
    savingThrow: 'DEX', saveEffect: 'Not covered on success',
  },
  {
    name: 'Tasha\'s Hideous Laughter', level: 1, school: 'Enchantment',
    castingTime: '1 action', range: '30 feet',
    components: ['V', 'S', 'M'], materialComponent: 'tiny tarts and a feather that is waved in the air',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'A creature of your choice that you can see within range perceives everything as hilariously funny and falls into fits of laughter if this spell affects it. The target must succeed on a Wisdom saving throw or fall prone, becoming incapacitated and unable to stand up for the duration. A creature with an Intelligence score of 4 or less isn\'t affected. At the end of each of its turns, and each time it takes damage, the target can make another Wisdom saving throw. The target has advantage on the saving throw if it\'s triggered by damage. On a success, the spell ends.',
    higherLevels: '',
    classes: ['Bard', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'WIS', saveEffect: 'No effect on success',
  },
  {
    name: 'Tenser\'s Floating Disk', level: 1, school: 'Conjuration',
    castingTime: '1 action', range: '30 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a drop of mercury',
    duration: '1 hour', concentration: false, ritual: true,
    description: 'This spell creates a circular, horizontal plane of force, 3 feet in diameter and 1 inch thick, that floats 3 feet above the ground in an unoccupied space of your choice that you can see within range. The disk remains for the duration, and can hold up to 500 pounds. If more weight is placed on it, the spell ends, and everything on the disk falls to the ground.',
    higherLevels: '',
    classes: ['Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Thunderwave', level: 1, school: 'Evocation',
    castingTime: '1 action', range: 'Self (15-foot cube)',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'A wave of thunderous force sweeps out from you. Each creature in a 15-foot cube originating from you must make a Constitution saving throw. On a failed save, a creature takes 2d8 thunder damage and is pushed 10 feet away from you. On a successful save, the creature takes half as much damage and isn\'t pushed. In addition, unsecured objects that are completely within the area of effect are automatically pushed 10 feet away from you by the spell\'s effect, and the spell emits a thunderous boom audible out to 300 feet.',
    higherLevels: 'The damage increases by 1d8 for each slot level above 1st.',
    classes: ['Bard', 'Druid', 'Sorcerer', 'Wizard'],
    attackType: '', damage: '2d8', damageType: 'thunder', scaling: '',
    savingThrow: 'CON', saveEffect: 'Half damage, not pushed on success',
  },
  {
    name: 'Unseen Servant', level: 1, school: 'Conjuration',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a piece of string and a bit of wood',
    duration: '1 hour', concentration: false, ritual: true,
    description: 'This spell creates an invisible, mindless, shapeless, Medium force that performs simple tasks at your command until the spell ends. The servant springs into existence in an unoccupied space on the ground within range. It has AC 10, 1 hit point, and a Strength of 2, and it can\'t attack. If it drops to 0 hit points, the spell ends. Once on each of your turns as a bonus action, you can mentally command the servant to move up to 15 feet and interact with an object.',
    higherLevels: '',
    classes: ['Bard', 'Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Witch Bolt', level: 1, school: 'Evocation',
    castingTime: '1 action', range: '30 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a twig from a tree that has been struck by lightning',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'A beam of crackling, blue energy lances out toward a creature within range, forming a sustained arc of lightning between you and the target. Make a ranged spell attack against that creature. On a hit, the target takes 1d12 lightning damage, and on each of your turns for the duration, you can use your action to deal 1d12 lightning damage to the target automatically. The spell ends if you use your action to do anything else. The spell also ends if the target is ever outside the spell\'s range or if it has total cover from you.',
    higherLevels: 'The initial damage increases by 1d12 for each slot level above 1st.',
    classes: ['Sorcerer', 'Warlock', 'Wizard'],
    attackType: 'ranged', damage: '1d12', damageType: 'lightning', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Wrathful Smite', level: 1, school: 'Evocation',
    castingTime: '1 bonus action', range: 'Self',
    components: ['V'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'The next time you hit with a melee weapon attack during this spell\'s duration, your attack deals an extra 1d6 psychic damage. Additionally, if the target is a creature, it must make a Wisdom saving throw or be frightened of you until the spell ends. As an action, the creature can make a Wisdom check against your spell save DC to steel its resolve and end this spell.',
    higherLevels: '',
    classes: ['Paladin'],
    attackType: '', damage: '1d6', damageType: 'psychic', scaling: '',
    savingThrow: 'WIS', saveEffect: 'Not frightened on success',
  },
  {
    name: 'Zephyr Strike', level: 1, school: 'Transmutation',
    castingTime: '1 bonus action', range: 'Self',
    components: ['V'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You move like the wind. Until the spell ends, your movement doesn\'t provoke opportunity attacks. Once before the spell ends, you can give yourself advantage on one weapon attack roll on your turn. That attack deals an extra 1d8 force damage on a hit. Whether you hit or miss, your walking speed increases by 30 feet until the end of that turn.',
    higherLevels: '',
    classes: ['Ranger'],
    attackType: '', damage: '1d8', damageType: 'force', scaling: '',
    savingThrow: '', saveEffect: '',
  },
];

async function seed() {
  await mongoose.connect(process.env.MONGODB_URI);
  console.log('Connected to MongoDB');

  const deleted = await Spell.deleteMany({ level: 1 });
  console.log(`Removed ${deleted.deletedCount} existing level 1 spells`);

  const inserted = await Spell.insertMany(SPELLS);
  console.log(`Seeded ${inserted.length} level 1 spells`);

  await mongoose.disconnect();
  console.log('Done');
}

seed().catch(err => { console.error(err); process.exit(1); });
