require('dotenv').config();
const mongoose = require('mongoose');
const Spell = require('./models/Spell');

const SPELLS = [
  {
    name: 'Animate Objects', level: 5, school: 'Transmutation',
    castingTime: '1 action', range: '120 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'Objects come to life at your command. Choose up to ten nonmagical objects within range that are not being worn or carried. Medium targets count as two objects, Large targets count as four objects, Huge targets count as eight objects. You can\'t animate any object larger than Huge. Each target animates and becomes a creature under your control until the spell ends or until reduced to 0 hit points.\n\nAs a bonus action, you can mentally command any creature you made with this spell if the creature is within 500 feet of you. You decide what action the creature will take and where it will move during its next turn, or you can issue a general command. If you issue no commands, the creature only defends itself. The creature continues to follow the last command.\n\nTiny: HP 20, AC 18, Atk +8/1d4+4, Str 4, Dex 18\nSmall: HP 25, AC 16, Atk +6/1d8+2, Str 6, Dex 14\nMedium: HP 40, AC 13, Atk +5/2d6+1, Str 10, Dex 12\nLarge: HP 50, AC 10, Atk +6/2d10+2, Str 14, Dex 10\nHuge: HP 80, AC 10, Atk +8/2d12+4, Str 18, Dex 6',
    higherLevels: 'You animate two additional objects for each slot level above 5th.',
    classes: ['Bard', 'Sorcerer', 'Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Antilife Shell', level: 5, school: 'Abjuration',
    castingTime: '1 action', range: 'Self (10-foot radius)',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'A shimmering barrier extends out from you in a 10-foot radius and moves with you, remaining centered on you and hedging out creatures other than undead and constructs. The barrier lasts for the duration. The barrier prevents an affected creature from passing or reaching through. An affected creature can cast spells or make attacks with ranged or reach weapons through the barrier. If you move so that an affected creature is forced to pass through the barrier, the spell ends.',
    higherLevels: '',
    classes: ['Druid'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Awaken', level: 5, school: 'Transmutation',
    castingTime: '8 hours', range: 'Touch',
    components: ['V', 'S', 'M'], materialComponent: 'an agate worth at least 1,000 gp, which the spell consumes',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'After spending the casting time tracing magical pathways within a precious gemstone, you touch a Huge or smaller beast or plant. The target must have either no Intelligence score or an Intelligence of 3 or less. The target gains an Intelligence of 10. The target also gains the ability to speak one language you know. If the target is a plant, it gains the ability to move its limbs, roots, vines, creepers, and so forth, and it gains senses similar to a human\'s. Your DM chooses statistics appropriate for the awakened plant.\n\nThe awakened beast or plant is charmed by you for 30 days or until you or your companions do anything harmful to it. When the charmed condition ends, the awakened creature chooses whether to remain friendly to you, based on how you treated it while it was charmed.',
    higherLevels: '',
    classes: ['Bard', 'Druid'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Banishing Smite', level: 5, school: 'Abjuration',
    castingTime: '1 bonus action', range: 'Self',
    components: ['V'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'The next time you hit a creature with a weapon attack before this spell ends, your weapon crackles with force, and the attack deals an extra 5d10 force damage to the target. Additionally, if this attack reduces the target to 50 hit points or fewer, you banish it. If the target is native to a different plane of existence than the one you\'re on, the target disappears, returning to its home plane. If the target is native to the plane you\'re on, the creature vanishes into a harmless demiplane. While there, the target is incapacitated. It remains there until the spell ends, at which point the target reappears in the space it left or in the nearest unoccupied space if that space is occupied.',
    higherLevels: '',
    classes: ['Paladin'],
    attackType: '', damage: '5d10', damageType: 'force', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: "Bigby's Hand", level: 5, school: 'Evocation',
    castingTime: '1 action', range: '120 feet',
    components: ['V', 'S', 'M'], materialComponent: 'an eggshell and a snakeskin glove',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You create a Large hand of shimmering, translucent force in an unoccupied space that you can see within range. The hand lasts for the spell\'s duration, and it moves at your command, mimicking the movements of your own hand.\n\nThe hand is an object that has AC 20 and hit points equal to your hit point maximum. If it drops to 0 hit points, the spell ends. It has a Strength of 26 (+8) and a Dexterity of 10 (+0). The hand doesn\'t fill its space.\n\nWhen you cast the spell and as a bonus action on your subsequent turns, you can move the hand up to 60 feet and then cause one of the following effects:\n\nClenched Fist. The hand strikes one creature or object within 5 feet of it. Make a melee spell attack. On a hit, the target takes 4d8 force damage.\n\nForceful Hand. The hand attempts to push a creature within 5 feet of it in a direction you choose. The target must make a Strength saving throw. On a failed save, the target is pushed up to 5 feet plus a number of feet equal to five times your spellcasting ability modifier. The hand moves with the target to remain within 5 feet of it.\n\nGrasping Hand. The hand attempts to grapple a Huge or smaller creature within 5 feet of it. The target must succeed on a Dexterity saving throw or be grappled (escape DC equal to your spell save DC). While grappled, you can use a bonus action to crush the target, dealing 2d6 + your spellcasting ability modifier bludgeoning damage.\n\nInterposing Hand. The hand interposes itself between you and a creature you choose until you give the hand a different command. The hand moves to stay between you and the target, providing you with half cover.',
    higherLevels: 'The damage of the clenched fist option increases by 2d8 and the damage of the grasping hand increases by 2d6 for each slot level above 5th.',
    classes: ['Wizard', 'Artificer'],
    attackType: 'melee', damage: '4d8', damageType: 'force', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Circle of Power', level: 5, school: 'Abjuration',
    castingTime: '1 action', range: 'Self (30-foot radius)',
    components: ['V'], materialComponent: '',
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: false,
    description: 'Divine energy radiates from you, distorting and diffusing magical energy within a 30-foot radius. Until the spell ends, the sphere moves with you, centered on you. Each friendly creature in the sphere (including you) has advantage on saving throws against spells and other magical effects. Additionally, when an affected creature succeeds on a saving throw made against a spell or magical effect that allows it to make a saving throw to take only half damage, it instead takes no damage.',
    higherLevels: '',
    classes: ['Paladin'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Cloudkill', level: 5, school: 'Conjuration',
    castingTime: '1 action', range: '120 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: false,
    description: 'You create a 20-foot-radius sphere of poisonous, yellow-green fog centered on a point you choose within range. The fog spreads around corners. It lasts for the duration or until strong wind disperses the fog, ending the spell. Its area is heavily obscured.\n\nWhen a creature enters the spell\'s area for the first time on a turn or starts its turn there, that creature must make a Constitution saving throw. The creature takes 5d8 poison damage on a failed save, or half as much damage on a successful one. Creatures are affected even if they hold their breath or don\'t need to breathe.\n\nThe fog moves 10 feet away from you at the start of each of your turns, rolling along the surface of the ground. The vapors, being heavier than air, sink to the lowest level of the land, even pouring down openings.',
    higherLevels: 'The damage increases by 1d8 for each slot level above 5th.',
    classes: ['Sorcerer', 'Wizard'],
    attackType: '', damage: '5d8', damageType: 'poison', scaling: '',
    savingThrow: 'CON', saveEffect: 'half damage',
  },
  {
    name: 'Cone of Cold', level: 5, school: 'Evocation',
    castingTime: '1 action', range: 'Self (60-foot cone)',
    components: ['V', 'S', 'M'], materialComponent: 'a small crystal or glass cone',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'A blast of cold air erupts from your hands. Each creature in a 60-foot cone must make a Constitution saving throw. A creature takes 8d8 cold damage on a failed save, or half as much damage on a successful one. A creature reduced to 0 hit points by this spell becomes a frozen statue until it thaws.',
    higherLevels: 'The damage increases by 1d8 for each slot level above 5th.',
    classes: ['Sorcerer', 'Wizard'],
    attackType: '', damage: '8d8', damageType: 'cold', scaling: '',
    savingThrow: 'CON', saveEffect: 'half damage',
  },
  {
    name: 'Conjure Elemental', level: 5, school: 'Conjuration',
    castingTime: '1 minute', range: '90 feet',
    components: ['V', 'S', 'M'], materialComponent: 'burning incense for air, soft clay for earth, sulfur and phosphorus for fire, or water and sand for water',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'You call forth an elemental servant. Choose an area of air, earth, fire, or water that fills a 10-foot cube within range. An elemental of challenge rating 5 or lower appropriate to the area you chose appears in an unoccupied space within 10 feet of it.\n\nThe elemental is friendly to you and your companions for the duration. It obeys any verbal commands that you issue to it (no action required by you). If you don\'t issue any commands, the elemental defends itself from hostile creatures but otherwise takes no actions.\n\nIf your concentration is broken, the elemental doesn\'t disappear. Instead, you lose control of the elemental, it becomes hostile toward you and your companions, and it might attack. It can\'t be dismissed by you, and it disappears 1 hour after you summoned it.',
    higherLevels: 'The challenge rating increases by 1 for each slot level above 5th.',
    classes: ['Druid', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Conjure Volley', level: 5, school: 'Conjuration',
    castingTime: '1 action', range: '150 feet',
    components: ['V', 'S', 'M'], materialComponent: 'one piece of ammunition or one thrown weapon',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You fire a piece of nonmagical ammunition from a ranged weapon or throw a nonmagical weapon into the air and choose a point within range. Hundreds of duplicates of the ammunition or weapon fall in a volley from above and then disappear. Each creature in a 40-foot-radius, 20-foot-high cylinder centered on that point must make a Dexterity saving throw. A creature takes 8d8 damage on a failed save, or half as much damage on a successful one. The damage type is the same as that of the ammunition or weapon.',
    higherLevels: '',
    classes: ['Ranger'],
    attackType: '', damage: '8d8', damageType: '', scaling: '',
    savingThrow: 'DEX', saveEffect: 'half damage',
  },
  {
    name: 'Contact Other Plane', level: 5, school: 'Divination',
    castingTime: '1 minute', range: 'Self',
    components: ['V'], materialComponent: '',
    duration: 'Instantaneous', concentration: false, ritual: true,
    description: 'You mentally contact a demigod, the spirit of a long-dead sage, or some other mysterious entity from another plane. Contacting this extraplanar intelligence can strain or even break your mind. When you cast this spell, make a DC 15 Intelligence saving throw. On a failure, you take 6d6 psychic damage and are insane until you finish a long rest. While insane, you can\'t take actions, can\'t understand what other creatures say, can\'t read, and speak only in gibberish. A greater restoration spell cast on you ends this effect.\n\nOn a successful save, you can ask the entity up to five questions. You must ask your questions before the spell ends. The DM answers each question with one word, such as "yes," "no," "maybe," "never," "irrelevant," or "unclear." If a one-word answer would be misleading, the DM might instead offer a short phrase as an answer.',
    higherLevels: '',
    classes: ['Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Control Winds', level: 5, school: 'Transmutation',
    castingTime: '1 action', range: '300 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'You take control of the air in a 100-foot cube that you can see within range. Choose one of the following effects when you cast the spell. The effect lasts for the spell\'s duration, unless you use your action to switch to a different effect. You can also use your action to temporarily halt the effect or to restart one you\'ve halted.\n\nGusts. A wind picks up within the cube, continually blowing in a horizontal direction you designate. You choose the intensity of the wind: calm, moderate, or strong. If the wind is moderate or strong, ranged weapon attacks that pass through it or that are made against targets within the cube have disadvantage on their attack rolls. If the wind is strong, any creature moving against the wind must spend 1 extra foot of movement for each foot moved.\n\nDowndraft. You cause a sustained blast of strong wind to blow downward from the top of the cube. Ranged weapon attacks that pass through the cube or that are made against targets within it have disadvantage on their attack rolls. A creature must make a Strength saving throw if it flies into the cube for the first time on a turn or starts its turn there flying. On a failed save, the creature is knocked prone.\n\nUpdraft. You cause a sustained updraft within the cube, rising upward from the cube\'s bottom edge. Creatures that end a fall within the cube take only half normal falling damage. When a creature in the cube makes a vertical jump, the creature can jump up to 10 feet higher than normal.',
    higherLevels: '',
    classes: ['Druid', 'Sorcerer', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'STR', saveEffect: 'no knockdown',
  },
  {
    name: 'Creation', level: 5, school: 'Illusion',
    castingTime: '1 minute', range: '30 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a tiny piece of matter of the same type of the item you plan to create',
    duration: 'Special', concentration: false, ritual: false,
    description: 'You pull wisps of shadow material from the Shadowfell to create a nonliving object of vegetable matter within range: soft goods, rope, wood, or something similar. You can also use this spell to create mineral objects such as stone, crystal, or metal. The object created must be no larger than a 5-foot cube, and the object must be of a form and material that you have seen before.\n\nThe duration depends on the object\'s material. If the object is composed of multiple materials, use the shortest duration.\n\nVegetable matter: 1 day\nStone or crystal: 12 hours\nPrecious metals: 1 hour\nGems: 10 minutes\nAdamantine or mithral: 1 minute',
    higherLevels: 'The cube increases by 5 feet for each slot level above 5th.',
    classes: ['Sorcerer', 'Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Dawn', level: 5, school: 'Evocation',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a sunburst pendant worth at least 100 gp',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'The light of dawn shines down on a location you specify within range. Until the spell ends, a 30-foot-radius, 40-foot-high cylinder of bright light glimmers there. This light is sunlight.\n\nWhen the cylinder appears, each creature in it must make a Constitution saving throw, taking 4d10 radiant damage on a failed save, or half as much damage on a successful one. A creature must also make this saving throw whenever it ends its turn in the cylinder.\n\nIf you\'re within 60 feet of the cylinder, you can move it up to 60 feet as a bonus action on your turn.',
    higherLevels: '',
    classes: ['Cleric', 'Wizard'],
    attackType: '', damage: '4d10', damageType: 'radiant', scaling: '',
    savingThrow: 'CON', saveEffect: 'half damage',
  },
  {
    name: 'Destructive Wave', level: 5, school: 'Evocation',
    castingTime: '1 action', range: 'Self (30-foot radius)',
    components: ['V'], materialComponent: '',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You strike the ground, creating a burst of divine energy that ripples outward from you. Each creature you choose within 30 feet of you must succeed on a Constitution saving throw or take 5d6 thunder damage, as well as 5d6 radiant or necrotic damage (your choice), and be knocked prone. A creature that succeeds on its saving throw takes half as much damage and isn\'t knocked prone.',
    higherLevels: '',
    classes: ['Paladin'],
    attackType: '', damage: '5d6', damageType: 'thunder', scaling: '',
    savingThrow: 'CON', saveEffect: 'half damage, not prone',
  },
  {
    name: 'Dispel Evil and Good', level: 5, school: 'Abjuration',
    castingTime: '1 action', range: 'Self',
    components: ['V', 'S', 'M'], materialComponent: 'holy water or powdered silver and iron',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'Shimmering energy surrounds and protects you from fey, undead, and creatures originating from beyond the Material Plane. For the duration, celestials, elementals, fey, fiends, and undead have disadvantage on attack rolls against you.\n\nYou can end the spell early by using either of the following special functions.\n\nBreak Enchantment. As your action, you touch a creature you can reach that is charmed, frightened, or possessed by a celestial, an elemental, a fey, a fiend, or an undead. The creature you touch is no longer charmed, frightened, or possessed by such creatures.\n\nDismissal. As your action, make a melee spell attack against a celestial, an elemental, a fey, a fiend, or an undead you can reach. On a hit, you attempt to drive the creature back to its home plane. The creature must succeed on a Charisma saving throw or be sent back to its home plane (if it isn\'t there already).',
    higherLevels: '',
    classes: ['Cleric', 'Paladin'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'CHA', saveEffect: 'not banished',
  },
  {
    name: 'Dream', level: 5, school: 'Illusion',
    castingTime: '1 minute', range: 'Special',
    components: ['V', 'S', 'M'], materialComponent: 'a handful of sand, a dab of ink, and a writing quill plucked from a sleeping bird',
    duration: '8 hours', concentration: false, ritual: false,
    description: 'This spell shapes a creature\'s dreams. Choose a creature known to you as the target of this spell. The target must be on the same plane of existence as you. Creatures that don\'t sleep, such as elves, can\'t be contacted by this spell. You, or a willing creature you touch, enters a trance state, acting as a messenger. While in the trance, the messenger is aware of their surroundings but can\'t take actions or move.\n\nIf the target is asleep, the messenger appears in the target\'s dreams and can converse with the target as long as it remains asleep, through the duration of the spell. The messenger can also shape the environment of the dream, creating landscapes, objects, and other images. The messenger can emerge from the trance at any time, ending the effect of the spell early. The target recalls the dream perfectly upon waking.\n\nIf the target is awake when you cast the spell, the messenger knows it, and can either end the trance (and the spell) or wait for the target to fall asleep, at which point the messenger appears in the target\'s dreams.',
    higherLevels: '',
    classes: ['Bard', 'Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Far Step', level: 5, school: 'Conjuration',
    castingTime: '1 bonus action', range: 'Self',
    components: ['V'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You teleport up to 60 feet to an unoccupied space you can see. On each of your turns before the spell ends, you can use a bonus action to teleport in this way again.',
    higherLevels: '',
    classes: ['Sorcerer', 'Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Flame Strike', level: 5, school: 'Evocation',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'S', 'M'], materialComponent: 'pinch of sulfur',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'A vertical column of divine fire roars down from the heavens in a location you specify. Each creature in a 10-foot-radius, 40-foot-high cylinder centered on a point within range must make a Dexterity saving throw. A creature takes 4d6 fire damage and 4d6 radiant damage on a failed save, or half as much damage on a successful one.',
    higherLevels: 'The fire damage or the radiant damage (your choice) increases by 1d6 for each slot level above 5th.',
    classes: ['Cleric'],
    attackType: '', damage: '4d6', damageType: 'fire', scaling: '',
    savingThrow: 'DEX', saveEffect: 'half damage',
  },
  {
    name: 'Greater Restoration', level: 5, school: 'Abjuration',
    castingTime: '1 action', range: 'Touch',
    components: ['V', 'S', 'M'], materialComponent: 'diamond dust worth at least 100 gp, which the spell consumes',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You imbue a creature you touch with positive energy to undo a debilitating effect. You can reduce the target\'s exhaustion level by one, or end one of the following effects on the target:\n\n- One effect that charmed or petrified the target\n- One curse, including the target\'s attunement to a cursed magic item\n- Any reduction to one of the target\'s ability scores\n- One effect reducing the target\'s hit point maximum',
    higherLevels: '',
    classes: ['Bard', 'Cleric', 'Druid', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Hold Monster', level: 5, school: 'Enchantment',
    castingTime: '1 action', range: '90 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a small, straight piece of iron',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'Choose a creature that you can see within range. The target must succeed on a Wisdom saving throw or be paralyzed for the duration. This spell has no effect on undead. At the end of each of its turns, the target can make another Wisdom saving throw. On a success, the spell ends on the target.',
    higherLevels: 'You can target one additional creature for each slot level above 5th. The creatures must be within 30 feet of each other when you target them.',
    classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'WIS', saveEffect: 'negates',
  },
  {
    name: 'Holy Weapon', level: 5, school: 'Evocation',
    castingTime: '1 bonus action', range: 'Touch',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'You imbue a weapon you touch with holy power. Until the spell ends, the weapon emits bright light in a 30-foot radius and dim light for an additional 30 feet. In addition, weapon attacks made with it deal an extra 2d8 radiant damage on a hit. If the weapon isn\'t already a magic weapon, it becomes one for the duration.\n\nAs a bonus action on your turn, you can dismiss this spell and cause the weapon to emit a burst of radiance. Each creature of your choice that you can see within 30 feet of the weapon must make a Constitution saving throw. On a failed save, a creature takes 4d8 radiant damage, and it is blinded for 1 minute. On a successful save, a creature takes half as much damage and isn\'t blinded. At the end of each of its turns, a blinded creature can make a Constitution saving throw, ending the effect on itself on a success.',
    higherLevels: '',
    classes: ['Cleric', 'Paladin'],
    attackType: '', damage: '2d8', damageType: 'radiant', scaling: '',
    savingThrow: 'CON', saveEffect: 'half damage, not blinded',
  },
  {
    name: 'Insect Plague', level: 5, school: 'Conjuration',
    castingTime: '1 action', range: '300 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a few grains of sugar, some kernels of grain, and a smear of fat',
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: false,
    description: 'Swarming, biting locusts fill a 20-foot-radius sphere centered on a point you choose within range. The sphere spreads around corners. The sphere remains for the duration, and its area is lightly obscured. The sphere\'s area is difficult terrain.\n\nWhen the area appears, each creature in it must make a Constitution saving throw. A creature takes 4d10 piercing damage on a failed save, or half as much damage on a successful one. A creature must also make this saving throw when it enters the spell\'s area for the first time on a turn or ends its turn there.',
    higherLevels: 'The damage increases by 1d10 for each slot level above 5th.',
    classes: ['Cleric', 'Druid', 'Sorcerer'],
    attackType: '', damage: '4d10', damageType: 'piercing', scaling: '',
    savingThrow: 'CON', saveEffect: 'half damage',
  },
  {
    name: 'Legend Lore', level: 5, school: 'Divination',
    castingTime: '10 minutes', range: 'Self',
    components: ['V', 'S', 'M'], materialComponent: 'incense worth at least 250 gp, which the spell consumes, and four ivory strips worth at least 50 gp each',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'Name or describe a person, place, or object. The spell brings to your mind a brief summary of the significant lore about the thing you named. The lore might consist of current tales, forgotten stories, or even secret lore that has never been widely known. If the thing you named isn\'t of legendary importance, you gain no information. The more information you already have about the thing, the more precise and detailed the information you receive is.',
    higherLevels: '',
    classes: ['Bard', 'Cleric', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Maelstrom', level: 5, school: 'Evocation',
    castingTime: '1 action', range: '120 feet',
    components: ['V', 'S', 'M'], materialComponent: 'paper or leaf in the shape of a funnel',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'A mass of 5-foot-deep water appears and swirls in a 30-foot radius centered on a point you can see within range. The point must be on ground or in a body of water. Until the spell ends, that area is difficult terrain, and any creature that starts its turn there must succeed on a Strength saving throw or take 6d6 bludgeoning damage and be pulled 10 feet toward the center.',
    higherLevels: '',
    classes: ['Druid'],
    attackType: '', damage: '6d6', damageType: 'bludgeoning', scaling: '',
    savingThrow: 'STR', saveEffect: 'negates',
  },
  {
    name: 'Mass Cure Wounds', level: 5, school: 'Evocation',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'A wave of healing energy washes out from a point of your choice within range. Choose up to six creatures in a 30-foot-radius sphere centered on that point. Each target regains hit points equal to 3d8 + your spellcasting ability modifier. This spell has no effect on undead or constructs.',
    higherLevels: 'The healing increases by 1d8 for each slot level above 5th.',
    classes: ['Bard', 'Cleric', 'Druid'],
    attackType: '', damage: '3d8', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Mislead', level: 5, school: 'Illusion',
    castingTime: '1 action', range: 'Self',
    components: ['S'], materialComponent: '',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'You become invisible at the same time that an illusory double of you appears where you are standing. The double lasts for the duration, but the invisibility ends if you attack or cast a spell.\n\nYou can use your action to move your illusory double up to twice your speed and make it gesture, speak, and behave in whatever way you choose. You can see through its eyes and hear through its ears as if you were located where it is. On each of your turns as a bonus action, you can switch from using its senses to using your own, or back again. While you are using its senses, you are blinded and deafened in regard to your own surroundings.',
    higherLevels: '',
    classes: ['Bard', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Modify Memory', level: 5, school: 'Enchantment',
    castingTime: '1 action', range: '30 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You attempt to reshape another creature\'s memories. One creature that you can see must make a Wisdom saving throw. If you are fighting the creature, it has advantage on the saving throw. On a failed save, the target becomes charmed by you for the duration. The charmed target is incapacitated and unaware of its surroundings, though it can still hear you. If it takes any damage or is targeted by another spell, this spell ends, and none of the target\'s memories are modified.\n\nWhile this charm lasts, you can affect the target\'s memory of an event that it experienced within the last 24 hours and that lasted no more than 10 minutes. You can permanently eliminate all memory of the event, allow the target to recall the event with perfect clarity and exacting detail, change its memory of the details of the event, or create a memory of some other event.\n\nA modified memory doesn\'t necessarily affect how a creature behaves, particularly if the memory contradicts the creature\'s natural inclinations, alignment, or beliefs. An illogical modified memory is dismissed by the creature as a bad dream. The DM might rule that a modified memory is too nonsensical to affect a creature in a significant manner.\n\nA remove curse or greater restoration spell cast on the target restores the creature\'s true memory.',
    higherLevels: 'You can alter the target\'s memories of an event that took place up to 7 days ago (6th level), 30 days ago (7th level), 1 year ago (8th level), or any time in the creature\'s past (9th level).',
    classes: ['Bard', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'WIS', saveEffect: 'negates',
  },
  {
    name: 'Passwall', level: 5, school: 'Transmutation',
    castingTime: '1 action', range: '30 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a pinch of sesame seeds',
    duration: '1 hour', concentration: false, ritual: false,
    description: 'A passage appears at a point of your choice that you can see on a wooden, plaster, or stone surface (such as a wall, a ceiling, or a floor) within range, and lasts for the duration. You choose the opening\'s dimensions: up to 5 feet wide, 8 feet tall, and 20 feet deep. The passage creates no instability in a structure surrounding it.\n\nWhen the opening disappears, any creatures or objects still in the passage created by the spell are safely ejected to an unoccupied space nearest to the surface on which you cast the spell.',
    higherLevels: '',
    classes: ['Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Planar Binding', level: 5, school: 'Abjuration',
    castingTime: '1 hour', range: '60 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a jewel worth at least 1,000 gp, which the spell consumes',
    duration: '24 hours', concentration: false, ritual: false,
    description: 'With this spell, you attempt to bind a celestial, an elemental, a fey, or a fiend to your service. The creature must be within range for the entire casting of the spell. (Typically, the creature is first summoned into the center of an inverted magic circle in order to keep it trapped while this spell is cast.) At the completion of the casting, the target must make a Charisma saving throw. On a failed save, it is bound to serve you for the duration. If the creature was summoned or created by another spell, that spell\'s duration is extended to match the duration of this spell.\n\nA bound creature must follow your instructions to the best of its ability. You might command the creature to accompany you on an adventure, to guard a location, or to deliver a message.',
    higherLevels: 'The duration increases to 10 days (6th level), 30 days (7th level), 180 days (8th level), or a year and a day (9th level).',
    classes: ['Bard', 'Cleric', 'Druid', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'CHA', saveEffect: 'negates',
  },
  {
    name: 'Raise Dead', level: 5, school: 'Necromancy',
    castingTime: '1 hour', range: 'Touch',
    components: ['V', 'S', 'M'], materialComponent: 'a diamond worth at least 500 gp, which the spell consumes',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You return a creature that has perished within the last 10 days to life. If the creature\'s soul is both willing and at liberty to rejoin the body, the creature returns to life with 1 hit point.\n\nThis spell also neutralizes any poisons and cures nonmagical diseases that affected the creature at the time it perished. This spell doesn\'t, however, remove magical diseases, curses, or similar effects; if these aren\'t first removed prior to casting the spell, they take effect when the creature returns to life.\n\nThis spell closes all mortal wounds, but it doesn\'t restore missing body parts. If the creature is lacking body parts or organs integral for its survival, the spell automatically fails.\n\nComing back from the beyond is an ordeal. The target takes a -4 penalty to all attack rolls, saving throws, and ability checks. Every time the target finishes a long rest, the penalty is reduced by 1 until it disappears.',
    higherLevels: '',
    classes: ['Bard', 'Cleric', 'Paladin'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Reincarnate', level: 5, school: 'Transmutation',
    castingTime: '1 hour', range: 'Touch',
    components: ['V', 'S', 'M'], materialComponent: 'rare oils and unguents worth at least 1,000 gp, which the spell consumes',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You touch a creature that has perished within the last 10 days. Provided that the creature\'s soul is free and willing, the creature is restored to life with a new body. The spell forms a new adult body for the creature and then calls the soul to enter that body.\n\nThe magic fashions a new body for the creature to inhabit, which likely causes the creature\'s race to change. The DM rolls a d100 and consults the Reincarnate table to determine what form the creature takes when restored to life, or the DM chooses a form.\n\nThe reincarnated creature recalls its former life and experiences. It retains the capabilities it had in its original form, except it exchanges its original race for the new one and changes its racial traits accordingly.',
    higherLevels: '',
    classes: ['Druid'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Scrying', level: 5, school: 'Divination',
    castingTime: '10 minutes', range: 'Self',
    components: ['V', 'S', 'M'], materialComponent: 'a focus worth at least 1,000 gp, such as a crystal ball, a silver mirror, or a font filled with holy water',
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: false,
    description: 'You can see and hear a particular creature you choose that is on the same plane of existence as you. The target must make a Wisdom saving throw, which is modified by how well you know the target and the sort of physical connection you have to it. If a target knows you\'re casting this spell, it can fail the saving throw voluntarily if it wants to be observed.\n\nKnowledge — Save Modifier:\nSecondhand (you have heard of the target): +5\nFirsthand (you have met the target): +0\nFamiliar (you know the target well): -5\n\nConnection — Save Modifier:\nLikeness or picture: -2\nPossession or garment: -4\nBody part, lock of hair, bit of nail, or the like: -10\n\nOn a successful save, the target isn\'t affected, and you can\'t use this spell against it again for 24 hours. On a failed save, the spell creates an invisible sensor within 10 feet of the target. You can see and hear through the sensor as if you were there. The sensor moves with the target, remaining within 10 feet of it for the duration. A creature that can see invisible objects sees the sensor as a luminous orb about the size of your fist.',
    higherLevels: '',
    classes: ['Bard', 'Cleric', 'Druid', 'Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'WIS', saveEffect: 'negates',
  },
  {
    name: 'Seeming', level: 5, school: 'Illusion',
    castingTime: '1 action', range: '30 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: '8 hours', concentration: false, ritual: false,
    description: 'This spell allows you to change the appearance of any number of creatures that you can see within range. You give each target you choose a new, illusory appearance. An unwilling target can make a Charisma saving throw, and if it succeeds, it is unaffected by this spell.\n\nThe spell disguises physical appearance as well as clothing, armor, weapons, and equipment. You can make each creature seem 1 foot shorter or taller and appear thin, fat, or in between. You can\'t change a target\'s body type, so you must choose a form that has the same basic arrangement of limbs. Otherwise, the extent of the illusion is up to you.\n\nThe changes wrought by this spell fail to hold up to physical inspection. For example, if you use this spell to add a hat to a creature\'s outfit, objects pass through the hat, and anyone who touches it would feel nothing.\n\nA creature can use its action to inspect a target and make an Intelligence (Investigation) check against your spell save DC. If it succeeds, it becomes aware that the target is disguised.',
    higherLevels: '',
    classes: ['Bard', 'Sorcerer', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'CHA', saveEffect: 'negates',
  },
  {
    name: 'Skill Empowerment', level: 5, school: 'Transmutation',
    castingTime: '1 action', range: 'Touch',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'Your magic deepens a creature\'s understanding of its own talent. You touch one willing creature and give it expertise in one skill of your choice; the creature must already be proficient in that skill. Until the spell ends, the creature doubles its proficiency bonus for ability checks it makes that use the chosen skill.',
    higherLevels: '',
    classes: ['Bard', 'Sorcerer', 'Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Steel Wind Strike', level: 5, school: 'Conjuration',
    castingTime: '1 action', range: '30 feet',
    components: ['S', 'M'], materialComponent: 'a melee weapon worth at least 1 sp',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You flourish the weapon used in the casting and then vanish to strike like the wind. Choose up to five creatures you can see within range. Make a melee spell attack against each target. On a hit, a target takes 6d10 force damage. You can then teleport to an unoccupied space you can see within 5 feet of one of the targets you hit or missed.',
    higherLevels: '',
    classes: ['Ranger', 'Wizard'],
    attackType: 'melee', damage: '6d10', damageType: 'force', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Summon Celestial', level: 5, school: 'Conjuration',
    castingTime: '1 action', range: '90 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a golden reliquary worth at least 500 gp',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'You call forth a celestial spirit. It manifests in an angelic form in an unoccupied space that you can see within range. This corporeal form uses the Celestial Spirit stat block. When you cast the spell, choose Avenger or Defender. Your choice determines the creature\'s attack in its stat block. The creature disappears when it drops to 0 hit points or when the spell ends.\n\nThe creature is an ally to you and your companions. In combat, the creature shares your initiative count, but it takes its turn immediately after yours. It obeys your verbal commands (no action required by you). If you don\'t issue any, it takes the Dodge action and uses its move to avoid danger.',
    higherLevels: 'The creature assumes the higher level for its stat block when you cast this spell with a spell slot of 6th level or higher.',
    classes: ['Cleric'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Swift Quiver', level: 5, school: 'Transmutation',
    castingTime: '1 bonus action', range: 'Touch',
    components: ['V', 'S', 'M'], materialComponent: 'a quiver containing at least one piece of ammunition',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You transmute your quiver so it produces an endless supply of nonmagical ammunition, which seems to leap into your hand when you reach for it. On each of your turns until the spell ends, you can use a bonus action to make two attacks with a weapon that uses ammunition from the quiver. Each time you make such a ranged attack, your quiver magically replaces the piece of ammunition you used with a similar piece of nonmagical ammunition. Any pieces of ammunition created by this spell disintegrate when the spell ends. If the quiver leaves your possession, the spell ends.',
    higherLevels: '',
    classes: ['Ranger'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Synaptic Static', level: 5, school: 'Enchantment',
    castingTime: '1 action', range: '120 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You choose a point within range and cause psychic energy to explode there. Each creature in a 20-foot-radius sphere centered on that point must make an Intelligence saving throw. On a failed save, a target takes 8d6 psychic damage and suffers muddled thoughts for 1 minute. A target can make an Intelligence saving throw at the end of each of its turns, ending the muddled thoughts on a success. A muddled target must roll a d6 and subtract the number rolled from all its attack rolls and ability checks, as well as its Constitution saving throws to maintain concentration. On a successful save, a target takes half as much damage and suffers no other effect.',
    higherLevels: '',
    classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    attackType: '', damage: '8d6', damageType: 'psychic', scaling: '',
    savingThrow: 'INT', saveEffect: 'half damage, no muddled thoughts',
  },
  {
    name: 'Telekinesis', level: 5, school: 'Transmutation',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: false,
    description: 'You gain the ability to move or manipulate creatures or objects by thought. When you cast the spell, and as your action each round for the duration, you can exert your will on one creature or object that you can see within range, causing the appropriate effect below.\n\nCreature. You can try to move a Huge or smaller creature. Make an ability check with your spellcasting ability contested by the creature\'s Strength check. If you win the contest, you move the creature up to 30 feet in any direction, including upward but not beyond the range of this spell. Until the end of your next turn, the creature is restrained in your telekinetic grip. A creature lifted upward is suspended in mid-air. On subsequent rounds, you can use your action to attempt to maintain your telekinetic grip on the creature by repeating the contest.\n\nObject. You can try to move an object that weighs up to 1,000 pounds. If the object isn\'t being worn or carried, you automatically move it up to 30 feet in any direction, but not beyond the range of this spell. If the object is worn or carried by a creature, you must make an ability check with your spellcasting ability contested by that creature\'s Strength check. If you succeed, you pull the object away from that creature and can move it up to 30 feet in any direction but not beyond the range of this spell.\n\nYou can exert fine control on objects with your telekinetic grip, such as manipulating a simple tool, opening a door or a container, stowing or retrieving an item from an open container, or pouring the contents from a vial.',
    higherLevels: '',
    classes: ['Sorcerer', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Teleportation Circle', level: 5, school: 'Conjuration',
    castingTime: '1 minute', range: '10 feet',
    components: ['V', 'M'], materialComponent: 'rare chalks and inks infused with precious gems worth 50 gp, which the spell consumes',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'As you cast the spell, you draw a 10-foot-diameter circle on the ground inscribed with sigils that link your location to a permanent teleportation circle of your choice whose sigil sequence you know and that is on the same plane of existence as you. A shimmering portal opens within the circle you drew and remains open until the end of your next turn. Any creature that enters the portal instantly appears within 5 feet of the destination circle or in the nearest unoccupied space if that space is occupied.\n\nYou can create a permanent teleportation circle by casting this spell in the same location every day for one year. You need not use the circle to teleport when you cast the spell in this way.',
    higherLevels: '',
    classes: ['Bard', 'Sorcerer', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Transmute Rock', level: 5, school: 'Transmutation',
    castingTime: '1 action', range: '120 feet',
    components: ['V', 'S', 'M'], materialComponent: 'clay and water',
    duration: 'Until dispelled', concentration: false, ritual: false,
    description: 'You choose an area of stone or mud that you can see that fits within a 40-foot cube and that is within range, and choose one of the following effects.\n\nTransmute Rock to Mud. Nonmagical rock of any sort in the area becomes an equal volume of thick, flowing mud that remains for the spell\'s duration. The ground in the spell\'s area becomes muddy enough that creatures can sink into it. Each foot that a creature moves through the mud costs 4 feet of movement, and any creature on the ground when you cast the spell must make a Strength saving throw. A creature must also make this save the first time it enters the area on a turn or ends its turn there. On a failed save, a creature sinks into the mud and is restrained, though it can use an action to end the restrained condition on itself by pulling itself free of the mud. If you cast the spell on a ceiling, the mud falls. Any creature under the mud when it falls must make a Dexterity saving throw. A creature takes 4d8 bludgeoning damage on a failed save, or half as much on a successful one.\n\nTransmute Mud to Rock. Nonmagical mud or quicksand in the area no more than 10 feet deep transforms into soft stone for the spell\'s duration. Any creature in the mud when it transforms must make a Dexterity saving throw. On a successful save, a creature is shunted safely to the surface. On a failed save, a creature becomes restrained by the rock. A restrained creature can use an action to try to break free by succeeding on a DC 20 Strength check or by dealing damage to the rock around it. The rock has AC 15 and 25 hit points.',
    higherLevels: '',
    classes: ['Druid', 'Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'STR', saveEffect: 'not restrained',
  },
  {
    name: 'Tree Stride', level: 5, school: 'Conjuration',
    castingTime: '1 action', range: 'Self',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You gain the ability to enter a tree and move from inside it to inside another tree of the same kind within 500 feet. Both trees must be living and at least the same size as you. You must use 5 feet of movement to enter a tree. You instantly know the location of all other trees of the same kind within 500 feet and, as part of the move used to enter the tree, can either pass into one of those trees or step out of the tree you\'re in. You appear in a spot of your choice within 5 feet of the destination tree, using another 5 feet of movement. If you have no movement left, you appear within 5 feet of the tree you entered.\n\nYou can use this transportation ability once per round for the duration. You must end each turn outside a tree.',
    higherLevels: '',
    classes: ['Druid', 'Ranger'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Wall of Force', level: 5, school: 'Evocation',
    castingTime: '1 action', range: '120 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a pinch of powder made by crushing a clear gemstone',
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: false,
    description: 'An invisible wall of force springs into existence at a point you choose within range. The wall appears in any orientation you choose, as a horizontal or vertical barrier or at an angle. It can be free floating or resting on a solid surface. You can form it into a hemispherical dome or a sphere with a radius of up to 10 feet, or you can shape a flat surface made up of ten 10-foot-by-10-foot panels. Each panel must be contiguous with another panel. In any form, the wall is 1/4 inch thick. It lasts for the duration. If the wall cuts through a creature\'s space when it appears, the creature is pushed to one side of the wall (your choice which side).\n\nNothing can physically pass through the wall. It is immune to all damage and can\'t be dispelled by dispel magic. A disintegrate spell destroys the wall instantly, however. The wall also extends into the Ethereal Plane, blocking ethereal travel through the wall.',
    higherLevels: '',
    classes: ['Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Wall of Light', level: 5, school: 'Evocation',
    castingTime: '1 action', range: '120 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a hand mirror',
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: false,
    description: 'A shimmering wall of bright light appears at a point you choose within range. The wall appears in any orientation you choose: horizontally, vertically, or diagonally. It can be free floating, or it can rest on a solid surface. The wall can be up to 60 feet long, 10 feet high, and 5 feet thick. The wall blocks line of sight, but creatures and objects can pass through it. It emits bright light out to 120 feet and dim light for an additional 120 feet.\n\nWhen the wall appears, each creature in its area must make a Constitution saving throw. On a failed save, a creature takes 4d8 radiant damage, and it is blinded for 1 minute. On a successful save, it takes half as much damage and isn\'t blinded. A blinded creature can make a Constitution saving throw at the end of each of its turns, ending the effect on itself on a success.\n\nA creature that ends its turn in the wall\'s area takes 4d8 radiant damage.\n\nUntil the spell ends, you can use an action to launch a beam of radiance from the wall at one creature you can see within 60 feet of it. Make a ranged spell attack. On a hit, the target takes 4d8 radiant damage. Whether you hit or miss, reduce the length of the wall by 10 feet. If the wall\'s length drops to 0 feet, the spell ends.',
    higherLevels: 'The damage increases by 1d8 for each slot level above 5th.',
    classes: ['Sorcerer', 'Warlock', 'Wizard'],
    attackType: 'ranged', damage: '4d8', damageType: 'radiant', scaling: '',
    savingThrow: 'CON', saveEffect: 'half damage, not blinded',
  },
  {
    name: 'Wall of Stone', level: 5, school: 'Evocation',
    castingTime: '1 action', range: '120 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a small block of granite',
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: false,
    description: 'A nonmagical wall of solid stone springs into existence at a point you choose within range. The wall is 6 inches thick and is composed of ten 10-foot-by-10-foot panels. Each panel must be contiguous with at least one other panel. Alternatively, you can create 10-foot-by-20-foot panels that are only 3 inches thick.\n\nIf the wall cuts through a creature\'s space when it appears, the creature is pushed to one side of the wall (your choice). If a creature would be surrounded on all sides by the wall (or the wall and another solid surface), that creature can make a Dexterity saving throw. On a success, it can use its reaction to move up to its speed so that it is no longer enclosed by the wall.\n\nThe wall can have any shape you desire, though it can\'t occupy the same space as a creature or object. The wall doesn\'t need to be vertical or rest on any firm foundation. It must, however, merge with and be solidly supported by existing stone. Thus, you can use this spell to bridge a chasm or create a ramp.\n\nIf you create a span greater than 20 feet in length, you must halve the size of each panel to create supports. Each panel has AC 15 and 30 hit points per inch of thickness. Reducing a panel to 0 hit points destroys it.\n\nIf you maintain your concentration on this spell for its whole duration, the wall becomes permanent and can\'t be dispelled. Otherwise, the wall disappears when the spell ends.',
    higherLevels: '',
    classes: ['Druid', 'Sorcerer', 'Wizard', 'Artificer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'DEX', saveEffect: 'can move to avoid enclosure',
  },
  {
    name: 'Wrath of Nature', level: 5, school: 'Evocation',
    castingTime: '1 action', range: '120 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You call out to the spirits of nature to rouse them against your enemies. Choose a point you can see within range. The spirits cause trees, rocks, and grasses in a 60-foot cube centered on that point to become animated until the spell ends.\n\nGrasses and Undergrowth. Any area of ground in the cube that is covered by grass or undergrowth is difficult terrain for your enemies.\n\nTrees. At the start of each of your turns, each of your enemies within 10 feet of any tree in the cube must succeed on a Dexterity saving throw or take 4d6 slashing damage from whipping branches.\n\nRoots and Vines. At the end of each of your turns, one creature of your choice that is on the ground in the cube must succeed on a Strength saving throw or become restrained until the spell ends. A restrained creature can use an action to make a Strength (Athletics) check against your spell save DC, ending the effect on itself on a success.\n\nRocks. As a bonus action on your turn, you can cause a loose rock in the cube to launch at a creature you can see in the cube. Make a ranged spell attack. On a hit, the target takes 3d8 nonmagical bludgeoning damage, and it must succeed on a Strength saving throw or fall prone.',
    higherLevels: '',
    classes: ['Druid', 'Ranger'],
    attackType: 'ranged', damage: '4d6', damageType: 'slashing', scaling: '',
    savingThrow: 'DEX', saveEffect: 'negates branch damage',
  },
  {
    name: 'Contagion', level: 5, school: 'Necromancy',
    castingTime: '1 action', range: 'Touch',
    components: ['V', 'S'], materialComponent: '',
    duration: '7 days', concentration: false, ritual: false,
    description: 'Your touch inflicts disease. Make a melee spell attack against a creature within your reach. On a hit, you afflict the creature with a disease of your choice from any of the diseases described below.\n\nAt the end of each of the target\'s turns, it must make a Constitution saving throw. After failing three of these saving throws, the disease\'s effects last for the duration, and the creature stops making these saves. After succeeding on three of these saving throws, the creature recovers from the disease, and the spell ends.\n\nBlinding Sickness. The creature has disadvantage on Wisdom checks and Wisdom saving throws and is blinded.\n\nFilth Fever. The creature has disadvantage on Strength checks, Strength saving throws, and attack rolls that use Strength.\n\nFlesh Rot. The creature has disadvantage on Charisma checks and vulnerability to all damage.\n\nMindfire. The creature has disadvantage on Intelligence checks and Intelligence saving throws, and the creature behaves as if under the effects of the confusion spell during combat.\n\nSeizure. The creature has disadvantage on Dexterity checks, Dexterity saving throws, and attack rolls that use Dexterity.\n\nSlimy Doom. The creature has disadvantage on Constitution checks and Constitution saving throws. In addition, whenever the creature takes damage, it is stunned until the end of its next turn.',
    higherLevels: '',
    classes: ['Cleric', 'Druid'],
    attackType: 'melee', damage: '', damageType: '', scaling: '',
    savingThrow: 'CON', saveEffect: '3 successes ends spell',
  },
  {
    name: 'Danse Macabre', level: 5, school: 'Necromancy',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'Threads of dark power leap from your fingers to pierce up to five Small or Medium corpses you can see within range. Each corpse immediately stands up and becomes undead. You decide whether it is a zombie or a skeleton (the statistics for zombies and skeletons are in the Monster Manual), and it gains a bonus to its attack and damage rolls equal to your spellcasting ability modifier.\n\nYou can use a bonus action to mentally command the creatures you make with this spell, issuing the same command to all of them. To receive the command, a creature must be within 60 feet of you. You decide what action the creature will take and where it will move during its next turn, or you can issue a general command, such as to guard a chamber or passageway against your foes. If you issue no commands, the creature only defends itself against hostile creatures. Once given an order, the creature continues to follow it until its task is complete.\n\nThe creatures are under your control until the spell ends, after which they become inanimate once more.',
    higherLevels: 'When you cast this spell using a spell slot of 6th level or higher, you animate up to two additional corpses for each slot level above 5th.',
    classes: ['Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Dominate Person', level: 5, school: 'Enchantment',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You attempt to beguile a humanoid that you can see within range. It must succeed on a Wisdom saving throw or be charmed by you for the duration. If you or creatures that are friendly to you are fighting it, it has advantage on the saving throw.\n\nWhile the target is charmed, you have a telepathic link with it as long as the two of you are on the same plane of existence. You can use this telepathic link to issue commands to the creature while you are conscious (no action required), which it does its best to obey. You can specify a simple and general course of action, such as "Attack that creature," "Run over there," or "Fetch that object." If the creature completes the order and doesn\'t receive further direction from you, it defends and preserves itself to the best of its ability.\n\nYou can use your action to take total and precise control of the target. Until the end of your next turn, the creature takes only the actions you choose, and doesn\'t do anything that you don\'t allow it to do.\n\nEach time the target takes damage, it makes a new Wisdom saving throw against the spell. If the saving throw succeeds, the spell ends.',
    higherLevels: 'When you cast this spell with a 6th-level spell slot, the duration is concentration, up to 10 minutes. With a 7th-level slot, the duration is concentration, up to 1 hour. With an 8th-level slot, the duration is concentration, up to 8 hours.',
    classes: ['Bard', 'Sorcerer', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'WIS', saveEffect: 'negates',
  },
  {
    name: 'Enervation', level: 5, school: 'Necromancy',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'A tendril of inky darkness reaches out from you, touching a creature you can see within range to drain life from it. The target must make a Dexterity saving throw. On a successful save, the target takes 2d8 necrotic damage, and the spell ends. On a failed save, the target takes 4d8 necrotic damage, and until the spell ends, you can use your action on each of your turns to automatically deal 4d8 necrotic damage to the target. The spell ends if you use your action to do anything else, if the target is ever outside the spell\'s range, or if the target has total cover from you.\n\nWhenever the spell deals damage to a target, you regain hit points equal to half the amount of necrotic damage the target takes.',
    higherLevels: 'When you cast this spell using a spell slot of 6th level or higher, the damage increases by 1d8 for each slot level above 5th.',
    classes: ['Sorcerer', 'Warlock', 'Wizard'],
    attackType: '', damage: '4d8', damageType: 'necrotic', scaling: '',
    savingThrow: 'DEX', saveEffect: '2d8 and spell ends',
  },
  {
    name: 'Geas', level: 5, school: 'Enchantment',
    castingTime: '1 minute', range: '60 feet',
    components: ['V'], materialComponent: '',
    duration: '30 days', concentration: false, ritual: false,
    description: 'You place a magical command on a creature that you can see within range, forcing it to carry out some service or refrain from some action or course of activity as you decide. If the creature can understand you, it must succeed on a Wisdom saving throw or become charmed by you for the duration. While the creature is charmed by you, it takes 5d10 psychic damage each time it acts in a manner directly counter to your instructions, but no more than once each day. A creature that can\'t understand you is unaffected by the spell.\n\nYou can issue any command you choose, short of an activity that would result in certain death. Should you issue a suicidal command, the spell ends.\n\nYou can end the spell early by using an action to dismiss it. A remove curse, greater restoration, or wish spell also ends it.',
    higherLevels: 'When you cast this spell using a spell slot of 7th or 8th level, the duration is 1 year. When you cast this spell using a spell slot of 9th level, the spell lasts until it is ended by one of the spells mentioned above.',
    classes: ['Bard', 'Cleric', 'Druid', 'Paladin', 'Wizard'],
    attackType: '', damage: '5d10', damageType: 'psychic', scaling: '',
    savingThrow: 'WIS', saveEffect: 'negates',
  },
  {
    name: 'Immolation', level: 5, school: 'Evocation',
    castingTime: '1 action', range: '90 feet',
    components: ['V'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'Flames wreathe one creature you can see within range. The target must make a Dexterity saving throw. It takes 8d6 fire damage on a failed save, or half as much damage on a successful one. On a failed save, the target also burns for the spell\'s duration. The burning target sheds bright light in a 30-foot radius and dim light for an additional 30 feet. At the start of each of its turns until the spell ends, the target must make another Dexterity saving throw. It takes 4d6 fire damage on a failed save, and the spell ends on a successful one. These magical flames can\'t be extinguished by nonmagical means.\n\nIf damage from this spell reduces a target to 0 hit points, the target is turned to ash.',
    higherLevels: '',
    classes: ['Sorcerer', 'Wizard'],
    attackType: '', damage: '8d6', damageType: 'fire', scaling: '',
    savingThrow: 'DEX', saveEffect: 'half damage, no ongoing',
  },
  {
    name: 'Infernal Calling', level: 5, school: 'Conjuration',
    castingTime: '1 minute', range: '90 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a ruby worth at least 999 gp',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'Uttering a dark incantation, you summon a devil from the Nine Hells. You choose the devil\'s type, which must be one of challenge rating 6 or lower. The devil appears in an unoccupied space that you can see within range. The devil disappears when it drops to 0 hit points or when the spell ends.\n\nThe devil is unfriendly toward you and your companions. Roll initiative for the devil, which has its own turns. It is under the DM\'s control and acts according to its nature on each of its turns, which might result in its attacking you if it thinks it can prevail, or trying to tempt you to undertake an evil act in exchange for limited service.\n\nIf you know a specific devil\'s true name or possess a talisman connected to it, you can request that devil. Otherwise, the DM chooses which devil answers. If you know a devil\'s true name, you can speak it to force that devil to obey your commands, though it may try to trick you.',
    higherLevels: 'When you cast this spell using a spell slot of 6th level or higher, the challenge rating increases by 1 for each slot level above 5th.',
    classes: ['Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Negative Energy Flood', level: 5, school: 'Necromancy',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'M'], materialComponent: 'a broken bone and a square of black silk',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You send ribbons of negative energy at one creature you can see within range. Unless the target is undead, it must make a Constitution saving throw, taking 5d12 necrotic damage on a failed save, or half as much damage on a successful one. A target that is reduced to 0 hit points by this damage rises up as a zombie at the start of your next turn. The zombie pursues whatever creature it can see that is closest to it. Statistics for the zombie are in the Monster Manual.\n\nIf you target an undead with this spell, the target doesn\'t make a saving throw. Instead, roll 5d12. The target gains half the total as temporary hit points.',
    higherLevels: '',
    classes: ['Warlock', 'Wizard'],
    attackType: '', damage: '5d12', damageType: 'necrotic', scaling: '',
    savingThrow: 'CON', saveEffect: 'half damage',
  },
  {
    name: "Yolande's Regal Presence", level: 5, school: 'Enchantment',
    castingTime: '1 action', range: 'Self',
    components: ['V', 'S', 'M'], materialComponent: 'a miniature crown',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You surround yourself with unearthly majesty in a 10-foot emanation. Whenever the emanation enters the space of a creature you can see and whenever a creature you can see enters the emanation or ends its turn there, you can force that creature to make a Wisdom saving throw. On a failed save, the target is charmed or frightened by you (your choice) for 1 minute. The target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.\n\nA target that succeeds on the saving throw is immune to your use of this spell for 24 hours.',
    higherLevels: '',
    classes: ['Bard', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'WIS', saveEffect: 'immune for 24 hours',
  },
];

(async () => {
  await mongoose.connect(process.env.MONGODB_URI);
  for (const sp of SPELLS) await Spell.findOneAndUpdate({ name: sp.name, level: sp.level }, sp, { upsert: true });
  console.log(`Seeded ${SPELLS.length} level-5 spells`);
  process.exit(0);
})();
