require('dotenv').config();
const mongoose = require('mongoose');
const Spell = require('./models/Spell');

const SPELLS = [
  {
    name: 'Conjure Celestial', level: 7, school: 'Conjuration',
    castingTime: '1 minute', range: '90 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'You summon a celestial of challenge rating 4 or lower, which appears in an unoccupied space that you can see within range. The celestial disappears when it drops to 0 hit points or when the spell ends.\n\nThe celestial is friendly to you and your companions for the duration. Roll initiative for the celestial, which has its own turns. It obeys any verbal commands that you issue to it (no action required by you), as long as they don\'t violate its alignment. If you don\'t issue any commands to the celestial, it defends itself from hostile creatures but otherwise takes no actions.\n\nThe DM has the celestial\'s statistics.',
    higherLevels: 'When you cast this spell using a 9th-level spell slot, you summon a celestial of challenge rating 5 or lower.',
    classes: ['Cleric'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Crown of Stars', level: 7, school: 'Evocation',
    castingTime: '1 action', range: 'Self',
    components: ['V', 'S'], materialComponent: '',
    duration: '1 hour', concentration: false, ritual: false,
    description: 'Seven star-like motes of light appear and orbit your head until the spell ends. You can use a bonus action to send one of the motes streaking toward one creature or object within 120 feet of you. When you do so, make a ranged spell attack. On a hit, the target takes 4d12 radiant damage. Whether you hit or miss, the mote is expended. The spell ends early if you expend the last mote.\n\nIf you have four or more motes remaining, they shed bright light in a 30-foot radius and dim light for an additional 30 feet. If you have one to three motes remaining, they shed dim light in a 30-foot radius.\n\nIf another effect is already producing starlight within the same area as the motes, the motes are suppressed. They resume functioning once the conflicting effect ends.',
    higherLevels: 'Two additional motes are created for each slot level above 7th.',
    classes: ['Sorcerer', 'Warlock', 'Wizard'],
    attackType: 'ranged', damage: '4d12', damageType: 'radiant', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Delayed Blast Fireball', level: 7, school: 'Evocation',
    castingTime: '1 action', range: '150 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a tiny ball of bat guano and sulfur',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'A beam of yellow light flashes from your pointing finger, then condenses to linger at a chosen point within range as a glowing bead for the duration. When the spell ends, either because your concentration is broken or because you decide to end it, the bead blossoms with a low roar into an explosion of flame that spreads around corners. Each creature in a 20-foot-radius sphere centered on that point must make a Dexterity saving throw. A creature takes fire damage equal to the total accumulated damage on a failed save, or half as much damage on a successful one.\n\nThe spell\'s base damage is 12d6. If at the end of your turn the bead has not yet detonated, the damage increases by 1d6.\n\nIf the glowing bead is touched before the interval has expired, the creature touching it must make a Dexterity saving throw. On a failed save, the spell ends immediately, causing the bead to erupt in flame. On a successful save, the creature can throw the bead up to 40 feet. When it strikes a creature or a solid object, the spell ends, and the bead explodes.',
    higherLevels: 'The base damage increases by 1d6 for each slot level above 7th.',
    classes: ['Sorcerer', 'Wizard'],
    attackType: '', damage: '12d6', damageType: 'fire', scaling: '',
    savingThrow: 'DEX', saveEffect: 'half damage',
  },
  {
    name: 'Divine Word', level: 7, school: 'Evocation',
    castingTime: '1 bonus action', range: '30 feet',
    components: ['V'], materialComponent: '',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You utter a divine word, imbued with the power that shaped the world at the dawn of creation. Choose any number of creatures you can see within range. Each creature that can hear you must make a Charisma saving throw. On a failed save, a creature suffers an effect based on its current hit points:\n\n- 50 hit points or fewer: deafened for 1 minute\n- 40 hit points or fewer: deafened and blinded for 10 minutes\n- 30 hit points or fewer: blinded, deafened, and stunned for 1 hour\n- 20 hit points or fewer: killed instantly\n\nRegardless of its current hit points, a celestial, an elemental, a fey, or a fiend that fails its save is forced back to its plane of origin (if it isn\'t there already) and can\'t return to your current plane for 24 hours by any means short of a wish spell.',
    higherLevels: '',
    classes: ['Cleric'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'CHA', saveEffect: 'negates',
  },
  {
    name: 'Dream of the Blue Veil', level: 7, school: 'Conjuration',
    castingTime: '10 minutes', range: '20 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a magic item or a willing creature from the destination world',
    duration: '6 hours', concentration: false, ritual: false,
    description: 'You and up to eight willing creatures within range fall unconscious for the spell\'s duration and experience visions of another world on the Material Plane, such as Oerth, Toril, Krynn, or Eberron. If the spell reaches its full duration, the visions conclude with each of you encountering and pulling back a mysterious blue curtain. The spell then ends with you mentally and physically transported to the world that was in the visions.\n\nTo cast this spell, you must have a magic item that originated on the world you wish to reach, and you must be aware of the world\'s existence, even if you don\'t know the world\'s name. Your destination in the other world is a safe location within 1 mile of where the magic item was created. Alternatively, you can cast the spell if one of the affected creatures was born on the other world, which causes your destination to be a safe location within 1 mile of where that creature was born.\n\nThe spell ends early on a creature if that creature takes any damage, and the creature isn\'t transported. If you take damage during the spell, the spell ends for you and all the other creatures, with none of you being transported.',
    higherLevels: '',
    classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Etherealness', level: 7, school: 'Transmutation',
    castingTime: '1 action', range: 'Self',
    components: ['V', 'S'], materialComponent: '',
    duration: '8 hours', concentration: false, ritual: false,
    description: 'You step into the border regions of the Ethereal Plane, in the area where it overlaps with your current plane. You remain in the Border Ethereal for the duration or until you use your action to dismiss the spell. During this time, you can move in any direction. If you move up or down, every foot of movement costs an extra foot. You can see and hear the plane you originated from, but everything there looks gray, and you can\'t see anything more than 60 feet away.\n\nWhile on the Ethereal Plane, you can only affect and be affected by other creatures on that plane. Creatures that aren\'t on the Ethereal Plane can\'t perceive you and can\'t interact with you, unless a special ability or magic has given them the ability to do so.\n\nYou ignore all objects and effects that aren\'t on the Ethereal Plane, allowing you to move through objects you perceive on the plane you originated from. When the spell ends, you immediately return to the plane you originated from in the spot you currently occupy. If you occupy the same spot as a solid object or creature when this happens, you are immediately shunted to the nearest unoccupied space that you can occupy and take force damage equal to twice the number of feet you are moved.\n\nThis spell has no effect if you cast it while you are on the Ethereal Plane or a plane that doesn\'t border it, such as one of the Outer Planes.',
    higherLevels: 'You can target up to three willing creatures (including you) for each slot level above 7th.',
    classes: ['Bard', 'Cleric', 'Sorcerer', 'Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Finger of Death', level: 7, school: 'Necromancy',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You send negative energy coursing through a creature that you can see within range, causing it searing pain. The target must make a Constitution saving throw. It takes 7d8 + 30 necrotic damage on a failed save, or half as much damage on a successful one.\n\nA humanoid killed by this spell rises at the start of your next turn as a zombie that is permanently under your command, following your verbal orders to the best of its ability.',
    higherLevels: '',
    classes: ['Sorcerer', 'Warlock', 'Wizard'],
    attackType: '', damage: '7d8', damageType: 'necrotic', scaling: '',
    savingThrow: 'CON', saveEffect: 'half damage',
  },
  {
    name: 'Fire Storm', level: 7, school: 'Evocation',
    castingTime: '1 action', range: '150 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'A storm made up of sheets of roaring flame appears in a location you choose within range. The area of the storm consists of up to ten 10-foot cubes, which you can arrange as you wish. Each cube must have at least one face adjacent to the face of another cube. Each creature in the area must make a Dexterity saving throw. It takes 7d10 fire damage on a failed save, or half as much damage on a successful one.\n\nThe fire damages objects in the area and ignites flammable objects that aren\'t being worn or carried. If you choose, plant life in the area is unaffected by this spell.',
    higherLevels: '',
    classes: ['Cleric', 'Druid', 'Sorcerer'],
    attackType: '', damage: '7d10', damageType: 'fire', scaling: '',
    savingThrow: 'DEX', saveEffect: 'half damage',
  },
  {
    name: 'Forcecage', level: 7, school: 'Evocation',
    castingTime: '1 action', range: '100 feet',
    components: ['V', 'S', 'M'], materialComponent: 'ruby dust worth 1,500 gp',
    duration: '1 hour', concentration: false, ritual: false,
    description: 'An immobile, invisible, cube-shaped prison composed of magical force springs into existence around an area you choose within range. The prison can be a cage or a solid box, as you choose.\n\nA prison in the shape of a cage can be up to 20 feet on a side and is made from 1/2-inch diameter bars spaced 1/2 inch apart. A prison in the shape of a box can be up to 10 feet on a side, creating a solid barrier that prevents any matter from passing through it and blocking any spells cast into or out from the area.\n\nWhen you cast the spell, any creature that is completely inside the cage\'s area is trapped. Creatures only partially within the area, or those too large to fit inside the area, are pushed away from the center of the area until they are completely outside the area.\n\nA creature inside the cage can\'t leave it by nonmagical means. If the creature tries to use teleportation or interplanar travel to leave the cage, it must first make a Charisma saving throw. On a success, the creature can use that magic to exit the cage. On a failure, the creature can\'t exit the cage and wastes the use of the spell or effect. The cage also extends into the Ethereal Plane, blocking ethereal travel.\n\nThis spell can\'t be dispelled by dispel magic.',
    higherLevels: '',
    classes: ['Bard', 'Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'CHA', saveEffect: 'can teleport out',
  },
  {
    name: 'Mirage Arcane', level: 7, school: 'Illusion',
    castingTime: '10 minutes', range: 'Sight',
    components: ['V', 'S'], materialComponent: '',
    duration: '10 days', concentration: false, ritual: false,
    description: 'You make terrain in an area up to 1 mile square look, sound, smell, and even feel like some other sort of terrain. The terrain\'s general shape remains the same, however. Open fields or a road could be made to resemble a swamp, hill, crevasse, or some other difficult or impassable terrain. A pond can be made to seem like a grassy meadow, a precipice like a gentle slope, or a rock-strewn gully like a wide and smooth road.\n\nSimilarly, you can alter the appearance of structures, or add them where none are present. The spell doesn\'t disguise, conceal, or add creatures.\n\nThe illusion includes audible, visual, tactile, and olfactory elements, so it can turn clear ground into difficult terrain (or vice versa) or otherwise impede movement through the area. Any piece of the illusory terrain (such as a rock or stick) that is removed from the spell\'s area disappears immediately.\n\nCreatures with truesight can see through the illusion to the terrain\'s true form; however, all other elements of the illusion remain, so while the creature is aware of the illusion\'s presence, the creature can still physically interact with the illusion.',
    higherLevels: '',
    classes: ['Bard', 'Druid', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: "Mordenkainen's Magnificent Mansion", level: 7, school: 'Conjuration',
    castingTime: '1 minute', range: '300 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a miniature portal carved from ivory, a small piece of polished marble, and a tiny silver spoon, each item worth at least 5 gp',
    duration: '24 hours', concentration: false, ritual: false,
    description: 'You conjure an extradimensional dwelling in range that lasts for the duration. You choose where its one entrance is located. The entrance shimmers faintly and is 5 feet wide and 10 feet tall. You and any creature you designate when you cast the spell can enter the extradimensional dwelling as long as the portal remains open. You can open or close the portal if you are within 30 feet of it. While closed, the portal is invisible.\n\nBeyond the portal is a magnificent foyer with numerous chambers beyond. The atmosphere is clean, fresh, and warm. You can create any floor plan you like, but the space can\'t exceed 50 cubes, each cube being 10 feet on each side. The place is furnished and decorated as you choose. It contains sufficient food to serve a nine-course banquet for up to 100 people. A staff of 100 near-transparent servants attends all who enter. You decide the visual appearance of these servants and their attire. They are completely obedient to your orders. Each servant can perform any task a normal human servant could perform, but they can\'t attack or take any action that would directly harm another creature. Thus the servants can fetch things, clean, mend, fold clothes, light fires, serve food, pour wine, and so on. The servants can go anywhere in the mansion but can\'t leave it. Furnishings and other objects created by this spell dissipate into smoke if removed from the mansion. When the spell ends, any creatures inside the extradimensional space are expelled into the open spaces nearest to the entrance.',
    higherLevels: '',
    classes: ['Bard', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: "Mordenkainen's Sword", level: 7, school: 'Evocation',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a miniature platinum sword with a grip and pommel of copper and zinc, worth 250 gp',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You create a sword-shaped plane of force that hovers within range. It lasts for the duration. When the sword appears, you make a melee spell attack against a target of your choice within 5 feet of the sword. On a hit, the target takes 3d10 force damage. Until the spell ends, you can use a bonus action on each of your turns to move the sword up to 20 feet to a spot you can see and repeat this attack against the same target or a different one.',
    higherLevels: '',
    classes: ['Bard', 'Wizard'],
    attackType: 'melee', damage: '3d10', damageType: 'force', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Plane Shift', level: 7, school: 'Conjuration',
    castingTime: '1 action', range: 'Touch',
    components: ['V', 'S', 'M'], materialComponent: 'a forked, metal rod worth at least 250 gp, attuned to a particular plane of existence',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You and up to eight willing creatures who link hands in a circle are transported to a different plane of existence. You can specify a target destination in general terms, such as the City of Brass on the Elemental Plane of Fire or the palace of Dispater on the second level of the Nine Hells, and you appear in or near that destination. If you are trying to reach the City of Brass, for example, you might arrive in its Street of Steel, before its Gate of Ashes, or looking at the city from across the Sea of Fire, at the DM\'s discretion.\n\nAlternatively, if you know the sigil sequence of a teleportation circle on another plane of existence, this spell can take you to that circle. If the teleportation circle is too small to hold all the creatures you transported, they appear in the closest unoccupied spaces next to the circle.\n\nYou can use this spell to banish an unwilling creature to another plane. Choose a creature within your reach and make a melee spell attack against it. On a hit, the creature must make a Charisma saving throw. If the creature fails this save, it is transported to a random location on the plane of existence you specify. A creature so transported must find its own way back to your current plane of existence.',
    higherLevels: '',
    classes: ['Cleric', 'Druid', 'Sorcerer', 'Warlock', 'Wizard'],
    attackType: 'melee', damage: '', damageType: '', scaling: '',
    savingThrow: 'CHA', saveEffect: 'not banished',
  },
  {
    name: 'Power Word Pain', level: 7, school: 'Enchantment',
    castingTime: '1 action', range: '60 feet',
    components: ['V'], materialComponent: '',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You speak a word of power that causes waves of intense pain to assail one creature you can see within range. If the target has 100 hit points or fewer, it is subject to crippling pain. Otherwise, the spell has no effect on it. A target is also unaffected if it is immune to being charmed.\n\nWhile the target is affected by crippling pain, any speed it has can be no higher than 10 feet. The target also has disadvantage on attack rolls, ability checks, and saving throws, other than Constitution saving throws. Finally, if the target tries to cast a spell, it must first succeed on a Constitution saving throw, or the casting fails and the spell is wasted.\n\nA target suffering this pain can make a Constitution saving throw at the end of each of its turns. On a successful save, the pain ends.',
    higherLevels: '',
    classes: ['Sorcerer', 'Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'CON', saveEffect: 'ends pain',
  },
  {
    name: 'Prismatic Spray', level: 7, school: 'Evocation',
    castingTime: '1 action', range: 'Self (60-foot cone)',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'Eight multicolored rays of light flash from your hand. Each ray is a different color and has a different power and purpose. Each creature in a 60-foot cone must make a Dexterity saving throw. For each target, roll a d8 to determine which color ray affects it.\n\n1 — Red. The target takes 10d6 fire damage on a failed save, or half as much damage on a successful one.\n\n2 — Orange. The target takes 10d6 acid damage on a failed save, or half as much damage on a successful one.\n\n3 — Yellow. The target takes 10d6 lightning damage on a failed save, or half as much damage on a successful one.\n\n4 — Green. The target takes 10d6 poison damage on a failed save, or half as much damage on a successful one.\n\n5 — Blue. The target takes 10d6 cold damage on a failed save, or half as much damage on a successful one.\n\n6 — Indigo. On a failed save, the target is restrained. It must then make a Constitution saving throw at the end of each of its turns. If it successfully saves three times, the spell ends. If it fails its save three times, it permanently turns to stone and is subjected to the petrified condition. The successes and failures don\'t need to be consecutive; keep track of both until the target collects three of a kind.\n\n7 — Violet. On a failed save, the target is blinded. It must then make a Wisdom saving throw at the start of your next turn. A successful save ends the blindness. If it fails that save, the creature is transported to another plane of existence of the DM\'s choosing and is no longer blinded. (Typically, a creature that is on a plane that isn\'t its home plane is banished home, while other creatures are usually cast into the Astral or Ethereal planes.)\n\n8 — Special. The target is struck by two rays. Roll twice more, rerolling any 8.',
    higherLevels: '',
    classes: ['Sorcerer', 'Wizard'],
    attackType: '', damage: '10d6', damageType: '', scaling: '',
    savingThrow: 'DEX', saveEffect: 'half damage or negates',
  },
  {
    name: 'Project Image', level: 7, school: 'Illusion',
    castingTime: '1 action', range: '500 miles',
    components: ['V', 'S', 'M'], materialComponent: 'a small replica of you made from materials worth at least 5 gp',
    duration: 'Concentration, up to 1 day', concentration: true, ritual: false,
    description: 'You create an illusory copy of yourself that lasts for the duration. The copy can appear at any location within range that you have seen before, regardless of intervening obstacles. The illusion looks and sounds like you but is intangible. If the illusion takes any damage, it disappears, and the spell ends.\n\nYou can use your action to move this illusion up to twice your speed, and make it gesture, speak, and behave in whatever way you choose. It mimics your mannerisms perfectly.\n\nYou can see through its eyes and hear through its ears as if you were in its space. On your turn as a bonus action, you can switch from using its senses to using your own, or back again. While you are using its senses, you are blinded and deafened in regard to your own surroundings.\n\nPhysical interaction with the image reveals it to be an illusion, because things can pass through it. A creature that uses its action to examine the image can determine that it is an illusion with a successful Intelligence (Investigation) check against your spell save DC. If a creature discerns the illusion for what it is, the creature can see through the image, and any noise it makes sounds hollow to the creature.',
    higherLevels: '',
    classes: ['Bard', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Regenerate', level: 7, school: 'Transmutation',
    castingTime: '1 minute', range: 'Touch',
    components: ['V', 'S', 'M'], materialComponent: 'a prayer wheel and holy water',
    duration: '1 hour', concentration: false, ritual: false,
    description: 'You touch a creature and stimulate its natural healing ability. The target regains 4d8 + 15 hit points. For the duration of the spell, the target regains 1 hit point at the start of each of its turns (10 hit points each minute).\n\nThe target\'s severed body members (fingers, legs, tails, and so on), if any, are restored after 2 minutes. If you have the severed part and hold it to the stump, the spell instantaneously causes the limb to knit to the stump.',
    higherLevels: '',
    classes: ['Bard', 'Cleric', 'Druid'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Resurrection', level: 7, school: 'Necromancy',
    castingTime: '1 hour', range: 'Touch',
    components: ['V', 'S', 'M'], materialComponent: 'a diamond worth at least 1,000 gp, which the spell consumes',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You touch a creature that has been deceased for no more than a century, that didn\'t die of old age, and that isn\'t undead. If its soul is free and willing, the target returns to life with all its hit points.\n\nThis spell neutralizes any poisons and cures normal diseases afflicting the creature when it died. It doesn\'t, however, remove magical diseases, curses, and the like; if such effects aren\'t removed prior to casting the spell, they afflict the target on its return to life.\n\nThis spell closes all mortal wounds and restores any missing body parts.\n\nComing back from the dead is an ordeal. The target takes a -4 penalty to all attack rolls, saving throws, and ability checks. Every time the target finishes a long rest, the penalty is reduced by 1 until it disappears.\n\nCasting this spell to restore life to a creature that has been dead for one year or longer taxes you greatly. Until you finish a long rest, you can\'t cast spells again, and you have disadvantage on all attack rolls, ability checks, and saving throws.',
    higherLevels: '',
    classes: ['Bard', 'Cleric'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Reverse Gravity', level: 7, school: 'Transmutation',
    castingTime: '1 action', range: '100 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a lodestone and iron filings',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'This spell reverses gravity in a 50-foot-radius, 100-foot-high cylinder centered on a point within range. All creatures and objects that aren\'t somehow anchored to the ground in the area fall upward and reach the top of the area when you cast this spell. A creature can make a Dexterity saving throw to grab onto a fixed object it can reach, thus avoiding the fall.\n\nIf some solid object (such as a ceiling) is encountered in the fall, falling objects and creatures strike it just as they would during a normal downward fall. If an object or creature reaches the top of the area without striking anything, it remains there, oscillating slightly, for the duration.\n\nAt the end of the duration, affected objects and creatures fall back down.',
    higherLevels: '',
    classes: ['Druid', 'Sorcerer', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'DEX', saveEffect: 'grabs fixed object',
  },
  {
    name: 'Sequester', level: 7, school: 'Transmutation',
    castingTime: '1 action', range: 'Touch',
    components: ['V', 'S', 'M'], materialComponent: 'a powder composed of diamond, emerald, ruby, and sapphire dust worth at least 5,000 gp, which the spell consumes',
    duration: 'Until dispelled', concentration: false, ritual: false,
    description: 'By means of this spell, a willing creature or an object can be hidden away, safe from detection for the duration. When you cast the spell and touch the target, it becomes invisible and can\'t be targeted by divination spells or perceived through scrying sensors created by divination spells.\n\nIf the target is a creature, it falls into a state of suspended animation. Time ceases to flow for it, and it doesn\'t age.\n\nYou can set a condition for the spell to end early. The condition can be anything you choose, but it must occur or be visible within 1 mile of the target. Examples include "after 1,000 years" or "when the tarrasque awakens." This spell also ends if the target takes any damage.',
    higherLevels: '',
    classes: ['Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Simulacrum', level: 7, school: 'Illusion',
    castingTime: '12 hours', range: 'Touch',
    components: ['V', 'S', 'M'], materialComponent: 'snow or ice in quantities sufficient to make a life-size copy of the duplicated creature; some hair, fingernail clippings, or other piece of that creature\'s body placed inside the snow or ice; and powdered ruby worth 1,500 gp, sprinkled over the duplicate and consumed by the spell',
    duration: 'Until dispelled', concentration: false, ritual: false,
    description: 'You shape an illusory duplicate of one beast or humanoid that is within range for the entire casting time of the spell. The duplicate is a creature, partially real and formed from ice or snow, and it can take actions and otherwise be affected as a normal creature. It appears to be the same as the original, but it has half the creature\'s hit point maximum and is formed without any equipment. Otherwise, the illusion uses all the statistics of the creature it duplicates, except that it is a construct.\n\nThe simulacrum is friendly to you and creatures you designate. It obeys your spoken commands, moving and acting in accordance with your wishes and acting on your turn in combat. The simulacrum lacks the ability to learn or become more powerful, so it never increases its level or other abilities, nor can it regain expended spell slots.\n\nIf the simulacrum is damaged, you can repair it in an alchemical laboratory, using rare herbs and minerals worth 100 gp per hit point it regains. If the simulacrum is destroyed, it reverts to snow and melts instantly. If you cast this spell again, any currently active duplicates you created with this spell are instantly destroyed.',
    higherLevels: '',
    classes: ['Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Symbol', level: 7, school: 'Abjuration',
    castingTime: '1 minute', range: 'Touch',
    components: ['V', 'S', 'M'], materialComponent: 'mercury, phosphorus, and powdered diamond and opal with a total value of at least 1,000 gp, which the spell consumes',
    duration: 'Until dispelled or triggered', concentration: false, ritual: false,
    description: 'When you cast this spell, you inscribe a harmful glyph either on a surface (such as a section of floor, a wall, or a table) or within an object that can be closed to conceal the glyph (such as a book, a scroll, or a treasure chest). If you choose a surface, the glyph can cover an area of the surface no larger than 10 feet in diameter. If you choose an object, that object must remain in its place; if the object is moved more than 10 feet from where you cast this spell, the glyph is broken, and the spell ends without being triggered.\n\nThe glyph is nearly invisible, requiring an Intelligence (Investigation) check against your spell save DC to find it.\n\nYou decide what triggers the glyph when you cast the spell. For glyphs inscribed on a surface, the most typical triggers include touching or stepping on the glyph, removing another object covering it, approaching within a certain distance of it, or manipulating the object that holds it. For glyphs inscribed within an object, the most common triggers are opening the object, approaching within a certain distance of it, or seeing or reading the glyph.\n\nOnce a glyph is triggered, this spell ends. When the glyph is triggered, it fills a 60-foot-radius sphere with dim light for 10 minutes, after which time the spell ends. Each creature in the sphere when the glyph activates is targeted by its effect, as is a creature that enters the sphere for the first time on a turn or ends its turn there.\n\nWhen you inscribe the glyph, choose one of the following options:\n\nDeath. Each target must make a Constitution saving throw, taking 10d10 necrotic damage on a failed save, or half as much damage on a successful one.\n\nDiscord. Each target must make a Constitution saving throw. On a failed save, a target bickers and argues with other creatures for 1 minute. During this time, it is incapable of meaningful communication and has disadvantage on attack rolls and ability checks.\n\nFear. Each target must make a Wisdom saving throw and becomes frightened for 1 minute on a failed save. While frightened, the target drops whatever it is holding and must move at least 30 feet away from the glyph on each of its turns, if able.\n\nHopelessness. Each target must make a Charisma saving throw. On a failed save, the target is overwhelmed with despair for 1 minute. During this time, it can\'t attack or target any creature with harmful abilities, spells, or other magical effects.\n\nInsanity. Each target must make an Intelligence saving throw. On a failed save, the target is driven insane for 1 minute. An insane creature can\'t take actions, can\'t understand what other creatures say, can\'t read, and speaks only in gibberish. The DM controls its movement, which is erratic.\n\nPain. Each target must make a Constitution saving throw and becomes incapacitated for 1 minute on a failed save.\n\nSleep. Each target must make a Wisdom saving throw and falls unconscious for 10 minutes on a failed save. A creature awakens if it takes damage or if someone uses an action to shake or slap it awake.\n\nStunning. Each target must make a Wisdom saving throw and becomes stunned for 1 minute on a failed save.',
    higherLevels: '',
    classes: ['Bard', 'Cleric', 'Wizard'],
    attackType: '', damage: '10d10', damageType: 'necrotic', scaling: '',
    savingThrow: 'CON', saveEffect: 'half damage (Death option)',
  },
  {
    name: 'Temple of the Gods', level: 7, school: 'Conjuration',
    castingTime: '1 hour', range: '120 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a holy symbol worth at least 5 gp',
    duration: '24 hours', concentration: false, ritual: false,
    description: 'You cause a temple to shimmer into existence on ground you can see within range. The temple must fit within an unoccupied cube of space, up to 120 feet on each side. The temple remains until the spell ends. It is dedicated to whatever god, pantheon, or philosophy is represented by the holy symbol used in the casting.\n\nYou make all decisions about the temple\'s appearance. The interior is enclosed by a floor, walls, and a roof, with one door granting access to the interior and as many windows as you wish. Only you and any creatures you designate when you cast the spell can open or close the door.\n\nThe temple\'s interior is an open space with an idol or altar at one end. You decide whether the temple is illuminated and whether that illumination is bright light or dim light. The smell of burning incense fills the air within, and the temperature is mild.\n\nThe temple opposes types of creatures you choose when you cast this spell. Choose one or more of the following: celestials, elementals, fey, fiends, or undead. If a creature of the chosen type attempts to enter the temple, that creature must make a Charisma saving throw. On a failed save, it can\'t enter the temple for 24 hours. Even if the creature can enter the temple, the magic there hinders it; whenever it makes an attack roll, an ability check, or a saving throw inside the temple, it must roll a d4 and subtract the number rolled from the d20 roll.\n\nIn addition, the sensors created by divination spells can\'t appear inside the temple, and creatures within can\'t be targeted by divination spells.\n\nFinally, whenever any creature in the temple regains hit points from a spell of 1st level or higher, the creature regains additional hit points equal to your Wisdom modifier (minimum 1 hit point).\n\nThe temple is made from opaque magical force that extends into the Ethereal Plane, thus blocking ethereal travel into the temple\'s interior. Nothing can physically pass through the temple\'s exterior. It can\'t be dispelled by dispel magic, and antimagic field has no effect on it. A disintegrate spell destroys the temple instantly.\n\nCasting this spell on the same spot every day for a year makes this effect permanent.',
    higherLevels: '',
    classes: ['Cleric'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'CHA', saveEffect: 'can enter temple',
  },
  {
    name: 'Tether Essence', level: 7, school: 'Necromancy',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a spool of platinum cord worth at least 250 gp, which the spell consumes',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'Two creatures you can see within range must make Constitution saving throws, with disadvantage if they are within 30 feet of each other. Either creature can willingly fail the save. If either save succeeds, the spell has no effect. If both saves fail, the creatures are magically linked for the duration, regardless of the distance between them. When damage is dealt to one of them, the same damage is dealt to the other one. If one of them regains hit points, the other one also regains the same number of hit points. If either of the tethered creatures is reduced to 0 hit points, the spell ends on both. If the spell ends on one creature, it ends on both.',
    higherLevels: '',
    classes: ['Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'CON', saveEffect: 'negates',
  },
  {
    name: 'Whirlwind', level: 7, school: 'Evocation',
    castingTime: '1 action', range: '300 feet',
    components: ['V', 'M'], materialComponent: 'a piece of straw',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'A whirlwind howls down to a point that you can see on the ground within range. The whirlwind is a 10-foot-radius, 30-foot-high cylinder centered on that point. Until the spell ends, you can use your action to move the whirlwind up to 30 feet in any direction along the ground. The whirlwind sucks up any Medium or smaller objects that aren\'t secured to anything and that aren\'t worn or carried by anyone.\n\nA creature must make a Dexterity saving throw the first time on a turn that it enters the whirlwind or that the whirlwind enters its space, including when the whirlwind first appears. A creature takes 10d6 bludgeoning damage on a failed save, or half as much damage on a successful one. In addition, a Large or smaller creature that fails the save must succeed on a Strength saving throw or become restrained in the whirlwind until the spell ends. When a creature starts its turn restrained by the whirlwind, the creature is pulled 5 feet higher inside it, unless the creature is at the top. A restrained creature moves with the whirlwind and falls when the spell ends, unless the creature has some means to stay aloft.\n\nA restrained creature can use an action to make a Strength or Dexterity check against your spell save DC. If successful, the creature is no longer restrained by the whirlwind and is hurled 3d6 × 10 feet away from it in a random direction.',
    higherLevels: '',
    classes: ['Druid', 'Sorcerer', 'Wizard'],
    attackType: '', damage: '10d6', damageType: 'bludgeoning', scaling: '',
    savingThrow: 'DEX', saveEffect: 'half damage',
  },
];

(async () => {
  await mongoose.connect(process.env.MONGODB_URI);
  for (const sp of SPELLS) await Spell.findOneAndUpdate({ name: sp.name, level: sp.level }, sp, { upsert: true });
  console.log(`Seeded ${SPELLS.length} level-7 spells`);
  process.exit(0);
})();
