require('dotenv').config();
const mongoose = require('mongoose');
const Spell = require('./models/Spell');

const SPELLS = [
  {
    name: "Abi-Dalzim's Horrid Wilting", level: 8, school: 'Necromancy',
    castingTime: '1 action', range: '150 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a bit of sponge',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You draw the moisture from every creature in a 30-foot cube centered on a point you choose within range. Each creature in that area must make a Constitution saving throw. Constructs and undead aren\'t affected, and plants and water elementals make this saving throw with disadvantage. A creature takes 12d8 necrotic damage on a failed save, or half as much damage on a successful one.\n\nNonmagical plants in the area that aren\'t creatures, such as trees and shrubs, wither and die instantly.',
    higherLevels: '',
    classes: ['Sorcerer', 'Wizard'],
    attackType: '', damage: '12d8', damageType: 'necrotic', scaling: '',
    savingThrow: 'CON', saveEffect: 'half damage',
  },
  {
    name: 'Animal Shapes', level: 8, school: 'Transmutation',
    castingTime: '1 action', range: '30 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 24 hours', concentration: true, ritual: false,
    description: 'Your magic turns others into beasts. Choose any number of willing creatures that you can see within range. You transform each target into the form of a Large or smaller beast with a challenge rating of 4 or lower. On subsequent turns, you can use your action to transform affected creatures into new forms.\n\nThe transformation lasts for the duration for each target, or until the target drops to 0 hit points or dies. You can choose a different form for each target. A target\'s game statistics are replaced by the statistics of the chosen beast, though the target retains its alignment and Intelligence, Wisdom, and Charisma scores. The target assumes the hit points of its new form, and when it reverts to its normal form, it returns to the number of hit points it had before it transformed. If it reverts as a result of dropping to 0 hit points, any excess damage carries over to its normal form. As long as the excess damage doesn\'t reduce the creature\'s normal form to 0 hit points, it isn\'t knocked unconscious. The creature is limited in the actions it can perform by the nature of its new form, and it can\'t speak or cast spells. The target\'s gear melds into the new form. The target can\'t activate, wield, or otherwise benefit from any of its equipment.',
    higherLevels: '',
    classes: ['Druid'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Antimagic Field', level: 8, school: 'Abjuration',
    castingTime: '1 action', range: 'Self (10-foot-radius sphere)',
    components: ['V', 'S', 'M'], materialComponent: 'a pinch of powdered iron or iron filings',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'A 10-foot-radius invisible sphere of antimagic surrounds you. This area is divorced from the magical energy that suffuses the multiverse. Within the sphere, spells can\'t be cast, summoned creatures disappear, and even magic items become mundane. Until the spell ends, the sphere moves with you, centered on you.\n\nSpells and other magical effects, except those created by an artifact or a deity, are suppressed in the sphere and can\'t protrude into it. A slot expended to cast a suppressed spell is consumed. While an effect is suppressed, it doesn\'t function, but the time it spends suppressed counts against its duration.\n\nTargeted Effects. Spells and other magical effects that target a creature or an object in the sphere have no effect on that target.\n\nAreas of Magic. The area of another spell or magical effect, such as fireball, can\'t extend into the sphere. If the sphere overlaps an area of magic, the part of the area that is covered by the sphere is suppressed.\n\nSpells. Any active spell or other magical effect on a creature or an object in the sphere is suppressed while the creature or object is in it.\n\nMagic Items. The properties and powers of magic items are suppressed in the sphere. A magic weapon becomes mundane within it.\n\nMagical Travel. Teleportation and planar travel fail to work in the sphere, whether the sphere is the destination or the departure point.\n\nCreatures and Objects. A creature or object summoned or created by magic temporarily winks out of existence in the sphere. Such a creature instantly reappears once the space the creature occupied is no longer within the sphere.\n\nDispel Magic. Spells and magical effects such as dispel magic have no effect on the sphere. Likewise, the spheres created by different antimagic field spells don\'t nullify each other.',
    higherLevels: '',
    classes: ['Cleric', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Antipathy/Sympathy', level: 8, school: 'Enchantment',
    castingTime: '1 hour', range: '60 feet',
    components: ['V', 'S', 'M'], materialComponent: 'either a lump of alum soaked in vinegar for the antipathy effect or a drop of honey for the sympathy effect',
    duration: '10 days', concentration: false, ritual: false,
    description: 'This spell attracts or repels creatures of your choice. You target something within range, either a Huge or smaller object or creature or an area that is no larger than a 200-foot cube. Then specify a kind of intelligent creature, such as red dragons, goblins, or vampires. You imbue the target with an aura that either attracts or repels the specified creatures for the duration. Choose antipathy or sympathy as the aura\'s effect.\n\nAntipathy. The enchantment causes creatures of the kind you designated to feel an intense urge to leave the area and avoid the target. When such a creature can see the target or comes within 60 feet of it, the creature must succeed on a Wisdom saving throw or become frightened. The creature remains frightened while it can see the target or is within 60 feet of it. While frightened by the target, the creature must use its movement to move to the nearest safe spot from which it can\'t see the target. If the creature moves more than 60 feet from the target and can\'t see it, the creature is no longer frightened, but the creature becomes frightened again if it regains sight of the target or moves within 60 feet of it.\n\nSympathy. The enchantment causes the specified creatures to feel an intense urge to approach the target while within 60 feet of it or able to see it. When such a creature can see the target or comes within 60 feet of it, the creature must succeed on a Wisdom saving throw or use its movement on each of its turns to enter the area or move within reach of the target. When the creature has done so, it can\'t willingly move away from the target. If the target damages or otherwise harms an affected creature, the affected creature can make a Wisdom saving throw to end the effect.\n\nEnding the Effect. If an affected creature ends its turn while not within 60 feet of the target or able to see it, the creature makes a Wisdom saving throw. On a successful save, the creature is no longer affected by the target and recognizes the feeling of repugnance or attraction as magical. In addition, a creature affected by the spell is allowed to make another Wisdom saving throw every 24 hours while the spell persists.\n\nA creature that successfully saves against this effect is immune to it for 1 minute, after which time it can be affected again.',
    higherLevels: '',
    classes: ['Bard', 'Druid', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'WIS', saveEffect: 'negates',
  },
  {
    name: 'Clone', level: 8, school: 'Necromancy',
    castingTime: '1 hour', range: 'Touch',
    components: ['V', 'S', 'M'], materialComponent: 'a diamond worth at least 1,000 gp and at least 1 cubic inch of flesh of the creature that is to be cloned, which the spell consumes, and a vessel worth at least 2,000 gp that has a sealable lid and is large enough to hold a Medium creature',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'This spell grows an inert duplicate of a living, Medium creature as a safeguard against death. This clone forms inside a sealed vessel and grows to full size and maturity after 120 days; you can also choose to have the clone be a younger version of the same creature. It remains inert and endures indefinitely, as long as its vessel remains undisturbed.\n\nAt any time after the clone matures, if the original creature dies, its soul transfers to the clone, provided that the soul is free and willing to return. The clone is physically identical to the original and has the same personality, memories, and abilities, but none of the original\'s equipment. The original creature\'s physical remains, if they still exist, become inert and can\'t thereafter be restored to life, since the creature\'s soul is elsewhere.',
    higherLevels: '',
    classes: ['Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Control Weather', level: 8, school: 'Transmutation',
    castingTime: '10 minutes', range: 'Self (5-mile radius)',
    components: ['V', 'S', 'M'], materialComponent: 'burning incense and bits of earth and wood mixed in water',
    duration: 'Concentration, up to 8 hours', concentration: true, ritual: false,
    description: 'You take control of the weather within 5 miles of you for the duration. You must be outdoors to cast this spell. Moving to a place where you don\'t have a clear path to the sky ends the spell early.\n\nWhen you cast the spell, you change the current weather conditions, which are determined by the DM based on the climate and season. You can change precipitation, temperature, and wind. It takes 1d4 × 10 minutes for the new conditions to take effect. Once they do so, you can change the conditions again. When the spell ends, the weather gradually returns to normal.\n\nWhen you change the weather conditions, find a current condition on the following tables and change its stage by one, up or down. When changing the wind, you can change its direction.\n\nPrecipitation: Clear, Light clouds, Overcast/ground fog, Rain/hail/snow, Torrential rain/driving hail/blizzard\n\nTemperature: Unbearable heat, Hot, Warm, Cool, Cold, Arctic cold\n\nWind: Calm, Moderate wind, Strong wind, Gale, Storm',
    higherLevels: '',
    classes: ['Cleric', 'Druid', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Dark Star', level: 8, school: 'Evocation',
    castingTime: '1 action', range: '150 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a shard of onyx and a drop of the caster\'s blood, both of which the spell consumes',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'This spell creates a sphere centered on a point you choose within range. The sphere can have a radius of up to 40 feet. The area within this sphere is filled with magical darkness and crushing gravitational force.\n\nFor the duration, the spell\'s area is difficult terrain. A creature with darkvision can\'t see through the magical darkness, and nonmagical light can\'t illuminate it. No sound can be created within or pass through the area. Any creature or object entirely inside the sphere is immune to thunder damage, and creatures are deafened while entirely inside it. Casting a spell that includes a verbal component is impossible there.\n\nAny creature that enters the spell\'s area for the first time on a turn or starts its turn there must make a Constitution saving throw. The creature takes 8d10 force damage on a failed save, or half as much damage on a successful one. A creature reduced to 0 hit points by this damage is disintegrated. A disintegrated creature and everything it is wearing and carrying, except magic items, are reduced to a pile of fine gray dust.',
    higherLevels: '',
    classes: ['Wizard'],
    attackType: '', damage: '8d10', damageType: 'force', scaling: '',
    savingThrow: 'CON', saveEffect: 'half damage',
  },
  {
    name: 'Demiplane', level: 8, school: 'Conjuration',
    castingTime: '1 action', range: '60 feet',
    components: ['S'], materialComponent: '',
    duration: '1 hour', concentration: false, ritual: false,
    description: 'You create a shadowy door on a flat solid surface that you can see within range. The door is large enough to allow Medium creatures to pass through unhindered. When opened, the door leads to a demiplane that appears to be an empty room 30 feet in each dimension, made of wood or stone. When the spell ends, the door disappears, and any creatures or objects inside the demiplane remain trapped there, as the door also disappears from the other side.\n\nEach time you cast this spell, you can create a new demiplane, or have the shadowy door connect to a demiplane you created with a previous casting of this spell. Additionally, if you know the nature and contents of a demiplane created by a casting of this spell by another creature, you can have the shadowy door connect to its demiplane instead.',
    higherLevels: '',
    classes: ['Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Dominate Monster', level: 8, school: 'Enchantment',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'You attempt to beguile a creature that you can see within range. It must succeed on a Wisdom saving throw or be charmed by you for the duration. If you or creatures that are friendly to you are fighting it, it has advantage on the saving throw.\n\nWhile the creature is charmed, you have a telepathic link with it as long as the two of you are on the same plane of existence. You can use this telepathic link to issue commands to the creature while you are conscious (no action required), which it does its best to obey. You can specify a simple and general course of action, such as "Attack that creature," "Run over there," or "Fetch that object." If the creature completes the order and doesn\'t receive further direction from you, it defends and preserves itself to the best of its ability.\n\nYou can use your action to take total and precise control of the target. Until the end of your next turn, the creature takes only the actions you choose, and doesn\'t do anything that you don\'t allow it to do.\n\nEach time the target takes damage, it makes a new Wisdom saving throw against the spell. If the saving throw succeeds, the spell ends.',
    higherLevels: 'When you cast this spell with a 9th-level spell slot, the duration is concentration, up to 8 hours.',
    classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'WIS', saveEffect: 'negates',
  },
  {
    name: 'Earthquake', level: 8, school: 'Evocation',
    castingTime: '1 action', range: '500 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a pinch of dirt, a piece of rock, and a lump of clay',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You create a seismic disturbance at a point on the ground that you choose within range. For the duration, an intense tremor rips through the ground in a 100-foot-radius circle centered on that point and shakes creatures and structures in contact with the ground in that area.\n\nThe ground in the area becomes difficult terrain. Each creature on the ground that is concentrating must make a Constitution saving throw. On a failed save, the creature\'s concentration is broken.\n\nWhen you cast this spell and at the end of each turn you spend concentrating on it, each creature on the ground in the area must make a Dexterity saving throw. On a failed save, the creature is knocked prone.\n\nThis spell can have additional effects depending on the terrain in the area, as determined by the DM.\n\nFissures. Fissures open throughout the spell\'s area at the start of your next turn after you cast the spell. A total of 1d6 such fissures open in locations chosen by the DM. Each is 1d10 × 10 feet deep, 10 feet wide, and extends from one edge of the spell\'s area to the opposite side. A creature standing on a spot where a fissure opens must succeed on a Dexterity saving throw or fall in. A creature that successfully saves moves with the fissure\'s edge as it opens. A fissure that opens beneath a structure causes it to automatically collapse (see below).\n\nStructures. The tremor deals 50 bludgeoning damage to any structure in contact with the ground in the area when you cast the spell and at the start of each of your turns until the spell ends. If a structure drops to 0 hit points, it collapses and potentially damages nearby creatures. A creature within half the distance of a structure\'s height must make a Dexterity saving throw. On a failed save, the creature takes 5d6 bludgeoning damage, is knocked prone, and is buried in the rubble, requiring a DC 20 Strength (Athletics) check as an action to escape. On a successful save, the creature takes half as much damage and isn\'t knocked prone or buried.',
    higherLevels: '',
    classes: ['Cleric', 'Druid', 'Sorcerer'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'DEX', saveEffect: 'not knocked prone',
  },
  {
    name: 'Feeblemind', level: 8, school: 'Enchantment',
    castingTime: '1 action', range: '150 feet',
    components: ['V', 'S', 'M'], materialComponent: 'a handful of clay, crystal, glass, or mineral spheres',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You blast the mind of a creature that you can see within range, attempting to shatter its intellect and personality. The target takes 4d6 psychic damage and must make an Intelligence saving throw.\n\nOn a failed save, the creature\'s Intelligence and Charisma scores become 1. The creature can\'t cast spells, activate magic items, understand language, or communicate in any intelligible way. The creature can, however, identify its friends, follow them, and even protect them.\n\nAt the end of every 30 days, the creature can repeat its saving throw against this spell. If it succeeds on its saving throw, the spell ends. The spell can also be ended by greater restoration, heal, or wish.',
    higherLevels: '',
    classes: ['Bard', 'Druid', 'Warlock', 'Wizard'],
    attackType: '', damage: '4d6', damageType: 'psychic', scaling: '',
    savingThrow: 'INT', saveEffect: 'negates (takes damage only)',
  },
  {
    name: 'Glibness', level: 8, school: 'Transmutation',
    castingTime: '1 action', range: 'Self',
    components: ['V'], materialComponent: '',
    duration: '1 hour', concentration: false, ritual: false,
    description: 'Until the spell ends, when you make a Charisma check, you can replace the number you roll with a 15. Additionally, no matter what you say, magic that would determine if you are telling the truth indicates that you are being truthful.',
    higherLevels: '',
    classes: ['Bard', 'Warlock'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Holy Aura', level: 8, school: 'Abjuration',
    castingTime: '1 action', range: 'Self',
    components: ['V', 'S', 'M'], materialComponent: 'a tiny reliquary worth at least 1,000 gp containing a sacred relic, such as a scrap of cloth from a saint\'s robe or a piece of parchment from a religious text',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'Divine light washes out from you and coalesces in a soft radiance in a 30-foot radius around you. Creatures of your choice in that radius when you cast this spell shed dim light in a 5-foot radius and have advantage on all saving throws, and other creatures have disadvantage on attack rolls against them until the spell ends. In addition, when a fiend or an undead hits an affected creature with a melee attack, the aura flashes with brilliant light. The attacker must succeed on a Constitution saving throw or be blinded until the spell ends.',
    higherLevels: '',
    classes: ['Cleric'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'CON', saveEffect: 'not blinded',
  },
  {
    name: 'Illusory Dragon', level: 8, school: 'Illusion',
    castingTime: '1 action', range: '120 feet',
    components: ['S'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'By gathering threads of shadow material from the Shadowfell, you create a Huge shadowy dragon in an unoccupied space that you can see within range. The illusion lasts for the spell\'s duration and occupies its space, as if it were a creature.\n\nWhen the illusion appears, any of your enemies that can see it must succeed on a Wisdom saving throw or become frightened of it for 1 minute. If a frightened creature ends its turn in a location where it doesn\'t have line of sight to the illusion, it can repeat the saving throw, ending the effect on itself on a success.\n\nAs a bonus action on your turn, you can move the illusion up to 60 feet. At any point during its movement, you can cause it to exhale a blast of energy in a 60-foot cone originating from its space. When you create the dragon, choose a damage type: acid, cold, fire, lightning, necrotic, or poison. Each creature in the cone must make an Intelligence saving throw, taking 7d6 damage of the chosen type on a failed save, or half as much damage on a successful one.\n\nThe illusion is tangible because of the shadow stuff used to create it, but attacks miss it automatically, it succeeds on all saving throws, and it is immune to all damage and conditions. A creature that uses an action to examine the dragon can determine that it is an illusion by succeeding on an Intelligence (Investigation) check against your spell save DC. If a creature discerns the illusion for what it is, the creature can see through it and has advantage on saving throws against its breath.',
    higherLevels: '',
    classes: ['Wizard'],
    attackType: '', damage: '7d6', damageType: '', scaling: '',
    savingThrow: 'INT', saveEffect: 'half damage',
  },
  {
    name: 'Incendiary Cloud', level: 8, school: 'Conjuration',
    castingTime: '1 action', range: '150 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'A swirling cloud of smoke shot through with white-hot embers appears in a 20-foot-radius sphere centered on a point within range. The cloud spreads around corners and is heavily obscured. It lasts for the duration or until a wind of moderate or greater speed (at least 10 miles per hour) disperses it.\n\nWhen the cloud appears, each creature in it must make a Dexterity saving throw. A creature takes 10d8 fire damage on a failed save, or half as much damage on a successful one. A creature must also make this saving throw when it enters the spell\'s area for the first time on a turn or ends its turn there.\n\nThe cloud moves 10 feet directly away from you in a direction that you choose at the start of each of your turns.',
    higherLevels: '',
    classes: ['Sorcerer', 'Wizard'],
    attackType: '', damage: '10d8', damageType: 'fire', scaling: '',
    savingThrow: 'DEX', saveEffect: 'half damage',
  },
  {
    name: 'Maddening Darkness', level: 8, school: 'Evocation',
    castingTime: '1 action', range: '150 feet',
    components: ['V', 'M'], materialComponent: 'a drop of pitch mixed with a drop of mercury',
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: false,
    description: 'Magical darkness spreads from a point you choose within range to fill a 60-foot-radius sphere until the spell ends. The darkness spreads around corners. A creature with darkvision can\'t see through this darkness. Nonmagical light, as well as light created by spells of 8th level or lower, can\'t illuminate the area.\n\nShrieks, gibbering, and mad laughter can be heard within the sphere. Whenever a creature starts its turn in the sphere, it must make a Wisdom saving throw, taking 8d8 psychic damage on a failed save, or half as much damage on a successful one.',
    higherLevels: '',
    classes: ['Warlock', 'Wizard'],
    attackType: '', damage: '8d8', damageType: 'psychic', scaling: '',
    savingThrow: 'WIS', saveEffect: 'half damage',
  },
  {
    name: 'Maze', level: 8, school: 'Conjuration',
    castingTime: '1 action', range: '60 feet',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: false,
    description: 'You banish a creature that you can see within range into a labyrinthine demiplane. The target remains there for the duration or until it escapes the maze.\n\nThe target can use its action to attempt to escape. When it does so, it makes a DC 20 Intelligence check. If it succeeds, it escapes, and the spell ends (a minotaur or goristro demon automatically succeeds).\n\nWhen the spell ends, the target reappears in the space it left or, if that space is occupied, in the nearest unoccupied space.',
    higherLevels: '',
    classes: ['Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Mighty Fortress', level: 8, school: 'Conjuration',
    castingTime: '1 minute', range: '1 mile',
    components: ['V', 'S', 'M'], materialComponent: 'a diamond worth at least 500 gp, which the spell consumes',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'A fortress of stone erupts from a square area of ground of your choice that you can see within range. The area is 120 feet on each side, and it must not have any buildings or other structures on it. Any creatures in the area are harmlessly lifted up as the fortress rises.\n\nThe fortress has four turrets with square bases, each one 20 feet on a side and 30 feet tall, with pointed roofs. The turrets are connected to each other by walls that are each 80 feet long, creating an enclosed area. Each wall is 1 foot thick and is composed of panels that are 10 feet wide and 20 feet tall. Each panel is contiguous with two other panels or one other panel and a turret. You can place up to four stone doors in the fortress\'s outer wall.\n\nA small keep stands inside, taking up an area 50 feet on each side and 80 feet tall. The keep has three levels, connected by stone staircases, each with interior stone walls that divide the level into four equal-size rooms. The interior contains furniture and enough supplies (including food) to host up to one hundred people.\n\nThe fortress is furnished and decorated however you like, and it contains sufficient food to host a banquet for 100 people each day. The furniture, decorations, and food are all created by magic.\n\nIf casting this spell every day for a year on the same spot, the fortress becomes permanent.',
    higherLevels: '',
    classes: ['Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Mind Blank', level: 8, school: 'Abjuration',
    castingTime: '1 action', range: 'Touch',
    components: ['V', 'S'], materialComponent: '',
    duration: '24 hours', concentration: false, ritual: false,
    description: 'Until the spell ends, one willing creature you touch is immune to psychic damage, any effect that would sense its emotions or read its thoughts, divination spells, and the charmed condition. The spell even foils wish spells and spells or effects of similar power used to affect the target\'s mind or to gain information about the target.',
    higherLevels: '',
    classes: ['Bard', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Power Word Stun', level: 8, school: 'Enchantment',
    castingTime: '1 action', range: '60 feet',
    components: ['V'], materialComponent: '',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You speak a word of power that can overwhelm the mind of one creature you can see within range, leaving it dumbfounded. If the target has 150 hit points or fewer, it is stunned. Otherwise, the spell has no effect.\n\nThe stunned target must make a Constitution saving throw at the end of each of its turns. On a successful save, this stunning effect ends.',
    higherLevels: '',
    classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: 'CON', saveEffect: 'ends stun',
  },
  {
    name: 'Sunburst', level: 8, school: 'Evocation',
    castingTime: '1 action', range: '150 feet',
    components: ['V', 'S', 'M'], materialComponent: 'fire and a piece of sunstone',
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'Brilliant sunlight flashes in a 60-foot radius centered on a point you choose within range. Each creature in that light must make a Constitution saving throw. On a failed save, a creature takes 12d6 radiant damage and is blinded for 1 minute. On a successful save, it takes half as much damage and isn\'t blinded by this spell. Undead and oozes have disadvantage on this saving throw.\n\nA creature blinded by this spell makes another Constitution saving throw at the end of each of its turns. On a successful save, it is no longer blinded.\n\nThis spell dispels any darkness in its area that was created by a spell.',
    higherLevels: '',
    classes: ['Druid', 'Sorcerer', 'Wizard'],
    attackType: '', damage: '12d6', damageType: 'radiant', scaling: '',
    savingThrow: 'CON', saveEffect: 'half damage, not blinded',
  },
  {
    name: 'Telepathy', level: 8, school: 'Evocation',
    castingTime: '1 action', range: 'Unlimited',
    components: ['V', 'S', 'M'], materialComponent: 'a pair of linked silver rings',
    duration: '24 hours', concentration: false, ritual: false,
    description: 'You create a telepathic link between yourself and a willing creature with which you are familiar. The creature can be anywhere on the same plane of existence as you. The spell ends if you or the target are no longer on the same plane.\n\nUntil the spell ends, you and the target can instantaneously share words, images, sounds, and other sensory messages with one another through the link, and the target recognizes you as the creature it is communicating with. The spell enables a creature with an Intelligence score of at least 1 to understand the meaning of your words and take in the scope of any sensory messages you send to it.',
    higherLevels: '',
    classes: ['Wizard'],
    attackType: '', damage: '', damageType: '', scaling: '',
    savingThrow: '', saveEffect: '',
  },
  {
    name: 'Tsunami', level: 8, school: 'Conjuration',
    castingTime: '1 minute', range: 'Sight',
    components: ['V', 'S'], materialComponent: '',
    duration: 'Concentration, up to 6 rounds', concentration: true, ritual: false,
    description: 'A wall of water springs into existence at a point you choose within range. You can make the wall up to 300 feet long, 300 feet high, and 50 feet thick. The wall lasts for the duration.\n\nWhen the wall appears, each creature within its area must make a Strength saving throw. On a failed save, a creature takes 6d10 bludgeoning damage, or half as much damage on a successful save.\n\nAt the start of each of your turns after the wall appears, the wall, along with any creatures in it, moves 50 feet away from you. Any Huge or smaller creature inside the wall or whose space the wall enters when it moves must succeed on a Strength saving throw or take 5d10 bludgeoning damage. A creature can take this damage only once per round. At the end of the turn, the wall\'s height is reduced by 50 feet, and the damage creatures take from the spell on subsequent rounds is reduced by 1d10. When the wall reaches 0 feet in height, the spell ends.\n\nA creature caught in the wall can move by swimming. Because of the force of the wave, though, the creature must make a successful Strength (Athletics) check against your spell save DC in order to move at all. If it fails the check, it can\'t move. A creature that moves out of the area falls to the ground.',
    higherLevels: '',
    classes: ['Druid'],
    attackType: '', damage: '6d10', damageType: 'bludgeoning', scaling: '',
    savingThrow: 'STR', saveEffect: 'half damage',
  },
];

(async () => {
  await mongoose.connect(process.env.MONGODB_URI);
  for (const sp of SPELLS) await Spell.findOneAndUpdate({ name: sp.name, level: sp.level }, sp, { upsert: true });
  console.log(`Seeded ${SPELLS.length} level-8 spells`);
  process.exit(0);
})();
